### ISSUE TITLE
Mercurial repo badge is unknown

### ISSUE THREAD

**Issue by saaj** [codecov/support#10]
It seems to be a regression because it was working correctly for some time. Here's example.

https://codecov.io/bitbucket/saaj/cherrypy/coverage.svg?branch=default ![bug](
https://codecov.io/bitbucket/saaj/cherrypy/coverage.svg?branch=default)

But if you go to the [report page](https://codecov.io/bitbucket/saaj/cherrypy?branch=default) there's certain coverage value is available.

**Comment by stevepeak** [comment]
Fixed up. Thank you for reporting this issue.
