### ISSUE TITLE
weird coverage diff

### ISSUE THREAD

**Issue by kmike** [codecov/support#100]
Hey,

There is a weird coverage diff here: https://github.com/scrapy/scrapy/pull/1545 (see https://codecov.io/github/scrapy/scrapy/compare/8dc400c...ec47c42): 

* function declaration is marked as not covered while function body is marked as covered; 
* last line in a function body is marked as not covered while previous line is marked as covered (it should be also covered).

![screen shot 2015-10-17 at 4 07 40 am](https://cloud.githubusercontent.com/assets/107893/10555183/aeb4ddc0-7484-11e5-913b-933b43c3fc26.png)

Is it a codecov issue?

**Comment by stevepeak** [comment]
There was an offset issue for line numbers. Fixed and deployed! Thank you :+1:
