### ISSUE TITLE
Integration with Bitrise

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#103]
> cc @reidmweber @birmacher

@birmacher is helping out with integrating [Codecov Bash](https://github.com/codecov/codecov-bash) into [Bitrise](https://www.bitrise.io/).

- [x] prepare uploader with environment vars from Bitrise [`66f36f7`](https://github.com/codecov/codecov-bash/blob/66f36f76cbc7c4e6f1a7decebb518832e3ff214c/codecov#L274-L283)
- [x] add Codecov to Bitrise integrations

**Comment by Pavan-Concur** [comment]
+1

**Comment by stevepeak** [comment]
@birmacher may I help out in any way with this? Thank you

**Comment by birmacher** [comment]
@stevepeak Thanks, I think I have everything.
I'll start investigating it in the weekend and update the ticket when we are ready with it. I don't think it will take long!

**Comment by birmacher** [comment]
@stevepeak When I'm trying to upload the reports I get the following error:

```{(...) "error": {"type": "ValidationError", "reason": "service must be ci-provider", "context": "service"}}```

Can you please check it?

**Comment by stevepeak** [comment]
@birmacher this is my bad. I forgot to add `bitrise` to our backend. Adding now and I'll ping you here when I deploy. Thanks!

**Comment by stevepeak** [comment]
@birmacher Deployed. Thanks!

**Comment by stevepeak** [comment]
@birmacher is there an API endpoint Codecov can ping to verify uploads? This way a repository token is not necessary making it easier for customers to integrate. Thank you

**Comment by birmacher** [comment]
@stevepeak Thanks!

We don't have an API endpoint for something like this currently.

The first version of the integration is ready:
* I've sent a PR to update the bash runner: https://github.com/codecov/codecov-bash/pull/18
* We've updated the Xcode Test step to generate code coverage files optionally: https://github.com/bitrise-io/steps-xcode-test/pull/21
* Created the integration for Codecov: https://github.com/bitrise-io/steps-codecov

We will test it a bit after you've accepted the PR for the bash runner, and deploy the official integrations. I'll get back here when it's ready.

**Comment by stevepeak** [comment]
@birmacher new uploader is live, your welcome to proceed and test the integration.

**Comment by birmacher** [comment]
@stevepeak We've just deployed our Codecov integraton: https://www.bitrise.io/integrations & https://github.com/bitrise-io/steps-codecov
Try it out and let me know how it works! :)

**Comment by stevepeak** [comment]
Very good! Thank you.

The link on https://www.bitrise.io/integrations at Codecov **Source** is 404ing. I think its supposed to be to https://github.com/bitrise-io/steps-codecov

I've give it a shot shortly! Cheers!

**Comment by birmacher** [comment]
I've updated the `source` url to the correct one

**Comment by stevepeak** [comment]
Thank you @birmacher, I'll close this thread. Next step is to add Bitrise to our example repositories:

https://github.com/codecov/example-xcode
https://github.com/codecov/example-swift

Cheers!
