### ISSUE TITLE
Introduce .codecov.yml

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#105]
See https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a

Thank you!

**Comment by jayvdb** [comment]
How will you select which configuration yml file to use?

e.g. if I have a long lived active branch which is based on a commit from a year ago, with master also diverging significantly, should the coverage report be based on the `.codecov.yml` that is:
1. on the current master,
2. on master, at the branch point a year ago, or
3. at the tip of the branch?

IMO it only the last option makes sense.  That is what developers using DVCS expect.

If you choose 3, then the `branches` block in each of these sections of the `yml` doesnt make much sense.

I'm not keen on branch configuration being placed into a global file.

Any long lived branch should have a modified version of the `.codecov.yml`, with adjusted targets, etc.

--
Another thought ... and I'm not advocating this:

The coverage target project percentage, path fixer, and the path ignore list, could be obtained from an existing coverage config file like Python's [`.coveragerc`](http://coverage.readthedocs.org/en/latest/config.html#syntax) existing in the repo.

**Comment by stevepeak** [comment]
@jayvdb thank you for the awesome feedback! 

The current concept is to get the `.codecov.yml` from the specific commit being tested (`3` from your list). In the case that there is no yml file default configurations would be used. Default configuration is not fully established, but would simply be comment and statuses enabled.

The `.travis.yml` file has a branches specification and IMO I would not like to adjust the `.codecov.yml` when making new branches.

Because Codecov supports every language we need to still keep fixpaths and ignore files accessible to all customers. Fixpaths is slowely being depreciated as the system is learning how to fix them automatically. Ignore files is very straight forward. Furthermore I may inclined to add #83 as well.

Thanks!

**Comment by jayvdb** [comment]
Ok, assuming 3., what should happen in the following circumstance:
1. master has `status: branches: master` (i.e. master only)
2. a Pull Request has removed `status: branches: master`

Will the pull request's branch configuration be used, overriding the master/tip configuration?

**Comment by stevepeak** [comment]
@jayvdb Yes, the pull request's tip would be used. The idea is to use the current commit's `.codecov.yml` file at the time of being tested.

An issues I see here is: if one changes the `.codecov.yml` file so that a pull request would pass coverage (because a value changed to `status: project: 0`) as a way to "game" the system and allow their pr to be approved. If this is an issue them perhaps always using the head of default branch is best, therefore ignoring all other changes to `.codecov.yml`. Furthermore, ignoring introductions of this configuration until it has been checked in on the default branch.

Thoughts?

**Comment by jayvdb** [comment]
I would hope that code reviewers notice changes to `status: project:` and similar in the PR, and evaluate the PR's codecov notification accordingly.

I am more concerned with a repo declaring in `.codecov.yml` that they only want codecov coverage reports/notifications for master (i.e. `status: branches: master`), and a PR being able to override that.  There isnt a way to remove a specific branch or commit from codecov, so the owners of the repo have no way to remove the PR's data from codecov.io if it was unwanted.
This is only a 'conceptual' concern for my part - I personally would always want codecov data & notifications for any branch, as I don't see a lot of benefit in having per branch configuration, except that branches should always increase the percentage of coverage obtained.
But if you're intending to offer per-branch configuration stored in the repo, you need to figure out how branch configuration is determined when `.codecov.yml` differs from `master` to a PR.

One mechanism to help resolve some of these issues is to classify a 'PR' as foreign configuration (not written by the repo committers), and treat its `.codecov.yml` as less reliable and explicitly ignore (with build fail notifications) a PR's `.codecov.yml` if it attempts to alter any `branches:` configuration or workflow related configuration such as `notify:` and `comment:`.

**Comment by stevepeak** [comment]
New updated posted on https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a

**Comment by stevepeak** [comment]
All set :+1: more information on the exact specification will be well documented in Codecov when released. Thanks!
