### ISSUE TITLE
Download coverage data

### ISSUE THREAD

**Issue by jayvdb** [codecov/support#106]
Firstly, it would be useful if the web UI exposed that the raw coverage data is available.
Your API is wonderful, allowing users to extract raw coverage data, but it isnt exposed in the web UI as a feature.  A "Download" link in the Features submenu would help people find this.  IMO, the API should be mentioned as feature on https://codecov.io/#features .

The other problem is your API only exposes the coverage data as `Codecov JSON`.  Is there a tool available to covert that JSON format to other formats supported by other tools (e.g. gcov)?

If you store the original coverage data sent, in whatever format was sent the server (e.g. gcov), it would be nice if that original raw data was made available via the API and web UI.

Primarily the reason for requesting this is philosophical.  We push data into your SaaS, but can not quite get it out.  You only provide a very nice JSON format for the data via a clean and simple API. ;-)
But the fact that the *original* coverage data cant be retrieved means the project using your SaaS can't obtain a copy of their historical data to switch to a different provider - it is a vendor lock in. (Granted, it is a very small vendor lock-in, and I have argued for using codecov primarily because codecov has a much lower vendor lock-in than its competitors   https://phabricator.wikimedia.org/T101807#1355749 and https://phabricator.wikimedia.org/T74863 )

Given the 'SaaSS is bad' / 'vendor lock-in' issue continues to be raised, it seems like it might be profitable for codecov.io to better expose its existing data download capabilities, and provide better data download facilities where possible to demonstrate that the business model isnt vendor lock-in model.  Obviously high volume mass downloads of the coverage data would violate the TOS, but that is a different problem which codecov.io already need to manage.

Finally, a little nit on: https://codecov.io/api , the trailing `e` looks incorrect.
```
GET https://codecov.io/api/:service/:username/:repo/:filee
```
should be
```
GET https://codecov.io/api/:service/:username/:repo/:file
```

**Comment by stevepeak** [comment]
@jayvdb first off thank you for taking the time to express your feedback and ideas here.

> Web UI exposed that the raw coverage data is available

This is coming in our next UI along with a log of actions taken per commit by Codecov. So you can:
1. Download the raw uploads (with no Codecov adjustment)
2. Download a detailed log on what and when actions occurred (status posted, comment updated, etc)

> API only exposes the coverage data as Codecov JSON

This is a neat concept. However, I do not see a use case of having Codecov generate different outputs. But someone could create their own `codecov.json to gcov` pretty simply.

> Vendor lockin

Our next major release has the opportunity to download the raw uploads. Vendor-lockin should not be an issue with Codecov shortly.

> Spelling error

Thank you! Adjusted for next deploy
