### ISSUE TITLE
coverage report is for unrelated diff

### ISSUE THREAD

**Issue by kmike** [codecov/support#107]
Here: https://github.com/scrapy/w3lib/pull/37 the coverage diff is shown for another pull request.

**Comment by stevepeak** [comment]
Which pull request was that commit supposed to be on?

**Comment by stevepeak** [comment]
- The Codecov comment says "as of" `e3f46cd` ([here](https://github.com/scrapy/w3lib/commit/e3f46cd4ee85c3b83dceaad0fcb14f751c49bb35)) 
- which is a merge commit: `Merge da213a3 into 3440a41`. 
- `da213a3` is the latest commit in scrapy/w3lib#37

Right?

**Comment by kmike** [comment]
Hm, it works fine now. Yesterday it was displaying coverage for a diff from https://github.com/scrapy/w3lib/pull/36 (https://codecov.io/github/scrapy/w3lib/commit/806299233b4d4c4147e81c99c69dabf94dcaf0ed).

**Comment by stevepeak** [comment]
Odd... I don't see `106194b` or `80629923` in the logs posting a comments. Oh well :)

**Comment by kmike** [comment]
Well, maybe it was me and a late night :) I'll be taking screenshots next time; sorry for noise.

**Comment by stevepeak** [comment]
No worries my friend!
