### ISSUE TITLE
codecov.exe : File not found - '*.gcno'

### ISSUE THREAD

**Issue by Netshroud** [codecov/support#108]
Hi,

I'm trying to add codecov to SteamRE/SteamKit, but I've hit a brick wall with the error

`
codecov.exe : File not found - '*.gcno'
`

It doesn't appear that `.gcno` files are being created by OpenCover, or even that they should be.

OpenCover generates XML, codecov uploads this XML, and it still complains about `.gcno` and fails the build.

Here's my AppVeyor build script: https://github.com/SteamRE/SteamKit/blob/codecov/appveyor.yml

Here's an example build: https://ci.appveyor.com/project/SteamRE/steamkit/build/job/xww8h42g0txfrjn0

What's going on here?

**Comment by stevepeak** [comment]
This error looks like a warning since the report do upload successfully, [as seen here](https://codecov.io/github/SteamRE/SteamKit?ref=dcd1baaf4ad500cbc77069d260b44de74d8b0a35)

You can disable `gcov` by: `codecov -f "SteamKit2-code-coverage.xml" -X gcov`

Thank you :+1:

**Comment by Netshroud** [comment]
Thanks Steve, that did the trick.
