### ISSUE TITLE
Incremental coverage

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#11]
> Continue from #5 

Support for incremental coverage on the entire Pull Request. 
1. Add metrics into PR Comment
2. Add to Commit Status. Require an entire patch incremental coverage minimum.

**Comment by doismellburning** [comment]
Yes please!

**Comment by joaopimentel** [comment]
As I've mentioned through support emails, we really need this feature.

On top of checking how the lines changed actually change the coverage, there could also be an option to simply fail a check if the PR gets the coverage below the target branch's coverage. In this case, this check would pass even if new lines are not covered, as long as total coverage increases (say, adding more coverage on previously uncovered code than new uncovered code).
Given that the PR comment already displays the coverage change/diff between the PR and the target branch, the change value can be used for this quick check, even though I admit it might not be that interesting to have.
It should be simpler, even if not as cool as patch coverage :wink:

**Comment by stevepeak** [comment]
@joaopimentel there will be two implementations of this. A Patch Coverage Status ([already complete](https://github.com/codecov/support/wiki/Patch-Coverage-Status)) and a Pull Request Coverage Status (this issue). Just to be clear :) Thanks!

**Comment by stevepeak** [comment]
## Deploying soon
- **Commit** expresses the incremental coverage within the single commit
- **Patch** expresses the incremental coverage in the entire pull request
- **Project** expresses the coverage of the entire project
