### ISSUE TITLE
UI (key binding) "jump to next (partial/miss) line" like coverage.py's HTML output

### ISSUE THREAD

**Issue by glyph** [codecov/support#111]
When you generate a coverage report via `coverage html` in Python, one of the features of the report is that you can hit <kbd>j</kbd> or <kbd>k</kbd> to go to the next or previous hunk.  Every time I look at a coverage diff in codecov, this is what I want to do: just show me what I didn't cover, so I can get back into my editor and get to fixing it.  Right now, what I do is I pull up the DOM inspector and search the source for `<tr class="line-added miss">` or `<tr class="line-added partial">` and then do `$0.scrollIntoViewIfNeeded()` to scan the page, but it would be a lot nicer if I could just hit those keyboard shortcuts (or a button, I'll click a button if I have to) to see the uncovered portions of my code.

**Comment by stevepeak** [comment]
I look forward to this! I'll add it to our upcoming large UI changes. Thank you!

> Working hard to get this done by end of year.

**Comment by stevepeak** [comment]
Awesome!

----

<img width="1157" alt="screen shot 2016-04-23 at 4 21 10 pm" src="https://cloud.githubusercontent.com/assets/2041757/14763800/854bdf3a-096f-11e6-982c-c97d06635982.png">

**Comment by glyph** [comment]
Thanks!
