### ISSUE TITLE
[Kotlin] Extra lines

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#113]
Kotlin may include extra coverage data that is beyond the EOF of the file.

**Comment by jkcclemens** [comment]
It would be nice if the lines that are beyond the EOF aren't counted towards coverage, but if they could still be viewed in the API, that would be awesome. It's possible to cover these lines by looking at the bytecode, but I've been using the API to see the lines that need covering.

**Comment by stevepeak** [comment]
Fixed in upcoming major release. :+1:
