### ISSUE TITLE
Python module level comments counted as uncovered

### ISSUE THREAD

**Issue by mblayman** [codecov/support#119]
Hi, thanks for making codecov! I'm enjoying the service so far.

I have a project that has 100% coverage locally, but the codecov report indicates that I have two lines uncovered. The two uncovered lines are Python code comments at the module level. I would hope those would be covered when the module was imported.

Here is the file for reference: https://codecov.io/github/mblayman/tappy/tap/plugins/_pytest.py?ref=9179ea630565e4e6a9a7d5d9f403518e480e43c0

Thanks!

**Comment by stevepeak** [comment]
Hey @mblayman that is wild! 

Looks like the [raw upload](https://codecov.s3.amazonaws.com/repos/4CFAB936590B87F1A00B97A0A7F18129/uploads/upload:243911:9179ea630565e4e6a9a7d5d9f403518e480e43c0:184.10:2965:1447817746.36.txt) has the following data:


```
<class branch-rate="0" complexity="0" filename=".tox/coverage/lib/python2.7/site-packages/pytest.py" line-rate="0.75" name="pytest.py">
    <methods/>
    <lines>
        <line hits="1" number="2"/>
        <line hits="1" number="5"/>
        <line hits="1" number="14"/>
        <line hits="0" number="16"/>
        <line hits="0" number="17"/>
        <line hits="1" number="21"/>
        <line hits="1" number="25"/>
        <line hits="1" number="27"/>
    </lines>
</class>
```

The file `pytest.py` is being fixed to `_pytest.py`. I'll look into patching and deploying shortly. Thank you for the feedback :+1:

**Comment by mblayman** [comment]
Awesome. Thank you for the speedy response.

**Comment by stevepeak** [comment]
Deployed :+1: let me know if you see any issues with this. Thanks!

**Comment by mblayman** [comment]
I pushed another build tonight and it correctly report the coverage I expected. Thanks, Steve.

**Comment by mblayman** [comment]
Hi @stevepeak, I noticed in the last week or two that this weird behavior has slipped back into the tappy coverage reports. Travis shows 100% coverage at https://travis-ci.org/mblayman/tappy/jobs/118767035 and Codecov shows 99.66% coverage at https://codecov.io/github/mblayman/tappy?ref=c45ff0c80c709010ea7c46b38ef80a8ff12f8f37.

The lines that are "uncovered" are module level comment lines (https://codecov.io/github/mblayman/tappy/tap%2Fplugins/_pytest.py?ref=c45ff0c80c709010ea7c46b38ef80a8ff12f8f37).

**Comment by stevepeak** [comment]
Hey @mblayman very strange...but I did find the issue.

This file is included in the report
```
<class branch-rate="0" complexity="0" filename=".tox/coverage/lib/python2.7/site-packages/pytest.py" line-rate="0.75" name="pytest.py">
	<methods/>
	<lines>
		<line hits="1" number="2"/>
		<line hits="1" number="5"/>
		<line hits="1" number="14"/>
		<line hits="0" number="16"/>
		<line hits="0" number="17"/>
		<line hits="1" number="21"/>
		<line hits="1" number="25"/>
		<line hits="1" number="27"/>
	</lines>
</class>
```

And the path `.tox/coverage/lib/python2.7/site-packages/pytest.py` is being fixed to `.tox/coverage/lib/python2.7/site-packages/tap/plugins/_pytest.py` which is wrong. I'll need to patch our path fixer and get back to you shortly.

Thank you for bringing this to my attention!
