### ISSUE TITLE
Return reports for merge commits head

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#122]
When only the merge commit exists in Codecov: browser overlay does not work because the commit being searched does not exist in Codecov. Need to return reports for the merge commit in this case.

**Comment by blueyed** [comment]
Is there a workaround?
It seems to affect all PRs, doesn't it?

**Comment by stevepeak** [comment]
You can override the commit sha being uploaded for the time being. This is fixed in our next major release.

```
bash <(curl -s https://codecov.io/bash) -C "commit-sha"
```
> You'll need to detect the merge commit and change the commit via `-C`

**Comment by stevepeak** [comment]
We are detecting the merge commit during upload! Hurray :) Coming out soon
