### ISSUE TITLE
add code cov statistics independent to branch created

### ISSUE THREAD

**Issue by henrykironde** [codecov/support#124]
If a branch(branch-example) is created, i.e from projectA(master), then branch-example should be able to have independent codecov automatically generated and linked to that specific branch.

**Comment by jayvdb** [comment]
Hi @henrykironde, I am not the maintainer .. I am just a fellow user ...

If I understand correctly, I believe this is already possible.

e.g.

https://codecov.io/github/henrykironde/deletedret?branch=henryf

If you push more commits to that branch, causing more or less coverage, that page should reflect the changes to that branch only.

My apologies if I have not understood your problem correctly.

**Comment by henrykironde** [comment]
Hi @jayvdb I guess that's right, since I have not configured the remote for this branch. If anything changes, I will reopen the issue. Thanks
