### ISSUE TITLE
PR comment is not updated when a PR changes 

### ISSUE THREAD

**Issue by ccarpita** [codecov/support#126]
For example, adding a commit, or force-pushing rebased changes does not seem to update the comment.  I would expect the original comment to be removed, and a new comment added to the end of the thread.   The result seems to be that the comment may contain non up-to-date info, and that the Coverage Diff link leads to an empty page.

Version: not sure how to pull this from the UI, but this is the enterprise image from mid-December 2015

**Comment by stevepeak** [comment]
Hey @ccarpita, the current policy for pull request comments are:

```
Create new if never posted before and update existing comments when new data is presented to Codecov
```

For your example above I have a couple questions. Did the rebase trigger a new CI build and upload reports to Codecov, therefore, updating the comment?

### Future version

We are introducing a much more flexible commenting system, the new `codecov.yml` will introduce a [comment behavior](https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a#file-codecov-yml-L87-L90). In addition, all comments will be deleted upon rebase.

**Comment by ccarpita** [comment]
Yes, a new CI build was triggered, but the comment did not update in this particular case even though the data should have changed due to new uncovered lines.  I upgraded codecov to the most recent version, and also I'm going to be together a test, so will close this issue for now until I can verifiably reproduce.  Thanks for explaining the behahvior!
