### ISSUE TITLE
setting up new project does not work

### ISSUE THREAD

**Issue by xh3b4sd** [codecov/support#130]
I just tried out https://codecov.io/ because I like the idea. Unfortunately after waiting some time nothing happened. The badge for my project was still grey and stated "unknown". There were really no information on the website. No commit/branch/PR information. I tried to dig into the problem and run codecov locally. Then I go this. It was also strange to need to provide my private token when running locally, because in my `.travis.yml` the command was simply `codecov` as suggested from your documentations. 

```
$ codecov --token <token>

      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \__,_|\___|\___\___/ \_/
                                    v1.6.3

==> Detecting CI provider
  -> Got branch from git/hg
  -> Got sha from git/hg
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find <path> -type f -name '*.gcno'  -exec gcov -pb  {} +)
==> Collecting reports
    + <path>/src/github.com/go-kit/kit/coverage.bash bytes=858
==> Appending adjustments (http://bit.ly/1O4eBpt)
  --> Found 22701 adjustments
Error: 'ascii' codec can't encode character u'\xa9' in position 832268: ordinal not in range(128)

Tip: See all example repositories: https://github.com/codecov?query=example
Support channels:
  Email:   hello@codecov.io
  IRC:     #codecov
  Gitter:  https://gitter.im/codecov/support
  Twitter: @codecov
```

So what to do? How to get a project properly running? How to get more information when things are going wrong?

**Comment by stevepeak** [comment]
Hey @xh3b4sd thank you for the feedback!

Seems that the uploader is having an issue with parsing. Can you do me a favor an try the bash uploader:

```
bash <(curl -s https://codecov.io/bash) -t <token>
```

This should upload your reports, at which time please let me know so I can review the content of them to fix the Python uploader. Or you can send the `coverage.bash` report directly to my email at steve@codecov.io

Thank you.

**Comment by xh3b4sd** [comment]
With the bash uploader I get this. Still don't understand what happens. The coverage seems to be 0.0%, what is just wrong. I guess codecov cannot read the file structure of my project or something. 

```
$ bash <(curl -s https://codecov.io/bash) -t <token>

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                5ca7b8c


(url) https://codecov.io
(root) .
==> Trying gcov (disable via -X gcov)
  -> Running gcov
==> Searching for coverage reports
**> Python coverage not found
==> Detecting git/mercurial file structure
==> Reading reports
  + ./.workspace/src/github.com/go-kit/kit/coverage.bash bytes=856
==> Appending adjustments (http://bit.ly/1O4eBpt)
  --> Found 22688 adjustments
(query) package=bash-5ca7b8c&branch=master&commit=ebe74aa0ae3cd6b744ca4cfde093c0a81ab98012&build=&build_url=&slug=&service=&pr=&job=&token=<token>
==> Uploading reports
    Pinging Codecov
    Uploading to S3

Reports queued to http://codecov.io/github/xh3b4sd/anna?ref=ebe74aa0ae3cd6b744ca4cfde093c0a81ab98012
```

**Comment by stevepeak** [comment]
Looks like there is no reports properly collected. The `coverage.bash` is not a report and will be ignored by collections shortly.

Checkout https://github.com/codecov/example-go for how to get coverage working with Go.

Let me know how that **GO**es ;) Thanks

**Comment by stevepeak** [comment]
The non-ascii character issue is being fixed today. Thank you!

**Comment by xh3b4sd** [comment]
Thanks for coming back. Based on https://travis-ci.org/xh3b4sd/anna/builds/109351450 the bug is not fixed. 
```
 'ascii' codec can't encode character u'\xa9' in position 835878: ordinal not in range(128)
```

I was able to fix the coverage problem of my project. Still cannot make `codecov` work with the python version. Trying the bash uploader.

**Comment by xh3b4sd** [comment]
Ok, the bash uploader is working. Good enough for me. Thanks for your help.
