### ISSUE TITLE
Not updating PR comments on Appveyor completion

### ISSUE THREAD

**Issue by gappleto97** [codecov/support#134]
I'm running two CIs. One from Appveyor, and one from Travis-CI.

When Travis-CI completes, CodeCov does not update its comment or check status, even though the coverage changes with additional reports.

Can you please address this?

Example: https://github.com/gappleto97/Senior-Project/pull/88

**Comment by stevepeak** [comment]
Hey @gappleto97 Codecov, by design, will wait for all CI providers to finish before submitting coverage comments and notifications. This is because some coverage data may depend on, for example AppVeyor, and therefore be inaccurate when posted.

We have ideas on how to improve this process by submitting the comment ahead of all finished builds, but making note that not all data may be available yet. But this is not currently supported. More on this will be published soon.

For now you will see the comment posted upon all CI solutions completing.

**Comment by gappleto97** [comment]
I think you're missing my point here. It updates when Travis is complete, but never updates when Appveyor is complete.

**Comment by stevepeak** [comment]
Hey @gappleto97 do you have a project slug and commit sha I can look up logs in our system for. Perhaps I can find a concurrency issue that is causing this. Thank you!

**Comment by gappleto97** [comment]
The pull request I put in the submission will work. It's since been closed, but it should have the information you need.

**Comment by dopplershift** [comment]
I'm seeing this problem: My code coverage updates when Travis finishes, but then doesn't update further when AppVeyor finishes. This causes my coverage from the PR to decrease due to the lack of windows coverage.

**Comment by gappleto97** [comment]
@stevepeak Seems like others are seeing this issue as well. Can you comment?

**Comment by dopplershift** [comment]
I can even go to https://codecov.io/github/Unidata/siphon?ref=22f53b647250444d56ce94d1c814541046bbbc01 and see an updated, unified coverage count of 95.06%. This isn't reported to GitHub (or at least it doesn't show up in the PR)--it still shows 94.75%.

**Comment by stevepeak** [comment]
Hey @gappleto97 @dopplershift sorry for my delay here. I did apply a fix to our detection for AppVeyor on April 7th. Have you seen this improve?

**Comment by dopplershift** [comment]
I need to re-enable the total coverage checkd, but now that I know you guys have had a look, I'll be sure to check on our next PR.

**Comment by stevepeak** [comment]
@dopplershift thanks! Let me know how it goes. We have a major release Sunday that enhances this process too

**Comment by stevepeak** [comment]
We fixed an issue concerning detection of AppVeyor. Thank you!
