### ISSUE TITLE
decreased coverage is interpreted as failed PR integration

### ISSUE THREAD

**Issue by xh3b4sd** [codecov/support#135]
Hello, I really like the codecov pull request integration. Nevertheless I noticed that the decreased coverage within a PR is expected to be a failed integration state. When using Github's protected branch feature, the PR cannot be merged then. So I need to find out how to at least reach the coverage I have in master branch. This is not always possible though. Are there some ideas around that? What is the suggested behavior here?

**Comment by stevepeak** [comment]
Hey @xh3b4sd I'm not quite sure the context of your question here. Is this the **codecov/project** or the **codecov/patch** status?

I'm happy to discuss how this works and what upcoming changes are due in our new [`codecov.yml`](https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a)

**Comment by xh3b4sd** [comment]
So I created a test PR to reproduce the issue. Unfortunately the problem is now not reproducible anymore. I don't know to what of your projects the issue is related to. That is why I just opened an issue here in the support repo. 

My problem what I have seen was that I had a PR where I have several integrations like Travis-CI and Codecov. The Travis-CI checks passed but the Codecov checks did not pass. So I thought that failing state of the codecov integration check was caused by a decreased coverage in my PR. So my assumption was that this will cause repositories that use Github's branch protection feature to not be able to merge. In my test PR I decreased the coverage on purpose to validate my assumption. Now it is not reproducible and the coverage decreased but the check passed. So all is good. 

Sorry for the noise. This issue can be closed I guess.

**Comment by xh3b4sd** [comment]
Its me again. I saw this issue again in https://github.com/xh3b4sd/anna/pull/62. For this commit the codecov check failed: https://github.com/xh3b4sd/anna/commit/07725161469a063ccc295f20e09a785c6e287b6c. This is the corresponding codecov check: https://codecov.io/github/xh3b4sd/anna?ref=07725161469a063ccc295f20e09a785c6e287b6c. This are the two corresponding travis checks: https://travis-ci.org/xh3b4sd/anna/builds/110526779, https://travis-ci.org/xh3b4sd/anna/builds/110526774. 

So it looks like all is good, all tests pass. It is simply that the coverage decreases. 

This is how it looks like in my PR right now. 

---

<img width="790" alt="screen shot 2016-02-20 at 02 23 16" src="https://cloud.githubusercontent.com/assets/552769/13193477/4b223818-d779-11e5-88da-d068915f2ad4.png">

---

The good thing is that the branch protection indeed does not require the codecov check to pass as I originally thought. Anyway I really don't understand what is going on here. 

I am not sure if this helps but I attach the coverage report here. I don't know why the coverage report changes from run to run even if the tests are the same, but anyway, here you go: [coverage.txt](https://github.com/codecov/support/files/138938/coverage.txt).

**Comment by xh3b4sd** [comment]
FYI it looks like this behavior is not related to a specific commit. I added a commit where only something in the `README.md` changed and the codecov check was still failed. So I doubt it is a race condition. Now I added a new commit that caused an overall increase of the coverage and now the codecov check passes.

**Comment by stevepeak** [comment]
I reckon the report on master may have an issue. I noticed that https://github.com/xh3b4sd/anna/pull/62 is not merged, and has a successful codecov status. Do you have a new example of one that is failing still?

**Comment by xh3b4sd** [comment]
I have the impression that this always happens in case you push a PR the first time and it decreases the coverage of the project. Can you confirm that?

**Comment by stevepeak** [comment]
> I have the impression that this always happens in case you push a PR the first time and it decreases the coverage of the project.

This is not the case. We have a process of checking the changes to see if coverage is expected to be reduced. We have a way to offset the coverage when expected. This will set a successful status even through coverage decreases. More here: https://github.com/codecov/support/wiki/Commit-Coverage-Status

Is this the answer you were seeking?

**Comment by xh3b4sd** [comment]
Interesting. I turned of the project coverage failure when decreasing. Lets see what happens. 

FYI the wiki page states `Features -> Github Status`. There is only a `Commit Status` tab.

**Comment by skirpichev** [comment]
> We have a process of checking the changes to see if coverage is expected to be reduced.

You have a minimum coverage ratio value to control incremental coverage (codecov/patch).

But I see no similar variable to control possible decrease for a project as a whole.  I think, this can be useful sometimes, [here](https://github.com/skirpichev/omg/pull/261) an example.  For the first commit - failure in codecov/project, but for second - green status.  In both cases the codecov/patch check shows that coverage not affected. (Perhaps, code flows are slightly different due to hash randomization and so on.)

**Comment by stevepeak** [comment]
Hey @skirpichev we are introducing thresholds in our next release Sunday. The `codecov.yml` will introduce this: https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a#file-codecov-yml-L86

**Comment by stevepeak** [comment]
I'm closing this issue because of the new `codecov.yml` implementation. Thank you!

**Comment by skirpichev** [comment]
Nothing is working yet, unfortunately (my builds stuck in "Waiting for status to be reported" state).  I hope this will be fixed soon.

BTW, about naming, why not ".codecov.yml", like ".travis.yml"?

**Comment by stevepeak** [comment]
@skirpichev you may use `.codecov.yml` as well.

Fixing up these issues now. Thank you for your patience.

**Comment by stevepeak** [comment]
@skirpichev  PS what commit was this for, I would like to review what happened

**Comment by skirpichev** [comment]
> you may use .codecov.yml as well.

Oh, good news.

> PS what commit was this for, I would like to review what happened

For example, latest merges in these prs:
https://github.com/skirpichev/omg/pull/208
https://github.com/skirpichev/omg/pull/227
(Travis jobs were finished about 3 hours ago or more)

**Comment by stevepeak** [comment]
@skirpichev thanks! Looking into it. +10 points for your patience 👍

**Comment by stevepeak** [comment]
@skirpichev can you rebuild these commits? I believe I've fixed the statuses. Thanks

**Comment by skirpichev** [comment]
Ok.  Travis jobs were restarted.

**Comment by skirpichev** [comment]
skirpichev/omg#227 finished 1/2 hour ago, still "Waiting for status to be reported".

**Comment by AxelNennker** [comment]
I just did a first-time commit to a project and changed just the readme.md.
https://github.com/openid/AppAuth-Android/pull/191 
Codecov now shows a failed test: https://codecov.io/gh/openid/AppAuth-Android/compare/29329dce430edebdc80e9635895358e20971f286...621e09303e9d8a07b0ca0c8699c69368168ba1f8

Why?
