### ISSUE TITLE
Duplicated repos for personal fork in the repo list

### ISSUE THREAD

**Issue by vasily-v-ryabov** [codecov/support#136]
When I'm looking at [my personal account projects on Codecov.io](https://codecov.io/github/vasily-v-ryabov), there are several repos with the same name: `vasily-v-ryabov/pywinauto`.

The latest coverage report looks incorrect ([no info shown](https://codecov.io/github/vasily-v-ryabov/pywinauto?ref=master) now, but it shows 96% in the list of repos).

When I press "Add new repository to Codecov" it also shows 3 identical repo names.

P.S. Sometimes I delete my fork `vasily-v-ryabov/pywinauto` and fork it from `pywinauto/pywinauto` again. That might be one of the reasons. But I expect it to work in such cases as for one repo.

![codecov_list_of_repos](https://cloud.githubusercontent.com/assets/7419086/13247016/2739fea2-da28-11e5-8cb8-ac30ec350149.png)

**Comment by stevepeak** [comment]
This issue has been fixed. Thank you!
