### ISSUE TITLE
Disable generating code coverage for CocoaPods frameworks on Bitrise

### ISSUE THREAD

**Issue by adamszeremetarstit** [codecov/support#137]
Hello,
I'm using Bitrise CI together with Codecov step to gather covegate data for my iOS project in Swift.
Codecov steps now gathers coverage data from dependencies like FBSDKShareKit but this wasn't the case some time ago. Any ideas how I can remove that to gather only my app data?

`(url) https://codecov.io
(root) .
--> token set from env
==> Bitrise CI detected.
  -> Swift in /Users/vagrant/Library/Developer/Xcode/DerivedData
    + Building reports for MyApp app
    + Building reports for Alamofire framework
    + Building reports for Bolts framework
    + Building reports for FBSDKCoreKit framework
warning: 1 functions have mismatched data. 
    + Building reports for FBSDKLoginKit framework
warning: 1 functions have mismatched data. 
    + Building reports for FBSDKShareKit framework
warning: 2 functions have mismatched data. `

**Comment by stevepeak** [comment]
> RE https://github.com/codecov/support/issues/140

Working on this now. Thank you!
