### ISSUE TITLE
0% Code coverage in iOS project

### ISSUE THREAD

**Issue by rad3ks** [codecov/support#143]
Hi

We're having problem with code coverage reports in our project. We use [Bitrise.io codecov step](https://github.com/bitrise-io/steps-codecov) (which uses your bash script) and it reports 0% code coverage. I'm not sure how to validate my project settings, but Xcode shows correct code coverage.

I enabled Code Coverage for both targets, I also set following envs:
```
GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES 
GCC_GENERATE_TEST_COVERAGE_FILES=YES
```
I'm running xcodebuild test with `-enableCodeCoverage YES`. I also set `Build active architecture only = YES` for all configurations and targets.

What information do you need to help me solve the problem? I can share logs,, but project is generally under NDA and repo is private, just let me know if there are some specific parts that may be specifically interesting, so don't need to remove app name from every line.

This is Objective-C project.

**Comment by stevepeak** [comment]
Hey @rad3ks, the best course of action to help out is: can you produce reports locally? 

Can you run the same test command then run from your project directory
```
find . -type f -name '*.gcno' -exec gcov -pb {} +
```

Let me know what the output is here. Thanks!

**Comment by rad3ks** [comment]
Thanks for your answer.

I'm running following command:
```
xcodebuild "-workspace" "./Project.xcworkspace" "-scheme" "Project" "build" "test" "-destination" "platform=iOS Simulator,name=iPhone 6,OS=latest" "GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES" "GCC_GENERATE_TEST_COVERAGE_FILES=YES" | xcpretty "--color" "--report" "html" "--output" "./Project_report.html"
```

Then the command you asked me for
```
find . -type f -name '*.gcno' -exec gcov -pb {} +
```

Output:
```
File '/Users/Me/Documents/Developer/directory/project/Project/Classes/Controllers/FirstViewController.h'
Lines executed:0.00% of 8
No branches
No calls
/Users/Me/Documents/Developer/directory/project/Project/Classes/Controllers/FirstViewController.h:creating '#Users#Me#Documents#Developer#directory#project#Project#Classes#Controllers#FirstViewController.h.gcov'

File '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h'
Lines executed:0.00% of 4
No branches
No calls
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGGeometry.h:creating '#Applications#Xcode.app#Contents#Developer#Platforms#iPhoneSimulator.platform#Developer#SDKs#iPhoneSimulator9.2.sdk#System#Library#Frameworks#CoreGraphics.framework#Headers#CGGeometry.h.gcov'

File '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGeometry.h'
Lines executed:0.00% of 3
No branches
No calls
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIGeometry.h:creating '#Applications#Xcode.app#Contents#Developer#Platforms#iPhoneSimulator.platform#Developer#SDKs#iPhoneSimulator9.2.sdk#System#Library#Frameworks#UIKit.framework#Headers#UIGeometry.h.gcov'

File '/Users/Me/Documents/Developer/directory/project/Project/Classes/Controllers/FirstViewController.m'
Lines executed:0.00% of 73
Branches executed:0.00% of 28
Taken at least once:0.00% of 28
No calls
/Users/Me/Documents/Developer/directory/project/Project/Classes/Controllers/FirstViewController.m:creating '#Users#Me#Documents#Developer#directory#project#Project#Classes#Controllers#FirstViewController.m.gcov'

File '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIViewController.h'
Lines executed:0.00% of 1
No branches
No calls
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIViewController.h:creating '#Applications#Xcode.app#Contents#Developer#Platforms#iPhoneSimulator.platform#Developer#SDKs#iPhoneSimulator9.2.sdk#System#Library#Frameworks#UIKit.framework#Headers#UIViewController.h.gcov'

File '/Users/Me/Documents/Developer/directory/project/Project/Classes/Controllers/SecondViewController.m'
Lines executed:0.00% of 11
No branches
No calls
/Users/Me/Documents/Developer/directory/project/Project/Classes/Controllers/SecondViewController.m:creating '#Users#Me#Documents#Developer#directory#project#Project#Classes#Controllers#SecondViewController.m.gcov'

File '/Users/Me/Documents/Developer/directory/project/Project/Classes/Utilities/SomeObject.m'
Lines executed:0.00% of 15
Branches executed:0.00% of 8
Taken at least once:0.00% of 8
No calls
/Users/Me/Documents/Developer/directory/project/Project/Classes/Utilities/SomeObject.m:creating '#Users#Me#Documents#Developer#directory#project#Project#Classes#Utilities#SomeObject.m.gcov'

File '/Users/Me/Documents/Developer/directory/project/Project/Classes/Utilities/SomeObject.h'
Lines executed:0.00% of 1
No branches
No calls
/Users/Me/Documents/Developer/directory/project/Project/Classes/Utilities/SomeObject.h:creating '#Users#Me#Documents#Developer#directory#project#Project#Classes#Utilities#SomeObject.h.gcov'

Function checksums do not match: 1859542279 != 3589996918 (in -[ThirdViewControllerSpec spec]).
Invalid .gcda File!
File '/Users/Me/Documents/Developer/directory/project/Pods/Parse/Parse/Internal/User/Coder/File/PFUserFileCodingLogic.m'
Lines executed:0.00% of 26
Branches executed:0.00% of 14
Taken at least once:0.00% of 14
No calls
/Users/Me/Documents/Developer/directory/project/Pods/Parse/Parse/Internal/User/Coder/File/PFUserFileCodingLogic.m:creating '#Users#Me#Documents#Developer#directory#project#Pods#Parse#Parse#Internal#User#Coder#File#PFUserFileCodingLogic.m.gcov'
```

It's the same result I get from bitrise. I hope that will help.

**Comment by rad3ks** [comment]
@stevepeak do you have any clue what's going on? I ran out of ideas, maybe I can give more information?

**Comment by stevepeak** [comment]
@rad3ks the output from gcov does express the `Lines executed:0.00%`. 

Can you try a build using `xctool` instead of `xcodebuild`. As seen here: https://github.com/codecov/example-objc/blob/master/.travis.yml#L3

Thanks!

**Comment by rad3ks** [comment]
@stevepeak after using `xctool` I have same output as with `xcodebuild`. Is there anything more I can check?

**Comment by stevepeak** [comment]
@rad3ks Not sure... sorry I'm not more helpful. I don't have much experience with xcode testing.

@bgerstle These kind of issues arise from time to time. Can you help me understand how to debug this. Thank you :+1:

**Comment by rad3ks** [comment]
@stevepeak @bgerstle guys, any luck with our issue? I think the script changed some time ago, as the reports worked nicely and then just stopped working. Maybe I can get some older version of the script to test?

**Comment by stevepeak** [comment]
@rad3ks sorry, but no updates yet. I personally have no experience with testing Xcode, I'm relying on the community to help resolve issues like this.

I'm curious have you used Slather before? https://github.com/SlatherOrg/slather
Codecov and Slather execute coverage in a similar way. I wonder if you can get that tool to work?

**Comment by bgerstle** [comment]
xctool won't generate coverage for Xcode 7 and up. Have you tried using debug configuration?

**Comment by bgerstle** [comment]
Also, double check that you're passing the `-enableCodeCoverage YES` arguments. I don't see it in the xcodebuild snippet you wrote above.

**Comment by bgerstle** [comment]
Lastly, have you looked at the example-swift project's setup? Comparing the build setting and CI steps side by side could highlight something that's breaking coverage.

**Comment by rad3ks** [comment]
Thanks for response! I started from the top, with Slather and it reports code coverage correctly. As I said before
>  I think the script changed some time ago, as the reports worked nicely and then just stopped working.

Are you sure this is not an issue?

**Comment by stevepeak** [comment]
@rad3ks do you have a date/time of when it was once working? I can check the change log. Thanks!

@bgerstle 👍 Thank you!

**Comment by stevepeak** [comment]
cc @aniahellwing

**Comment by rad3ks** [comment]
It looks like the last time it worked was 25th Feb.

**Comment by stevepeak** [comment]
> https://github.com/codecov/codecov-bash/compare/f9b8a8d...1f1226e line 119 to 134

The llvm-cov command did not change. The detection of projects did but I don't believe that is the issue here.

**Comment by coreyfloyd** [comment]
@rad3ks Hmm, we actually had to set `GCC_GENERATE_TEST_COVERAGE_FILES ==  NO` @bgerstle made these changes to our project a couple months ago:

```
GCC_GENERATE_TEST_COVERAGE_FILES = NO;
CLANG_ENABLE_CODE_COVERAGE = YES;
```
https://github.com/wikimedia/wikipedia-ios/pull/616/files#diff-97711e3aa5168bc96e6ca5daa633f9ac

Also, this is different since we are using fastlane, but we stopped passing arguments and relied on the scheme/build setting. Even though you are using Bitrise, the concept should be the same:

https://github.com/wikimedia/wikipedia-ios/pull/123/files#diff-56c5021ef06ac6cea807ae53269b6f4f

@rad3ks if that doesn't help feel free to pull down our source and inspect all the other settings. Everything is pretty much in the build settings, fastfile and .travis.yaml

**Comment by bgerstle** [comment]
sorry @coreyfloyd, but I think you've been misled by the diff. I did make that change, but I set coverage enabled to `YES` _for the Debug configuration_. Here's a screenshot of the current settings on the `develop` branch:

![image](https://cloud.githubusercontent.com/assets/444217/14469503/f62b055c-00b2-11e6-8a0c-c3eef4f07073.png)

I'm not familiar with Bitrise, but fastlane's `scan` tool is essentially a wrapper for xcodebuild.  You can see the command it generates in [the build output](https://travis-ci.org/wikimedia/wikipedia-ios/builds/116807314#L394) (broken into multiple lines for readability):

```
set -o pipefail && env NSUnbufferedIO=YES \
 xcodebuild \
 -workspace 'Wikipedia.xcworkspace' \
 -scheme 'Wikipedia' \ 
 -configuration 'Debug' \
 -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.2' \
 -enableCodeCoverage YES \
 TRAVIS=true \
 build test \
| tee '/Users/travis/build/wikimedia/wikipedia-ios/build/Wikipedia-Wikipedia.log' \
| xcpretty -f `xcpretty-travis-formatter` --no-utf
```

**Comment by coreyfloyd** [comment]
@bgerstle my bad - thanks for correcting.

**Comment by bgerstle** [comment]
not at all. things like this make me really wish Apple build tools were less opaque 🔮  hopefully Swift & Swift PM will help nudge things in the right direction

**Comment by rad3ks** [comment]
Issue fixed. Don't pass following flags
```
GCC_GENERATE_TEST_COVERAGE_FILES = YES;
CLANG_ENABLE_CODE_COVERAGE = YES;
```
when building with `xcodebuild`. Set them in build settings for debug and test configurations (only) and pass `-enableCodeCoverage YES` to `xcodebuild`.

Thanks for your help 🎉
