### ISSUE TITLE
Exclude lines in C++

### ISSUE THREAD

**Issue by ntadej** [codecov/support#144]
I'm using lcov locally to generate reports. There I can specify which lines to ignore using `LCOV_EXCL_LINE`. It would be nice to support this so I don't need to add additional comments as described in #83.

**Comment by stevepeak** [comment]
Hey @ntadej can you provide me with an extract of your code that expresses this comment inline with code. Example

```python
exclude this line # LCOV_EXCL_LINE
# LCOV_EXCL_START
line 
line 
# LCOV_EXCL_STOP
```

----

I presume the lcov output does not respect these comments?

**Comment by ntadej** [comment]
Your default bash uploader uses gcov directly which does not respect these comments. If I generate report with lcov and the just upload it with your uploader, it works as expected. The repo in question is [vlc-qt/vlc-qt](https://github.com/vlc-qt/vlc-qt).

Probably it would be good to include lcov in the docs.

**Comment by stevepeak** [comment]
Ok, just to be clear: the issue is with `gcov` not respecting the comments correct?

Would these comments only be in `.cpp` and `.h` files?

**Comment by ntadej** [comment]
Yes, `gcov` does not support these comments out of the box, it is a `lcov` feature. Comments would be in `.cpp`, `.h` and other files that can contain C/C++ source (`.cxx`, `.c`, `.hpp`, ...).

My idea was, that your service may want to support these comments so no additional effort is necessary. (as in my case, using `lcov` to process coverage results)

**Comment by stevepeak** [comment]
Great! Consider it done. Checkout the commit above

**Comment by springmeyer** [comment]
> Would these comments only be in .cpp and .h files?

Also .hpp files /cc @stevepeak.

**Comment by springmeyer** [comment]
Hrm, I went to create a PR to fix the above omission of `.hpp` but I'm no longer seeing any support for `LCOV_EXCL` in https://github.com/codecov/codecov-bash. @stevepeak - am I missing something? Did the `LCOV_EXCL` ignore support get dropped for some reason?

**Comment by stevepeak** [comment]
@springmeyer it's [right here](https://github.com/codecov/codecov-bash/blob/6ec4aac0c3a677658565ec4ce1be3ac04d99eae8/codecov#L955) Is this not working?

**Comment by stevepeak** [comment]
On second look... it's not catching the `LCOV_EXCL` just `LCOV_EXCL_START` and `LCOV_EXCL_STOP` for example. I'll patch that up.

**Comment by springmeyer** [comment]
@stevepeak what I'm seeing is that:

1) I'm missing coverage on a `}` which is odd. Lazily I tried to ignore this with `LCOV_EXCL_LINE` but it appears not to work. Am I doing something wrong that you see https://codecov.io/gh/mapbox/vt-shaver-cpp/src/f2e204929ae84fd83df142ded219d47820f69073/src/filters.cpp#L18

2) Also this usage of `LCOV_EXCL_START` and `LCOV_EXCL_STOP` also appear not to be working. Perhaps user error on my part? https://codecov.io/gh/mapbox/vt-shaver-cpp/src/f2e204929ae84fd83df142ded219d47820f69073/src/filters.cpp#L114...119

**Comment by ntadej** [comment]
It worked for my project a month ago when it was last built.

**Comment by stevepeak** [comment]
How are you uploading reports? I'm not seeing fixes included in the raw uploads...

**Comment by ntadej** [comment]
Sorry, I forgot that I manually run lcov on travis.

**Comment by stevepeak** [comment]
@ntadej ... one sec. I think I figured it out.

**Comment by springmeyer** [comment]
@stevepeak - are you thinking that https://github.com/codecov/codecov-bash/commit/228bb79ce618bd871603b7432a6406bfb9987396 will fix things? I'm not seeing things working yet on my end.

**Comment by stevepeak** [comment]
@springmeyer sorry about that, made a mistake with matching the paths. Fixing now. Thank you!

**Comment by springmeyer** [comment]
@stevepeak still not working. I tested again by:

  - commiting to https://github.com/mapbox/vtinfo/commit/c2d02c1c4b6013b8fadd02755aa71f187e1a551e
   - This project uses:
      - LCOV_EXCL_START/LCOV_EXCL_STOP: https://github.com/mapbox/vtinfo/blob/master/src/vtinfo.cpp#L91-L93
      - LCOV_EXCL_LINE: https://github.com/mapbox/vtinfo/blob/master/src/vtinfo.cpp#L112
 - The build still shows these lines as uncovered when they should be ignored: https://codecov.io/gh/mapbox/vtinfo/src/c2d02c1c4b6013b8fadd02755aa71f187e1a551e/src/vtinfo.cpp#L92

Am I missing something about how this functionality should work? I would presume that these lines would be marked green as they are ignored.

**Comment by stevepeak** [comment]
@springmeyer oh' bash... my regexp was not escaped properly. Fixed tested and deploying asap.

**Comment by springmeyer** [comment]
@stevepeak I tried testing yet again, and it still is not working: https://codecov.io/gh/mapbox/vtinfo/src/281ba3599f90db327a59ed28597f4e8c3252c334/src/vtinfo.cpp#L92.

**Comment by darioizzo** [comment]
We have the same issue on our project with the use of  LCOV_EXCL_START / LCOV_EXCL_STOP.
The first command seems to be parsed correctly, but then the second command is ignored.
This causes anything after the first LCOV_EXCL_START to be ignored!

https://codecov.io/gh/esa/pagmo2/src/master/include/pagmo/algorithms/ipopt.hpp#L262

is this going to be fixed?

**Comment by stevepeak** [comment]
@darioizzo sending a patch today. Thank you for your patience.

**Comment by springmeyer** [comment]
@stevepeak - thanks for taking a look at getting this working. Can you provide a link here to your commit or PR when you fix this? I presume it will show up at https://github.com/codecov/codecov-bash/commits/master?

**Comment by stevepeak** [comment]
The fix was server side - the code of which is private (planned to open source soon 👍 )
Just deployed 🚀

**Comment by springmeyer** [comment]
Thanks @stevepeak

**Comment by darioizzo** [comment]
Yeps, looks like this is fixed now! Thanks a mil @stevepeak

**Comment by zeux** [comment]
@stevepeak Can you explain a bit more how LCOV_EXCL_LINE support is implemented? I tried uploading a .gcov file that has LCOV_EXCL_LINE comments (https://github.com/zeux/pugixml/commit/02e6d7d605bd6b6b4637fdea08029ef822c0ab0c) but that did not work. Running this sed script over the source file itself in a later commit in this branch did mark these lines as covered in the report. Is it the case that LCOV_EXCL_LINE is only processed in the source file, not the submitted .gcov file?

**Comment by zeux** [comment]
My temporary workaround to this is:
> sed -e "s/#####\(.*\)\(\/\/ unreachable.*\)/    1\1\2/" -i pugixml.cpp.gcov

Needless to say it's not ideal :) My goal basically is to keep the source using `// unreachable` comment (as it seems more readable to people unfamiliar with lcov), and somehow tell codecov that this line should not be counted towards code coverage results.

**Comment by stevepeak** [comment]
> Can you explain a bit more how LCOV_EXCL_LINE support is implemented?

Codecov will search for this line in the code here: https://github.com/codecov/codecov-bash/blob/master/codecov#L1309-L1331
I do not know why lcov does not automatically ignore these lines... But Codecov must review the report to find the lines on it's own.

I welcome all feedback! 👍
