### ISSUE TITLE
Can I use the codecov logo as-is on public GitHubs?

### ISSUE THREAD

**Issue by richelbilderbeek** [codecov/support#145]
I'd enjoy putting codecov logo's on my GitHubs, as I enjoy codecov. Is this okay yes or no?

**Comment by stevepeak** [comment]
Sure, you can use the logo in your GitHub readme. We don't have documented guidelines of usage yet, but it's the same as other company's: unaltered and be nice :)

Thanks!

**Comment by richelbilderbeek** [comment]
Awesome, that fits my needs :-)
