### ISSUE TITLE
Summary shows coverage, but repo doesn't

### ISSUE THREAD

**Issue by kitsonk** [codecov/support#146]
I have been having a bit of a problem with posting my coverage and having it show up properly.

My [Travis CI](https://travis-ci.org/kitsonk/widgets/builds/116329358#L351) is posting the coverage information:

```
configuration:  { service: 'travis',
  commit: '37ac29ebfe205d7255184220f1fb2caf0ac07ca4',
  build: '9.1',
  branch: 'master',
  job: '116329359',
  pull_request: 'false',
  slug: 'kitsonk/widgets',
  package: 'node' }
```

And my [overview page](https://codecov.io/github/kitsonk/) is showing the coverage information:

<img width="1303" alt="kitsonk" src="https://cloud.githubusercontent.com/assets/1282577/13810599/9705dbce-eb68-11e5-9970-6e5dce045a79.png">

But when you [drill down](https://codecov.io/github/kitsonk/widgets), it claims there is no coverage information:

<img width="897" alt="kitsonk_widgets_master" src="https://cloud.githubusercontent.com/assets/1282577/13810644/cce0c2d6-eb68-11e5-8601-b6381d53fa69.png">

**Comment by stevepeak** [comment]
Hey @kitsonk not sure what happened here... but reports are now showing up. I think the original report, somehow, did not create an entry in the branches table.

**Comment by stevepeak** [comment]
Our next major release touches on this process. Thank you!
