### ISSUE TITLE
Coverage reports are not being shown in codecov.io site

### ISSUE THREAD

**Issue by crisfervil** [codecov/support#147]
Hi,

For some reason, the coverage reports are not being shown.

Reviewing the travis-ci log, everything looks fine, and a log line says that the reports have been successfully uploaded, but when I enter into codecov.io no coverage info appears.

```
=============================== Coverage summary ===============================
Statements   : 83.67% ( 492/588 )
Branches     : 71.68% ( 162/226 )
Functions    : 77.37% ( 106/137 )
Lines        : 83.62% ( 485/580 )
================================================================================
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v1.0.1
==> Detecting CI Provider
    Travis CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ service: 'travis',
  commit: '444608894ac8cf355466aa0a68a0782191899513',
  build: '20.1',
  branch: 'master',
  job: '115989440',
  pr: 'false',
  slug: 'crisfervil/Jigsaw',
  root: '/home/travis/build/crisfervil/Jigsaw',
  package: 'node-v1.0.1' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/travis/build/crisfervil/Jigsaw -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + /home/travis/build/crisfervil/Jigsaw/coverage/lcov.info
    + /home/travis/build/crisfervil/Jigsaw/coverage/coverage.json
==> Uploading reports
    Success!
    View report at: http://codecov.io/github/crisfervil/Jigsaw?ref=444608894ac8cf355466aa0a68a0782191899513
```

This is what I see in codecov.io site:

![capture](https://cloud.githubusercontent.com/assets/7902357/13812548/bab4300a-eb74-11e5-80c0-741fc6e26e86.PNG)

It shows 0% coverage and a message saying File path not found

Full travis-ci log: https://travis-ci.org/crisfervil/Jigsaw/builds/115989439

My .travis.yml file:
```
language: node_js
node_js:
  - "stable"
install:
  - npm install -g codecov
  - npm install
before_script: npm run build
script:
  - npm run cover  
  - codecov
```

And this is what *cover* and *build* scripts are doing in package.json

```
  "scripts": {
    "build": "typings install && tsc -p .",
    "test": "mocha --recursive",
    "cover": "istanbul cover ./node_modules/mocha/bin/_mocha -- --recursive",
    "doc": "jsdoc core/ -r -d doc"
  },
```

The codecov commit:
https://codecov.io/github/crisfervil/Jigsaw/commit/cbdc0c467890fbfa927da49a19e3935af12bf32a

This is the project in github
https://github.com/crisfervil/Jigsaw/

Any ideas?

Thanks!!

**Comment by stevepeak** [comment]
Hey @crisfervil looks the issue has to do with the file being named `core/builder.ts` but the report expressing this file as `core/builder.js`. I have not see this issue before, so thank you for bringing this to my attention.

I'll need to review some ideas on how to fix this. I likely need to make some backend patches. I'll ping you when I have this fixed.

Thanks!

**Comment by crisfervil** [comment]
Cool! Thanks!

**Comment by stevepeak** [comment]
Hey @crisfervil I'll be deploying a patch today. Thanks for your patience :+1:

**Comment by stevepeak** [comment]
Deployed :+1:

**Comment by crisfervil** [comment]
It works like a charm! Thanks a mill!
