### ISSUE TITLE
No coverage for Python 3 project; worked well with Python 2.

### ISSUE THREAD

**Issue by pavoljuhas** [codecov/support#149]
After converting one of my packages from Python 2 to Python 3 codecov cannot map coverage data to the source tree.  The codecov page shows 0% coverage together with "File path not found" message: https://codecov.io/github/pavoljuhas/diffpy.utils?branch=test-codecov-py35.  The package is built and tested on travis as follows:

1. install miniconda and build an anaconda package diffpy.utils for the project
1. use `conda install` to deploy the package to the standard site-packages directory
1. execute `coverage run ...` from an empty directory `rundir`
1. run `codecov` from the same directory

This procedure works fine with Python 2.7, but fails with 3.5.  I have added a `codecov --dump` call to the end of the travis script and here are the produced outputs:

- Python 2.7: [travis job](https://travis-ci.org/pavoljuhas/diffpy.utils/builds/116987096) --> [codecov report](https://codecov.io/github/pavoljuhas/diffpy.utils?ref=d41061c3697509529b2ea9f11ee97447f7051132)
- Python 3.5: [travis job](https://travis-ci.org/pavoljuhas/diffpy.utils/builds/116995839) --> [codecov report](https://codecov.io/github/pavoljuhas/diffpy.utils/commit/d5be30a793d0080d5df59759e32149ce8738fb36)

The python source tree of my package starts from the src folder.  As far as I can tell the difference between codecov dumps from 2.7 and 3.5 is that with Python 2.7 the installed package is in `.../site-packages/diffpy.utils-1.2.1.post6-py2.7.egg/` directory, but for 3.5 it is directly in the `.../site-packages/` directory.

Can you fix the codecov webpage so it can map sources correctly for the installation paths in Python 3.5?

I tried to use various path mappings with the "Path Fixer" option, but none of them worked.  It would be helpful to show a few examples of the original paths from coverage.xml together with their fixed form.

**Comment by stevepeak** [comment]
Looks like there is an issue mapping back files. For example a file was detected named `src/diffpy/utils/__init__.py` but the coverage report states: `/home/travis/mc/envs/testenv/lib/python3.5/site-packages/diffpy/utils/__init__.py`

This is something I'll need to fix server side. I'll was planning a deploy shortly and will include this. Ping you in a moment.

**Comment by stevepeak** [comment]
Deployed :+1: Let me know if that fixes it up on your next upload. Thanks!

**Comment by pavoljuhas** [comment]
Works great :+1:   Thank you for a quick fix!
