### ISSUE TITLE
Builds failing with 'coverage not measured fully' but tests passed

### ISSUE THREAD

**Issue by markstory** [codecov/support#150]
I'm a maintainer of cakephp/cakephp and we've recently started using codecov. A large number of our codecov [builds fail](https://github.com/cakephp/cakephp/pull/8584). However, the [relevant travis-ci job passes](https://travis-ci.org/cakephp/cakephp/jobs/120787447). I'm not able to figure out from the codecov interface why the codecov commit status check is failing. Have we [misconfigured codecov](https://github.com/cakephp/cakephp/blob/master/.travis.yml#L82-L84) or done something else dumb?

**Comment by stevepeak** [comment]
Hey @markstory I for that pull request Travis did fail, which is required to pass in order to properly calculate coverage metrics.

Codecov will check your CI builds to make sure they are successful in order to compare metrics. We do this because if a CI build fails coverage metics may not have been fully collected and there for drops in coverage are not valid.

**Comment by ADmad** [comment]
@stevepeak So codecov checks status of the whole build instead of just the particular job which generates clover.xml and sends it to codcov.io?

**Comment by stevepeak** [comment]
@ADmad we have patterns to check against so basically all CI providers. Scrutinizer would be skipped for example.

**Comment by ADmad** [comment]
By "whole build" I was referring to the travis ci build :)  

Would be nice if the checking of CI build status was configurable. One can ensure in a job CI itself that a codecov coverage check is triggered only if the job completes successfully, thereby avoiding the need to check status of the whole CI build.

**Comment by stevepeak** [comment]
@ADmad configuration is on its way: https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a#file-codecov-yml-L7 (scheduled to release Sunday)

**Comment by markstory** [comment]
Thanks @stevepeak that sounds like the source of our issue.
