### ISSUE TITLE
How to make file path fix?

### ISSUE THREAD

**Issue by kshmir** [codecov/support#152]
We have an application which contains a subproject, admin, it reports it's files but not it's base path in the repo... so we made the following fixes:

/src::api/src
/app::admin/admin/app
/config::admin/admin/config
/spec::admin/admin/spec

But within admin/admin/app/helpers/application_helper.rb also gets replaced with admin/admin... basically breaking those links.

Is there any documentation for a more advanced path fix?

Thanks!

**Comment by stevepeak** [comment]
Hey @kshmir documentation is coming soon, we are introducing new features soon for this as well: https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a#file-codecov-yml-L135

Meanwhile, I can help you. Can you please provide me with the project owner/repo name so I can review your project. You can ping me on https://gitter.im/codecov/support

Thanks!

**Comment by stevepeak** [comment]
More documentation will be provided in out next major release! Thank you
