### ISSUE TITLE
Exclude files from beeing gathered

### ISSUE THREAD

**Issue by Flamefire** [codecov/support#153]
In our repo we have some `*.lst` files that contain our data (not coverage related).

Using the codecov.io/bash script these files are misinterpreted as coverage files and probably confuse analyser later.

It would be good, if one can specify files or folders or patterns, that are not excluded from the search (Below `Searching for coverage reports`)

**Comment by stevepeak** [comment]
Hey @Flamefire You can ignore reports in the UI. See here http://cl.ly/1W0n1g1b3t3W

Sunday we release a major release and the `codecov.yml` will be the place to add ignore paths: https://gist.github.com/stevepeak/53bee7b2c326b24a9b4a#file-codecov-yml-L132

**Comment by Flamefire** [comment]
Does this work for **coverage** files? I though this feature is for ignoring **source** files?
I'm not completely sure how the bash script works internally, but it seems to aggregate all information from the coverage files and uploads this as coverage data. The server can then ignore source files listed in the coverage data. But can it really ignore coverage data from a specific coverage (not source) file?

**Comment by stevepeak** [comment]
@Flamefire the short answer is "yes", but to best help you I'll need to know the context of what you are looking to "ignore". Can you elaborate? I can also review your project: whats the owner/repo?

**Comment by Flamefire** [comment]
Ok, the project is here: https://github.com/Return-To-The-Roots/s25client
An example travis build here (before my change that uses own file gathering): https://travis-ci.org/Return-To-The-Roots/s25client/jobs/122539596
At this stage, `--coverage` was used, but nothing was executed. Take a look at the bottom:
> Reading reports
  + /home/travis/build/Return-To-The-Roots/s25client/RTTR/LSTS/GAME/Babylonier/bab_icon.lst bytes=19184
  + /home/travis/build/Return-To-The-Roots/s25client/RTTR/LSTS/GAME/Babylonier/bab_z.lst bytes=235176
  + /home/travis/build/Return-To-The-Roots/s25client/RTTR/LSTS/GAME/Babylonier/wbab_z.lst bytes=237231

These are actual data files, not coverage files. This seems to have resulted in the following (completely off) coverage: https://codecov.io/github/Return-To-The-Roots/s25client/src/main.cpp?ref=b002e27f4b5ad0862b150d0e26b17ca721621f82

Even more fatal: It seems it merges the data with PRs: https://codecov.io/github/Return-To-The-Roots/s25client/src/main.cpp?ref=6818bcd58ab1d7101974a77c0dc3d78829c82d17
This is from a PR, that only passes the correct gcov files to the bash script (https://travis-ci.org/Return-To-The-Roots/s25client/jobs/123752209) Note that the main.cpp got coverage data, even though it was not executed. What was executed is `test/main.cpp` (which is correctly reported)

**Comment by stevepeak** [comment]
Ok, your certainly an edge case :) 

Do you know the path of the "real" coverage report that you would like? Because you can specify it manually which skips the searching process. That will fix it.

`bash <(curl -s https://codecov.io/bash) -f path/to/coverage.txt`

**Comment by Flamefire** [comment]
Well, I think this might be pretty common (that one of the file patterns matches repo files)

Problem is (AFAIK) that there is no real coverage report. Only a collection of gcda files which need to be processed by gcov to produce gcov files which can then be fed into `-f`. This is what I'm currently doing...
Suggestion: If the bash script invokes gcov, it can limit the pattern to `*.gcov`. So one can use the bash script without manual work.

**Comment by stevepeak** [comment]
**The goal** is plug-n-play. Whatever we can do to make this work in "without manual work" is best. But this comes with some challenges, no doubt.

>  no real coverage report

False-positives do happen from time to time. We add many patterns to the "ignored" list here: https://github.com/codecov/codecov-bash/blob/73569726020635ca0a2ac2ae8ee7266025500e83/codecov#L610-L673

>  If the bash script invokes gcov, it can limit the pattern to *.gcov

We have some customers with gcov and pyhton/js/go etc. So this is unfortunately not an option.

-----

Thoughts on this concept:

`bash <(curl -s https://codecov.io/bash) -f !*.lst`

**Comment by Flamefire** [comment]
An ability to add/remove files or globs would probably be the best option. Could be even more verbose:

`--exclude_cov *.lst *.foo --include_cov *.bar build/subdir/myfile.txt`

Besides this: Can you check what happened with those lst files and why they were mapped to the main.cpp? I think it should be possible to detect, if they are valid or false positives. Also that it shows coverage that is not reported in subsequent reports is a bug (might legally be due to regressions)
