### ISSUE TITLE
When uploading C# code space in directory or file name will change to + symbol

### ISSUE THREAD

**Issue by brian-johnson-spot** [codecov/support#156]
url for code will have + sign as well, and then I cannot see files or directories unless I update url to change + to %20.  
Ex. 
If I have file in this location src/dir path/file
the url will look like this server/bitbucket_server/REPO/src/dir+path/file
and not return anything. I have to update to server/bitbucket_server/REPO/src/dir%20path/file for it to work. Is there  any fix for this?

**Comment by stevepeak** [comment]
Hey @brian-johnson-spot, thanks for expressing this issue. We have had challenges escaping paths properly, and it seems this has slipped by. In the release tomorrow we have new techniques to properly encode paths that fixes this issue.

**Comment by stevepeak** [comment]
Fixed a while ago. thanks
