### ISSUE TITLE
Validating codecov.yml via curl doesn't work

### ISSUE THREAD

**Issue by dougnukem** [codecov/support#159]
The docs say you can validate the `codecov.yml` via:
```
curl -X POST -d @codecov.yml https://codecov.io/validate
```

But it looks like I'm getting a `404` or an HTML response.

```

<html lang="en">
<!DOCTYPE html>
<head>
...
```

**Comment by Flamefire** [comment]
Note: I'd also suggest a simple form where you can submit the `codecov.yml`. If you are working in windows it is not that easy to use curl and if that service already understands POST requests, than adding a form to the homepage is a 4-liner.

**Comment by zbeekman** [comment]
I get 405 method not allowed

**Comment by stevepeak** [comment]
Fixed! 

```
cat codecov.yml | curl --data-binary @- https://codecov.io/validate
```
> Note the slight change on reading the file.

Thanks!
