### ISSUE TITLE
Language: Clojure

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#16]
> Re @emiln

- [ ] get an example coverage output
- [ ] show examples on how to create reports on [codecov/example-clojure](https://github.com/codecov/example-clojure)

**Comment by emiln** [comment]
Hi, @stevepeak. I'm a bit busy due to moving to a new house, but I expect I'll find some time for this within a week or two.

**Comment by emiln** [comment]
I think the most mature test coverage tool for Clojure is [cloverage](https://github.com/lshift/cloverage) at the moment. Coverage is currently written as HTML reports, which is not exactly ideal, but the structure seems very predictable if nothing else.

* [Here](https://www.refheap.com/101809) is an example of a report for a full project spanning a few namespaces.
* [Here](https://www.refheap.com/101810) is the report for one of the specific namespaces mentioned above.

Do you think this is workable?

**Comment by stevepeak** [comment]
Yea, I think this is very doable. I would wish for a more streamline way, but it look like this may be the best solution so far.

- Where are the html files stored once created?
- Can you send me an example directory with files I can use for testing.

I'll be creating a Python package to parse the html on our production server. If you would like to help hack it with me that would be great, let me know if that works for you.

Thanks!

**Comment by stevepeak** [comment]
https://github.com/codecov/example-clojure
