### ISSUE TITLE
codecov doesn't post PR comments anymore

### ISSUE THREAD

**Issue by pitrou** [codecov/support#163]
Due to the "new version" of codecov.io, I added a `codecov.yml` to our project but this seems to instruct codecov not to post a PR comment anymore: see https://github.com/numba/numba/pull/1856

**Comment by burabure** [comment]
Not receiving comments here also

**Comment by stevepeak** [comment]
Hey @pitrou  and @burabure I'm taking requests per project now for issues. I'm happy to review your project so to make sure everything lines up. We had some migration issues that have been most resolved, thank you for your patience.

@burabure, @pitrou what is your owner/repo#pr?

**Comment by burabure** [comment]
Hey @stevepeak we're having issues with not receiving comments and getting "no report found to compare against"
https://codecov.io/gh/springboardretail/springboard-retail/pull/2356 

![image](https://cloud.githubusercontent.com/assets/3132298/14943093/784767e0-0fa6-11e6-9012-f37db936fb93.png)

**Comment by stevepeak** [comment]
@burabure please see #173 with many details on this. Thank you

**Comment by burabure** [comment]
thanks @stevepeak, sending a coverage report for the main branch and then sending cov for the PR solved it for us

![image](https://cloud.githubusercontent.com/assets/3132298/14945285/518ceaa6-0fe4-11e6-8462-4b0c2f234f00.png)

![image](https://cloud.githubusercontent.com/assets/3132298/14945288/5f0847de-0fe4-11e6-9281-7fc4732261d7.png)

Awesome product, awesome support! <3

**Comment by pitrou** [comment]
@stevepeak, things seem to be working for us now. Thank you!

**Comment by stevepeak** [comment]
@pitrou 🙇 👍 Awesome :smi

**Comment by stevepeak** [comment]
@burabure B-E-A-UTIFUL 👍

**Comment by Flamefire** [comment]
@stevepeak I might have still an issue: The PR comment is not updated: https://github.com/Return-To-The-Roots/s25client/pull/451 `Powered by Codecov. Last updated by 46afab9...aa31231`, but latest commit is `7a25064` But all checks passed.

**Comment by stevepeak** [comment]
@Flamefire this is odd.... shouldn't the compare be `0e21183b...7a25064`?

Was this PR rebased? I'm having a tough time understanding why this instance occurred.

**Comment by Flamefire** [comment]
Yes I think the PR was rebased. However I think this is quite common: Create a PR, find an issue e.g. through CI that something is missing on a platform, create another PR that adds functionality required by first PR and rebase first to master after 2nd got merged. Or rebase to current master after PR was sitting for a while and created merge conflicts... So rebases should be handled, and I don't see the problem. codecov runs fine (all checks show up as passed) but comment is simply not updated.

**Comment by stevepeak** [comment]
@Flamefire for sure, just looking for some context on why this occurred. I'll continue to debug. Thanks

**Comment by alessandrojp** [comment]
I had the issue today.
In my case it was because I did `git push -f` in my pull request overriding the last commit reported on codecov. Once you do that, there is no commit any more to be compared and it will show the error `No report found to compare against.`

I fixed it sending a coverage report again as suggested here https://github.com/codecov/support/issues/163#issuecomment-216084472
