### ISSUE TITLE
"Commit was abandonded due to rebase..." has the wrong link

### ISSUE THREAD

**Issue by samuelcolvin** [codecov/support#170]
We're getting a message

> Commit was abandonded due to rebase, force push, or unable to be found in GitHub. Please check that your bot (link) user has authroization to ....

I'm assuming that will sort itself eventually as we've already discussed it, however the link on the word **bot** is wrong and just goes to a 404 page.

it currently points to `https://codecov.io/account/gh/<org>/settings/yaml` when I think it should be `https://codecov.io/account/gh/<org>/yaml`, eg. `settings/` should be removed.

**Comment by stevepeak** [comment]
Hey @samuelcolvin thanks for pointing this out. I've fixed the link :)

We are adding a better warning UI shortly. Thanks!
