### ISSUE TITLE
List of files and their coverage in the PR comment

### ISSUE THREAD

**Issue by tleunen** [codecov/support#171]
I'd like to have a quick way to see the coverage of the new/modified files in the PR, without going to codecov. Is it something already possible, or something that you'd be interested in adding to codecov?

I'm thinking of a simple table like that as a basic example:

file | coverage | change
--- | --- | ---
path/to/my/file.js | 33% &rarr; 33% | 0%
path/to/my/second/file.js | 50% &rarr; 100% | +100%

Each path will be a link to the file on codecov to see the coverage detail on that specific file. And of course, if there are more than X files, maybe just display the first more relevant (sorted by files with the least coverage?) and then just add a quick link to see everything on codecov.

**Comment by stevepeak** [comment]
This is a really cool ideas 👍 I had another customer ask about this a day ago too.

We will keep this discussion going and plan to implement something like this in the near future. Thank you @tleunen for the suggestion.

**Comment by adiroiban** [comment]
some feedback. I don't care about files with 100% coverage and I prefer to only see `troubled` files in the report. - no news is good news :)

**Comment by stevepeak** [comment]
Deploying soon! Instructions how to enable will proceed the deploy 👍

**Comment by tleunen** [comment]
Yay! Thanks @stevepeak

**Comment by stevepeak** [comment]
Hey @tleunen You can enable this via:

```
comment:
  layout: "header, diff, tree"
```
> Note just the addition of `tree` works. The default limit to the number of items is 10 items sorted by least covered. You can change the amount by `tree:5` or `tree:20` for example.
