### ISSUE TITLE
changed coverage in v4

### ISSUE THREAD

**Issue by 304NotModified** [codecov/support#175]
With the new version the coverage has been changed. It's not clear to me if this is a feature or a bug.

Before it was ~75%, which is still reflected with a badge: 
![image](https://cloud.githubusercontent.com/assets/5808377/14939272/06c63c74-0f40-11e6-9e74-4e0aba325198.png)
https://codecov.io/github/NLog/NLog/coverage.svg?branch=master

---

But the dashboard shows now 79%. 
![image](https://cloud.githubusercontent.com/assets/5808377/14939275/2afbeb70-0f40-11e6-955b-40539d2d1200.png)
https://codecov.io/gh/NLog/NLog

I like 79% more than 75%, but I guess it's wrong?

**Comment by zbeekman** [comment]
Did you create a codecov.yml file? This happened with our project because unit tests we were not counting towards the coverage started counting again before adding the ignore paths in the project.

**Comment by 304NotModified** [comment]
No. Is that new?

**Comment by zbeekman** [comment]
Yes codecov (a week or two ago) migrated all settings to a file you keep in the repo. If you set ignore files from the web settings previously, all these will be included in coverage reports until you re-enable the ignores from the codecov.yml file. There is a tool to import some of your old settings into the new file on the codecov website.

**Comment by stevepeak** [comment]
Hey @304NotModified is this issue closed? Thank you!

**Comment by 304NotModified** [comment]
No, I didn't ignored files before or now. I don't get it why the numbers are different.

**Comment by samuelcolvin** [comment]
Hi @stevepeak I'm having the same (or simpilar) problem

https://codecov.io/gh/samuelcolvin/harrier has coverage of 89%

but the badge https://codecov.io/github/samuelcolvin/harrier/coverage.svg?branch=master is showing (right now) 83%.

The coverage increased from 83% in a65471 16hrs ago.

```
samuel:~ || date
Mon  2 May 13:56:45 BST 2016
samuel:~ || curl -i https://codecov.io/github/samuelcolvin/harrier/coverage.svg
HTTP/1.1 200 OK
Connection: keep-alive
Date: Mon, 02 May 2016 12:56:48 GMT
Content-Type: image/svg+xml
Content-Length: 865
X-Coverage: 83
Pragma: no-cache
Content-Disposition: inline; filename="coverage.svg"
Access-Control-Allow-Credentials: true
Cache-Control: no-cache, no-store, must-revalidate, max-age=0
X-Request-Id: a7be5d4e-df55-4ac0-b381-cbeb9708fa2c
Access-Control-Expose-Headers: Content-Type, Cache-Control, Expires, Etag, Last-Modified
Vary: Accept-Encoding
Server: TornadoServer/4.3
Access-Control-Allow-Origin: *
Via: 1.1 vegur


<svg xmlns="http://www.w3.org/2000/svg" width="96" height="20">
    <linearGradient id="b" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1" />
        <stop offset="1" stop-opacity=".1" />
    </linearGradient>
    <mask id="a">
        <rect width="96" height="20" rx="3" fill="#fff" />
    </mask>
    <g mask="url(#a)">
        <path fill="#555" d="M0 0h60v20H0z" />
        <path fill="#ffde00" d="M60 0h36v20H60z" />
        <path fill="url(#b)" d="M0 0h96v20H0z" />
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="30" y="15" fill="#010101" fill-opacity=".3">Codecov</text>
        <text x="30" y="14">Codecov</text>
        <text x="77" y="15" fill="#010101" fill-opacity=".3">83%</text>
        <text x="77" y="14">83%</text>
    </g>
</svg>
samuel:~ || curl https://codecov.io/gh/samuelcolvin/harrier 2>&1 | grep "\.[0-9][0-9]%$"
89.82%
89.82%
```

**Comment by 304NotModified** [comment]
I think is at least wrong if I get two different numbers for the same source (badge vs dashboard)

**Comment by stevepeak** [comment]
There was an issue with caching badges that I have fixed. I presume this issues is resolved. Thank you!

**Comment by 304NotModified** [comment]
I think it was fixed by something else, because it seems fixed a few days before. 

And I was another case, as the badge was correct, but the dashboard not.

Anyway, fixed and thanks!
