### ISSUE TITLE
must always force reload when navigating reports on codecov.io

### ISSUE THREAD

**Issue by burabure** [codecov/support#176]
I have to force reloads in order to see new commits, branches or pulls on the codecov.io repos dashboard. Also when navigating to an already refreshed tab the old data is shown again and I have to force reload again.

already tried the usual cache/cookies cleanup

**Comment by stevepeak** [comment]
Hey @burabure we don't have web-sockets or auto-reloading content yet. But its in the roadmap.

Thank you for being patient and understanding :) We are working our best.

**Comment by burabure** [comment]
I think I wasn't very clear, what I mean is that when I navigate to an url, I get an outdated version, and I have to do a hard reload to get the new contents. Then if I go back to the same url again, it shows the outdated version again, so I have to do a hard reload again.

Does that make sense?, is kinda hard to explain.

**Comment by stevepeak** [comment]
I think I understand. Are you using the backspace/back-in-history? We just changed to pjax and I may need to revisit how the pages are cached in this case.

Thanks!

**Comment by burabure** [comment]
yeah it looks like a cache issue, and yes, going back in history causes this but also just navigating through the UI via the tabs 
![image](https://cloud.githubusercontent.com/assets/3132298/14955453/77941c9e-1050-11e6-8531-91e4262e9c7e.png)
