### ISSUE TITLE
codecov.yml, notifications and public repos

### ISSUE THREAD

**Issue by tusbar** [codecov/support#177]
Now that all settings have been migrated to `codecov.yml` how can I setup – for example – Slack notifications without having the URL public?

**Comment by stevepeak** [comment]
Sure, we have not published our secret variables yet:

1. Generate a Codecov Access token in your account center
2. Run `curl -X POST -d 'value=the-thing-I-want-secret' https://codecov.io/api/encode/gh/owner/repo?access_token=your-token`
1. Get the value at `"encoded": "secret...."`
1. Set in your yaml via `url: "secret...."`

Thank you!

**Comment by tusbar** [comment]
Cool, thanks.
