### ISSUE TITLE
codecov.yml errors should be reported

### ISSUE THREAD

**Issue by pitrou** [codecov/support#178]
Right now it seems codecov.io ignores codecov.yml when it contains errors, falling back to some default set of settings. It would be far more helpful if an erroneous codecov.yml generated an error in the corresponding PR or commit status.

See https://github.com/numba/llvmlite/pull/172 for some experiments of mine.

**Comment by stevepeak** [comment]
@pitrou we are looking into ways at expressing errors to the end users. For we we do have a validation endpoint at:

```
cat codecov.yml | curl --data-binary @- https://codecov.io/validate
```

**Comment by pitrou** [comment]
I'm finding it very hard to debug a codecov.yml file, even when validation returns fine. For examplein the following PR: https://github.com/numba/numba/pull/1863 it seems I'm unable to disable the "codecov/patch" status.

**Comment by stevepeak** [comment]
Hey @pitrou working on a better form of validating and debugging the yml. Meanwhile we are happy to review case-by-case and through our validation endpoint above.

Thanks!
