### ISSUE TITLE
init repo from cli

### ISSUE THREAD

**Issue by yoshuawuyts** [codecov/support#18]
would be neat to have a tool for codecov analogous to https://github.com/finnp/node-travisjs. When creating new modules I don't want to visit a website just to enable test coverage.

**Comment by stevepeak** [comment]
@yoshuawuyts this should already be the case for public repos. I have it set to enable to repo upon the first reports uploaded. Have you seen this not work? Thanks!

**Comment by yoshuawuyts** [comment]
@stevepeak hah, that's even better. Closing (:
