### ISSUE TITLE
Codecov checks are failing incorrectly

### ISSUE THREAD

**Issue by samuelcolvin** [codecov/support#180]
I'm getting 

> codecov/changes — 1 file has unexpected coverage changes not visible in diff. :x: 

On a pull request, clicking details gives "No commit to compare against found." I think this is because the branch was rebased with master and codecov and/or github can't find the right shared parent commit.

This means a PR is showing as failing when it has in fact passed all tests.

The fact that no diff comparison can be made shouldn't cause the PR to show as failing.

**Comment by samuelcolvin** [comment]
In github:

![image](https://cloud.githubusercontent.com/assets/4039449/14981293/09091e4c-1126-11e6-8301-6a5829a440c9.png)

**Comment by 304NotModified** [comment]
Same issue here. This is really delaying our development.

**Comment by stevepeak** [comment]
@304NotModified @samuelcolvin we had an issue saving the changes on a per commit lvl, but thats fixed now. My apologies on that slip-up.

For these commits you can use our `/gh/owner/repo/compare/base...head` endpoint to see these changes. You'll take the status commit as the `head` and the `base` being the parent commit in Codecov that was last reported successfully.

**Comment by VVeremjova** [comment]
I have PR that doesn't have  "No commit to compare against found." It shows changes in files that actually are covered by unit tests, but these changes are showed as fail. it is really confusing.
![screenshot from 2016-05-05 15 50 01](https://cloud.githubusercontent.com/assets/11159420/15044016/84c24152-12da-11e6-9b1a-4aafdc7f9248.png)

**Comment by stevepeak** [comment]
Hey @VVeremjova the changes status was fixed. There is only one remaining issue https://github.com/codecov/support/issues/181#issuecomment-217432573
