### ISSUE TITLE
Incorrect repository and member counts

### ISSUE THREAD

**Issue by jconroy** [codecov/support#184]
Hi @stevepeak !

Nothing urgent - looks like the repository and member counts are incorrect e.g. http://cl.ly/3N1q0o2w2s47

Clearly there are more than 0 repositories and there is at least 1 member.

I've refreshed a few times and had a look around around for similar issue (sorry if its a dupe).

Cheers!

**Comment by jconroy** [comment]
Looks like they started working for me in the last couple of days. I'll leave this open a little while longer until confirmed fixed.

**Comment by xh3b4sd** [comment]
I am kind of plus one for the incorrect member count. See the image below. There are 4 members displayed for my username. Intuitively I would expect one member there, myself. Not sure what this number is supposed to represent. Maybe I am misinterpreting it. Anyway I wanted to provide this feedback here. 

<img width="313" alt="screen shot 2016-05-27 at 23 26 56" src="https://cloud.githubusercontent.com/assets/552769/15621648/98a1ef94-2462-11e6-87c6-c30376a871e0.png">

Note that I am part of 4 organizations. This is the only relation that I can draw in this issue, but it is maybe a false positive.

**Comment by stevepeak** [comment]
This issue was fixed a couple weeks ago. Let me know if the issue is still occurring on your setup. Thanks!

**Comment by xh3b4sd** [comment]
I am seeing still the same picture. What does `4 Members` mean here?

**Comment by stevepeak** [comment]
@xh3b4sd your cache data may have been invalid as it appears to contain old data and has not updated in awhile. I've updated it to reflect more accurate data. Your "members" should be 0.

**Comment by xh3b4sd** [comment]
Right. WFM. Thanks.
