### ISSUE TITLE
Toggling misses lines in a file shows as hit

### ISSUE THREAD

**Issue by eddiemoore** [codecov/support#187]
In the code view in codecov on a line that was not hit, initially it shows as red
![screenshot 2016-05-06 10 23 18](https://cloud.githubusercontent.com/assets/199016/15062660/e489b83c-1374-11e6-8423-60d42e5e34d9.png)
However if you toggle it off and on again it shows that the line has been hit 
![screenshot 2016-05-06 10 23 31](https://cloud.githubusercontent.com/assets/199016/15062666/f64b3d70-1374-11e6-96ec-a5de72d09343.png)

**Comment by max-vogler** [comment]
This is still an issue...

**Comment by stevepeak** [comment]
Hey, this should be fixed up in recent updates. Sorry about that issue friends!
