### ISSUE TITLE
Hidden codecov.yml

### ISSUE THREAD

**Issue by 153957** [codecov/support#189]
Is the name `.codecov.yml` also supported/recognized? I'd prefer to have the config file hidden by default (on systems that hide files with names starting with a dot), just like `.travis.yml`.

**Comment by stevepeak** [comment]
Yes, you can name the file `codecov.yml` or `.codecov.yml` and place it anywhere in your project. As long as your uploading with the `bash` or `python` uploader which detects the location. 👍

**Comment by 153957** [comment]
Thanks

**Comment by simov** [comment]
@stevepeak why the *Node Uploader* does not support this feature?

**Comment by stevepeak** [comment]
@simov I have not yet had the opportunity to update that package yet. Backlogged on support and other pressing issues...
