### ISSUE TITLE
"View all files" broken while in subfolders

### ISSUE THREAD

**Issue by RyanCopley** [codecov/support#19]
If you click the "Prefer to view all files?" in the root of the project then click a file, it works
but if you click it while in a subfolder, then click a file, it doesn't work

C&P'd from gitter

**Comment by zbeekman** [comment]
yes I’m having this issue too… in fact it isn’t working for me anywhere…

Also, I’m uncertain of the intended functionality of this button: is the purpose of this button to view files that you’ve added to the ‘Features’ —> ‘Ignore Files’ list?

**Comment by stevepeak** [comment]
> The feature of gathering content in folders will show up when there are at lease 20 covered files. I'm considering removing this minimum for consistency

The intended feature is to remove the structure of the tree view and show all files in a huge list. Customers have asked for this feature so they may sort their whole project based on missed lines (and the other columns)

I'll work up a fix for this tomorrow. Thank you
