### ISSUE TITLE
Incorrect path for folders with spaces

### ISSUE THREAD

**Issue by adamkaplan** [codecov/support#190]
My project includes a folder called "UI Layer" and when clicking it in the UI, I get "File path not found".

The problem appears to be the hyperlink generation, which turns the folder name into `/UI+Layer` rather than the proper URL-encoded `/UI%20Layer`. Manually changing the URL corrects the issue.

Seen on Codecov Enterprise

(Let's ignore any discussion of the wisdom of spaces in paths – it's been there forever 😄)

**Comment by stevepeak** [comment]
Hey @adamkaplan I believe we have solved this in a recent version. Cool?

**Comment by Stoff81** [comment]
This issue is still present

**Comment by Stoff81** [comment]
I have to ask, why on would spaces be replaced with "+"

**Comment by stevepeak** [comment]
@Stoff81 replacing a space with "+" is for internal use only. The paths in your project should remain with a space character (` `) not a `+` char. Codecov must escape the spaces for navigation reasons.

**Comment by stevepeak** [comment]
This issue was resolved some time ago. I'll close it for now. 

> @Stoff81 I see your Intercom message. Please follow up with me there. Thank you
