### ISSUE TITLE
How to disable comments only in codecov.yml and preserve the statuses?

### ISSUE THREAD

**Issue by simov** [codecov/support#192]
Here is the PR that I'm talking about: https://github.com/request/request/pull/2204 - as you can see I have only `comments: false` set there, but for some reason the statuses are disabled too.

Here is a PR prior adding codecov.yml: https://github.com/request/request/pull/2203 - as you can see I have two codecov statuses at the bottom.

So my question is, how can I disable the comments only, but preserve the statuses?

**Comment by stevepeak** [comment]
Hey @simov  you have the setup properly in https://github.com/request/request/pull/2204

The lack of status is due to the commit being a merge commit (which we are fixing this week) So the commit uploaded was 274d2b440f3b but the actual commit is  3c42cc2.

I should have this deployed in the next day or two.

**Comment by simov** [comment]
Ok, can you ping me up when I can test it again? Probably I should be able to test https://github.com/request/request/pull/2204 with a force push?

**Comment by stevepeak** [comment]
Will do. I'll jump on this today as it slipped my mind this week.

**Comment by 153957** [comment]
I have the reverse problem, I have the `.codecov.yml` with `comments: false` in both master and a branch, but still codecov comments on the PR:
https://github.com/HiSPARC/sapphire/pull/124#issuecomment-218716288

https://github.com/HiSPARC/sapphire/blob/datetime_range/.codecov.yml

**Comment by stevepeak** [comment]
@153957 we had record of the yaml being at `codecov.yml` not `.codecov.yml`. I've updated that location and the next commit will respect the location of the file.

**Comment by simov** [comment]
My https://github.com/request/request/pull/2204 PR seems to have commit statuses (and no commits) :+1: 

@stevepeak is the `.codecov.yml` (hidden) file supported? I actually prefer that.

**Comment by 153957** [comment]
Curious, we never had it at `codecov.yml`, Thanks for the fix.

**Comment by simov** [comment]
I just renamed it to `.codecov.yml` and got the comment again ..

**Comment by 153957** [comment]
See Steve's previous comment, it seems codecov expects the file to no be renamed.

**Comment by stevepeak** [comment]
@153957 `.codecov.yml` is acceptable, it was just a detection issue. I'll be reviewing this process soon to see what the issue was. Thank you!
