### ISSUE TITLE
Codecov is not recognizing my commits anymore

### ISSUE THREAD

**Issue by untitaker** [codecov/support#194]
https://codecov.io/gh/pimutils/vdirsyncer

Newer commits that migrate codecov settings to codecov.yml are not recognized. Therefore the Settings panel on codecov still asks me to migrate my settings to codecov.yml.

I suspect this was because of `status.project = false`, which I removed from master (but those changes weren't picked up either).

**Comment by untitaker** [comment]
The commits appeared, but with a huge delay. I suspect that they don't show up until Travis is finished.

**Comment by stevepeak** [comment]
Hum... I wonder if it was just during a period of a high queue of processing. Is there a specific commit I can review?

We have some speed much needed improvements in the pipeline 🎉 👍

**Comment by untitaker** [comment]
Everything seems to work now, but with severe delays. No idea if those were there before.
