### ISSUE TITLE
Codecov fails with rebuilds on CircleCI

### ISSUE THREAD

**Issue by TPei** [codecov/support#198]
Lately when we rebuild on CircleCI, Codecov fails with `CI failed` message on Github. Codecov additionally shows `Nothing to diff`.

![screen shot 2016-05-12 at 15 31 55](https://cloud.githubusercontent.com/assets/4004343/15216321/ef896732-1856-11e6-9a1d-8ebd2bc2474a.png)
![screen shot 2016-05-12 at 15 33 21](https://cloud.githubusercontent.com/assets/4004343/15216329/f165f35e-1856-11e6-9c04-d6c34d249654.png)

**Comment by davidxia** [comment]
Same here https://github.com/spotify/helios/pull/925

**Comment by davidxia** [comment]
This didn't happen before? I thought Codecov was always just confused by repeated builds.

**Comment by TPei** [comment]
For us these problems only just surfaced a couple weeks ago... I think we might have changed our codecov config around that time, this would mean that that's a configurable error?^^

**Comment by stevepeak** [comment]
Hey, so the CI state was stored as failed and not allowing the status/comment process to proceed. I'm deploying a patch shortly to resolve the issue.

Thank you!

**Comment by davidxia** [comment]
Yay thank you. \o/

On Wednesday, May 25, 2016, Steve Peak <notifications@github.com> wrote:

> Hey, so the CI state was stored as failed and not allowing the
> status/comment process to proceed. I'm deploying a patch shortly to resolve
> the issue.
>
> Thank you!
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/codecov/support/issues/198#issuecomment-221568589>
>


-- 
David Xia
davidxia.com
