### ISSUE TITLE
Consistency between wiki, web help, and yaml checker

### ISSUE THREAD

**Issue by Eric89GXL** [codecov/support#201]
I've noticed a couple of inconsistencies when setting up my project:

1. [This wiki] (https://github.com/codecov/support/wiki/codecov.yml) states different defaults from the **bold** values in the web interface, e.g. https://codecov.io/gh/mne-tools/mne-python/settings/yaml for e.g. `comment: layout:`.

2. The web interface states that `coverage: precision:` can be between 0 and 5 inclusive, but the `curl --data-binary @codecov.yml https://codecov.io/validate` command complained when I had a value > 2 entered.

Sorry to nitpick on an otherwise great service! Which of these sources (web interface, wiki, or YAML checker) should I take as the authoritative source? I assume it's the web interface...

**Comment by stevepeak** [comment]
Deploying shortly. Thank you!
