### ISSUE TITLE
 codecov/patch status check reports wrong patch coverage

### ISSUE THREAD

**Issue by skirpichev** [codecov/support#202]
An example is here: https://github.com/diofant/diofant/pull/272 (second commit).  The codecov/patch — shows "100% of diff hit (target 90.00%)", but on the [details page](https://codecov.io/gh/diofant/diofant/compare/d8b40138808e4f4e3feb4fc3a0c4b72e0f5151ff...8f2867ba4c0dc88a19e2d30b773973e5369ad3fb) there is only "90.24% of changed lines covered".  (Close to the yml limit).

**Comment by stevepeak** [comment]
Deploying a fix in the next hour, thank you! You'll see the status updated on your PR now.
There was an issue with determining the comparison commit sha.
