### ISSUE TITLE
Coverage badge is not upgrading

### ISSUE THREAD

**Issue by entertainyou** [codecov/support#203]
Related github issue: https://github.com/github/markup/issues/224

Badge request to codecov does not have Cache-Control header set

```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 861
Content-Type: image/svg+xml
Date: Sat, 14 May 2016 10:24:45 GMT
Etag: "87068cd49843b7afa03c55ebf32ca11dc1d07d7d"
Server: TornadoServer/4.3
Vary: Accept-Encoding
Via: 1.1 vegur
X-Request-Id: d0dfd43f-0320-4a64-8416-1b8731b1becd
```

Other CI, like wercker, set headers like the following for badge request:
```
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
```

**Comment by stevepeak** [comment]
Fix is in the pipeline. Thank you!

**Comment by entertainyou** [comment]
@stevepeak , the Cache-Control header is still not set for badge request.

**Comment by stevepeak** [comment]
@entertainyou thanks for pointing this out. I fixed the ETag, but did not set the cache-control properly. Will deploy shortly
