### ISSUE TITLE
Wrong partial coverage on last line of file

### ISSUE THREAD

**Issue by Flamefire** [codecov/support#204]
I have a (new) partial coverage after a commit at the closing `}` of a c++ file: https://codecov.io/gh/Return-To-The-Roots/s25client/src/35dbf8a718d75906f431f90c4d54b43a41325eb4/src/postSystem/PostMsg.cpp

Coverage for this point is rather strange, but it seems to be caused by static arrays that get deleted there. However partial coverage seems wrong, especially as before this commit it was full coverage, so looks like a regression.

**Comment by stevepeak** [comment]
@Flamefire I'll apply a patch today to ignore these lines. Thank you!
