### ISSUE TITLE
Code coverage report not updating?

### ISSUE THREAD

**Issue by uxcq** [codecov/support#205]
Does codecov.io have an issue?

Viewing the report for the following project [gramps](https://codecov.io/github/gramps-project/gramps) I noticed that the last [commits](https://codecov.io/gh/gramps-project/gramps/commits) picked up by codecov.io are from 16 days ago and that project has had many [commits](https://github.com/gramps-project/gramps/commits/master) since then.

**Comment by stevepeak** [comment]
Hey @uxcq looks like there is an issue discovering the coverage reports: https://travis-ci.org/gramps-project/gramps#L1683

**Comment by akshaybabloo** [comment]
I still have this issue - https://travis-ci.org/akshaybabloo/gollahalli-com/builds/247804096

**Comment by johnbickmore** [comment]
@akshaybabloo Open your own issue, don't tag onto this closed issue 👎

**Comment by stevepeak** [comment]
There was a system outage yesterday that we continue to investigate.

This specific issue will be locked. Please open new ones if you have questions. Thank you!
