### ISSUE TITLE
gcov and zero coverage

### ISSUE THREAD

**Issue by jeppefrandsen** [codecov/support#206]
Is it possible with gcov to generate zero coverage for files not covered by tests? 

I found a patch on Google by do not want to compile gcov again if not needed. I know zero coverage is possible with lcov. The patch for gcov can be found here: https://gcc.gnu.org/bugzilla/attachment.cgi?id=35378&action=edit

Thank you very much in advance

**Comment by stevepeak** [comment]
Hey @jeppefrandsen, as long as the reports are generated Codecov will report the files.

I believe the patch you have discovered may produce the proper gcov reports that would be detected by Codecov. Is this patch already implemented?

**Comment by jeppefrandsen** [comment]
Hi @stevepeak,

No, it is not included - also checked gcc 6.1.0. Just wanted to hear if you had a way to generate zero coverage for files not covered by unit test (to have the full coverage of the code). Will compile my own version of gcov with this change. Thanks.

Kind Regards,
Jeppe
