### ISSUE TITLE
404 errors when trying to access pull request coverage

### ISSUE THREAD

**Issue by skirpichev** [codecov/support#209]
When I click on any recent PR in [my list](https://codecov.io/gh/diofant/diofant/pulls), I get 404 error, for example [here](https://codecov.io/gh/diofant/diofant/pull/283).  For old PR's there is no problem, e.g. [here](https://codecov.io/gh/diofant/diofant/pull/272).

Perhaps, this is related to #208.

**Comment by dtiesling** [comment]
+1

Seeing the exact same thing. I am also getting `Coverage Error` for all files when using the chrome extension.

**Comment by stevepeak** [comment]
We had an issue updating updating pulls the the proper head which has been fixed. You should see recently updated pulls (within a couple days) showing up properly.
