### ISSUE TITLE
Handle istanbul ignore next for functions

### ISSUE THREAD

**Issue by Blackbaud-PatrickOFriel** [codecov/support#214]
Codecov does not seem to respect the `/*istanbul ignore next */` comment when it is placed before a function. You can see that at https://codecov.io/gh/blackbaud/skyux/src/75a9940390d25dad5c2c7dbbf2a8ae0529f529e8/js/sky/src/moment/moment.js. 

Here's a screenshot displaying the issue as well (see the registerMoment function showing as not ignored)
![screen shot 2016-05-25 at 3 35 45 pm](https://cloud.githubusercontent.com/assets/11620552/15553800/d78387d4-228e-11e6-875c-d03eaf0403df.png)

**Comment by stevepeak** [comment]
Hey @Blackbaud-PatrickOFriel thank you for pointing this out. Fixing in next release

**Comment by Blackbaud-PatrickOFriel** [comment]
Thanks for the quick response!

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @stevepeak, this was working for a time, but just started failing again. See: https://codecov.io/gh/blackbaud/skyux/src/95864bd50f414272806e94ac93f1daad7d571696/js/sky/src/moment/moment.js

**Comment by Blackbaud-PatrickOFriel** [comment]
@stevepeak any word on when/if this'll start working again?

**Comment by stevepeak** [comment]
Hey @Blackbaud-PatrickOFriel interesting. I had though this was fixed upt. I'll take a look into it now

**Comment by Blackbaud-PatrickOFriel** [comment]
Hey @stevepeak, seems to be working again. Thanks!
