### ISSUE TITLE
not existing branch displayed in dashboard

### ISSUE THREAD

**Issue by xh3b4sd** [codecov/support#216]
For some time now I am seeing a branch in my dashboard that does not exist anymore on Github. IMO this should be deleted automatically. Unfortunately I am not able to remove it manually. Anyway this shouldn't be necessary to do on my own. The branch that is displayed here but does not exist on Github is named `more-clgs`.

<img width="1293" alt="screen shot 2016-05-27 at 23 32 17" src="https://cloud.githubusercontent.com/assets/552769/15621723/4bb606ec-2463-11e6-95f1-7077cd68615a.png">

**Comment by mayeut** [comment]
It's possible to remove them manually one by one but it would be better if this could be done automatically.

It also seem possible to delete the default branch manually (though I haven't try to do it, the link still appears). Is that a feature or a bug ?

**Comment by stevepeak** [comment]
Branches are automatically deleted via GitHub webhooks. If your project is not seeing this, it could be due to lack of webhooks being established. Please contact support in-app or [Slack](slack.codecov.io) for help on specific project(s). Thank you!
