### ISSUE TITLE
GitHub caching affecting my badge

### ISSUE THREAD

**Issue by vinniefalco** [codecov/support#218]
My GitHub badge often shows 73% even though the actual coverage is 97%. I believe this is a problem with GitHub's aggressive imaging caching and codecov.io. When I curl the badge from codecov, there is a "Cache-Control" header but no "Expires:". The 73% figure is at least 10 days old.

https://github.com/vinniefalco/Beast/

![badge](https://cloud.githubusercontent.com/assets/1503976/15647434/82f08482-2631-11e6-92ad-06bfb65c10ef.png)

![coverage](https://cloud.githubusercontent.com/assets/1503976/15647435/88d81c48-2631-11e6-845b-dbd96e3349af.png)

```
 curl -v https://codecov.io/gh/vinniefalco/Beast/branch/master/graph/badge.svg
*   Trying 50.17.198.53...
* Connected to codecov.io (50.17.198.53) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: codecov.io
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
> GET /gh/vinniefalco/Beast/branch/master/graph/badge.svg HTTP/1.1
> Host: codecov.io
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Date: Mon, 30 May 2016 10:33:19 GMT
< Content-Type: image/svg+xml
< Content-Length: 864
< Pragma: no-cache
< X-Ua-Compatible: IE=Edge,chrome=1
< Server: Codecov
< Vary: X-PJAX, Accept-Encoding
< Cache-Control: no-cache, no-store, must-revalidate
< Access-Control-Allow-Origin: *
< Via: 1.1 vegur
< 
<svg xmlns="http://www.w3.org/2000/svg" width="96" height="20">
    <linearGradient id="b" x2="0" y2="100%">
        <stop offset="0" stop-color="#bbb" stop-opacity=".1" />
        <stop offset="1" stop-opacity=".1" />
    </linearGradient>
    <mask id="a">
        <rect width="96" height="20" rx="3" fill="#fff" />
    </mask>
    <g mask="url(#a)">
        <path fill="#555" d="M0 0h60v20H0z" />
        <path fill="#1c8d00" d="M60 0h36v20H60z" />
        <path fill="url(#b)" d="M0 0h96v20H0z" />
    </g>
    <g fill="#fff" text-anchor="middle" font-family="DejaVu Sans,Verdana,Geneva,sans-serif" font-size="11">
        <text x="30" y="15" fill="#010101" fill-opacity=".3">Codecov</text>
        <text x="30" y="14">Codecov</text>
        <text x="77" y="15" fill="#010101" fill-opacity=".3">97%</text>
        <text x="77" y="14">97%</text>
    </g>
* Connection #0 to host codecov.io left intact
</svg>%  
```

**Comment by vinniefalco** [comment]
If I keep reloading the page sometimes it shows 92%:
![badge2](https://cloud.githubusercontent.com/assets/1503976/15647488/dfbd7184-2631-11e6-9ff8-7d12d03d4482.png)

and very rarely, the correct value of 97%:
![badge3](https://cloud.githubusercontent.com/assets/1503976/15647496/e4cfe74c-2631-11e6-9acd-b1aca1db605a.png)

**Comment by alessandrodalbello** [comment]
It seems I have the same problem. Any news?

**Comment by vinniefalco** [comment]
@alessandrodalbello How does one "use http://shields.io", can you give me an example? Here's the current Markdown I am using to display the Codecov badge:

```
[![codecov]
(https://codecov.io/gh/vinniefalco/Beast/branch/master/graph/badge.svg)](https://codecov.io/gh/vinniefalco/Beast)
```

How do I modify this?

**Comment by alessandrodalbello** [comment]
Sure @vinniefalco, glad to help you somehow. This is our badge code:
```
[![Coverage](
https://img.shields.io/codecov/c/github/chesslave/chesslave.svg?maxAge=600)]
(https://codecov.io/gh/chesslave/chesslave)
```
URL param `maxAge` does the trick. The value is expressed in seconds.

Your badge code might be something like
```
[![Coverage](
https://img.shields.io/codecov/c/github/vinniefalco/Beast.svg?maxAge=0)]
(https://codecov.io/gh/vinniefalco/Beast)
```

**Comment by vinniefalco** [comment]
Mind = blown

**Comment by stevepeak** [comment]
I'm adding the `Expires: 0` header, hope that fixes this up!

**Comment by vinniefalco** [comment]
@stevepeak You said you're adding the "Expires: 0" header, do you mean that badges served by CodeCov's HTTP server will include that header in their HTTP response? Should I still switch to shields.io?

**Comment by stevepeak** [comment]
I think the badges are working as expected now. We have a couple headers that do not allow caching.

Have you experienced otherwise lately?

**Comment by vinniefalco** [comment]
I haven't seen an old badge in a few days, so I guess no action is required on my part. I'll close this, thanks!
