### ISSUE TITLE
Incorrect label value for coverage

### ISSUE THREAD

**Issue by Kozoriz** [codecov/support#219]
When i put label address to my project, i wanna to see coverage for specified [branch](https://codecov.io/gh/smartdevicelink/sdl_core/branch/develop). 
But i see coverage for last correctly builded pull request to this specified branch.

**Comment by Kozoriz** [comment]
![screenshot from 2016-05-31 18 21 43](https://cloud.githubusercontent.com/assets/8917619/15680401/4aa7729c-275e-11e6-933a-5b0da38808aa.png)

**Comment by LuxoftAKutsan** [comment]
I would like to specify this issue more clearly.
An icon https://codecov.io/github/smartdevicelink/sdl_core/coverage.svg?branch=develop 
shows coverage not of the latest commit on develop branch but coverage of the last analysed pull request (last build).

**Comment by mhils** [comment]
The same is true for the dashboard at https://codecov.io/gh/mitmproxy/mitmproxy/branch/master, which also shows the latest PR.

**Comment by LuxoftAKutsan** [comment]
@mhils  is it expected behaviour of the system? Can it be changed? How can I get latest coverage statistics by certain branch? For my project it is rather important

**Comment by stevepeak** [comment]
For the badge please use this url:

```
https://codecov.io/gh/OWNER/REPO/branch/master/graph/badge.svg
```
