### ISSUE TITLE
No branch and method output for lcov file

### ISSUE THREAD

**Issue by Swatinem** [codecov/support#22]
I have uploaded the following lcov file https://gist.github.com/Swatinem/262e59ba04d99207f69a
here: https://codecov.io/github/Swatinem/yavd?ref=372762b827bc1af7a849487f29f303fc7ceabf2f
But as you can see, the branch and method coverage is empty, although it is available inside the lcov file.
Also, `lcov --list lcov.info --rc lcov_branch_coverage=1` and `genhtml lcov.info --rc lcov_branch_coverage=1` include the correct counts.

**Comment by stevepeak** [comment]
Thanks @Swatinem, (sorry for delay) this is at the top of my work-list tomorrow :+1: I'll be in touch when its complete.

**Comment by stevepeak** [comment]
Just deployed: Fix branches, store methods, and show notes on what part of the method was missed. Cheers!

**Comment by Swatinem** [comment]
Thanks! It’s still not 100% correct though, see here:

I uploaded this lcov file: https://gist.github.com/Swatinem/6719f02ffbd0ab91788b
here: https://codecov.io/github/Swatinem/yavd?ref=2aa9ebf33757107144211422bc760236f931f3e9&view=all

functions are there, but the branch and line numbers a little bit off compared to those reported by lcov and istanbul:

```
lcov --list coverage/lcov.info --rc lcov_branch_coverage=1
Reading tracefile coverage/lcov.info
                        |Lines       |Functions  |Branches    
Filename                |Rate     Num|Rate    Num|Rate     Num
==============================================================
[/home/swatinem/Coding/yavd/]
ext/stringify.js        | 100%     27| 100%     7| 100%     14
lib/create.js           | 100%     18| 100%     1| 100%     10
lib/index.js            | 100%     12| 100%     2|    -      0
lib/instance.js         |94.4%     36| 100%    10|71.4%     14
lib/jsx.js              | 100%     14| 100%     2| 100%     10
lib/props.js            | 100%     35| 100%     3| 100%     28
lib/update.js           | 100%     23| 100%     2| 100%     13
==============================================================
                  Total:|98.8%    165| 100%    27|95.5%     89
```

The istanbul html reporter shows the same branch/line numbers as lcov, but has additional statement numbers. But I guess thats a limitation of the lcov format -_-

**Comment by stevepeak** [comment]
> Referencing [create.js](https://github.com/Swatinem/yavd/blob/master/lib/create.js)

I count 4 branches: lines `4, 9, 19, 27` the lcov is says there is 10 (because `5x2=10`) and counts the method as a branch...

1. One thing that would be worked is the branches reporting the 2x concept, which I would agree is needing to be fixed.
2. Should methods count as branches? Thoughts?

> Referencing [instance.js]()

The lcov is reporing that [line 61 is partially hit](https://gist.github.com/Swatinem/6719f02ffbd0ab91788b#file-lcov-info-L215-L216) however that line is simply a `}` [end of branch](https://codecov.io/github/Swatinem/yavd/lib/instance.js?ref=master#l-61). Is this a flaw in lcov?

**Comment by Swatinem** [comment]
> Referencing instance.js
> 
> The lcov is reporing that line 61 is partially hit however that line is simply a } end of branch. Is this a flaw in lcov?

Maybe it references the end line of the if instead of the if statement itself, but in those cases only the if or the else branch are taken.

**Comment by Swatinem** [comment]
> I count 4 branches: lines 4, 9, 19, 27 the lcov is says there is 10 (because 5x2=10) and counts the method as a branch...

Its possible that it treat the ES6 default parameter as a branch. Not really sure, I have to dig into it

**Comment by Swatinem** [comment]
Ok, it does indeed report a branch for default parameters (since they are evaluated as expressions)
So for this file here:
```js
function withDefaults(param = 'bar') {
  if (param === 'foo') {
    'whatever'
  }
  // else not covered
}

withDefaults('foo')
```
I get the following lcov output:
```lcov
TN:
SF:/home/swatinem/Coding/yavd/covtest/test.js
FN:1,withDefaults
FNF:1
FNH:1
FNDA:1,withDefaults
DA:0,1
DA:1,1
DA:2,1
DA:3,1
DA:8,1
LF:5
LH:5
BRDA:1,1,0,0
BRDA:1,1,1,1
BRDA:2,2,0,1
BRDA:2,2,1,0
BRF:4
BRH:2
end_of_record
```
And the following output from istanbuls html reporter:
![istanbul](https://cloud.githubusercontent.com/assets/580492/8257900/21a22202-16b1-11e5-8799-1beed670e361.png)

As I see in the screenshot, the location (start/end) for the default param is also wrong there, but thats a different issue.

**Comment by Swatinem** [comment]
The line count is also broken somewhat. But lcov does not differentiate between lines and statements so that’s unfortunate.

**Comment by stevepeak** [comment]
Here is the processing of lcov files: https://gist.github.com/stevepeak/55937a42520a7fe296c0

Perhaps you can help tweak it to get the expected values, because I'm not certain on what needs to happen to get this more accurate

**Comment by Swatinem** [comment]
https://gist.github.com/stevepeak/55937a42520a7fe296c0#file-lcov-py-L55 <- do I read the code correctly that you assume 1 branch per line?
There can indeed be more branches per line.

```
BRDA:1,1,0,0
BRDA:1,1,1,1
BRDA:1,2,0,1
BRDA:1,2,1,0
```
for the code `function withDefaults(param = 'bar', param2 = 'default2') {`

**Comment by stevepeak** [comment]
In this case the result could be: Line 1 has 2/4 hits. And the comment would say "pos 0, 2 not called"

**Comment by Swatinem** [comment]
From http://ltp.sourceforge.net/coverage/lcov/geninfo.1.php:
```
Branch coverage information is stored which one line per branch:

         BRDA:<line number>,<block number>,<branch number>,<taken>

       Block number and branch number are gcc internal  IDs  for  the  branch.
```

Not really helpful indeed :-(

Not really sure what gcc is generates, but istanbul just gives branch id 0/1 for if/else.

Maybe instead of using the branch id in your mapping, just leave it out and just count hits/found.

**Comment by Swatinem** [comment]
> And the comment would say "pos 0, 2 not called"

I’m afraid lcov is not detailed enough to actually give accurate information there so I don’t think the comment is of any help.
