### ISSUE TITLE
Empty coverage badge (not displayed on GitHub page)

### ISSUE THREAD

**Issue by jeppefrandsen** [codecov/support#220]
Hi,

We see that the badge for our develop branch is not shown on our GitHub page. If I open the link directly is is just an empty badge: https://codecov.io/gh/bang-olufsen/ase/branch/develop/graph/badge.svg (wihtout token). 

Thank you very much in advance.

**Comment by stevepeak** [comment]
Hey, sorry for the delay, I found an issue when the coverage was `< 1%` and will patch and resolve now. Thank you for your patience 👍
