### ISSUE TITLE
codecov reports in PRs include unchanged files

### ISSUE THREAD

**Issue by megies** [codecov/support#221]
Sometimes (or rather quite regularly) codecov is reporting changes in files that are definitely not changed in the PR.

See e.g. obspy/obspy#1439 (single commit branch based on `master`):

codecov reports changes in file `obspy/io/seiscomp/sc3ml.py`, but the only changed files (in a single commit) are..
 - `CHANGELOG.txt`
 - `obspy/core/tests/test_trace.py` 
 - `obspy/core/trace.py`

![screenshot from 2016-06-03 16 27 35](https://cloud.githubusercontent.com/assets/1842780/15781948/aefa6820-29a8-11e6-8efd-51ef9e6097e1.png)
![screenshot from 2016-06-03 16 27 18](https://cloud.githubusercontent.com/assets/1842780/15781949/aefe1db2-29a8-11e6-9a1b-0cea1e77292d.png)
![screenshot from 2016-06-03 16 26 49](https://cloud.githubusercontent.com/assets/1842780/15781950/af0117d8-29a8-11e6-879f-7b031555d772.png)

P.S.: Codecov github/browser plugin is nice!

**Comment by stevepeak** [comment]
Hey @megies sorry for the delay. You'll see "changes" like these when coverage changed in files that were not adjusted in th PR. A shinning example of this is adjusting tests. If you add/remove/change tests you affect coverage without changing the lines being tested.

**Comment by megies** [comment]
Hi @stevepeak, no worries. But I'm still not fully convinced.. 
Is there a way to see what those `Hits +3` in that file `io/seiscomp/sc3ml.py` are?

In the PR i chose as an example I've only added a `setter` to a formerly read-only property `Trace.id`, and I really don't see it being used in `sc3ml.py` or the related tests, and the newly added test certainly doesn't use `sc3ml.py`.
Nevermind if it's a bother for you, really just curious and always a bit doubtful about those codecov comments.. ;-)

**Comment by stevepeak** [comment]
@megies this data should be exposed in our changes interface. When you compare these commits in CC click on the tab "Changes"

I understand your doubtful, I've seen stranger stuff and daily have to help customers dig through data to help figure out coverage issues. If it is an actual issue it almost always ends up being presented in the raw uploaded reports.

**Comment by megies** [comment]
> When you compare these commits in CC click on the tab "Changes"

See it now, thanks for the directions.

Still can't see a way to explain those changes, the only thing I can think of is test execution order changed by the single additional test function. But even that can not explain the change.

Anyway, thanks for the help!
