### ISSUE TITLE
Coverage to high due to incorrectly detected statements

### ISSUE THREAD

**Issue by Flamefire** [codecov/support#223]
I'm using codecov and lcov for comparison and debugging code coverage and have seen, that the coverage on codecov is much higher than it seems that it should be. As lcov (to my understanding) does not include partial coverage I expected it to be the other way round. Comparing an example file I found a potential cause: Non-executed statements are marked as executed.

Example: `GamePlayer.cpp`. lcov=42.4% vs codecov=57.0%. Looking at the file (https://codecov.io/gh/Return-To-The-Roots/s25client/src/f0ec6f8e224b8d24ab9f6474db12466e5269d64e/src/GamePlayer.cpp#L214) I see covered lines (marked) that are in a method that is never executed. I'm pretty sure, this is due to the attempt to reduce the number of partials which results in false positives here.

**Comment by stevepeak** [comment]
Hey @Flamefire super odd... The reports are accurate, its just the page building that is wrong. But I'm having a hard time replicating it, but will fix asap. Thank you for pointing this out.

**Comment by Flamefire** [comment]
It seems the reports are *now* accurate. They were not before. (I see a coverage decrease in a PR that actually adds a huge coverage increase) However it is at least (more) correct now.

Regarding the UI Bug: Check this: https://codecov.io/gh/Return-To-The-Roots/s25client/src/6e3a0e22f8d30f09389088e7c98783f6f92b681c/src/BasePlayerInfo.cpp Coverage is initially correct, but toggling hits will make everything appear (wrongly) as covered

**Comment by stevepeak** [comment]
Figured it out 👍 Thank you for reporting this. Deploying shortly.
