### ISSUE TITLE
GitHub status check says patch requires 80% while yml says 60%

### ISSUE THREAD

**Issue by frobichaud** [codecov/support#224]
Hi,
my repo is configure with the following yml:
```
    patch:
      default:
        enabled: yes
        target: 60%
```

But it says 80% in status checks of a Pull Request

<img width="686" alt="screen shot 2016-06-08 at 4 08 52 pm" src="https://cloud.githubusercontent.com/assets/3533748/15909227/54008e7e-2d93-11e6-8e75-41c270a416a8.png">

**Comment by stevepeak** [comment]
Hey @frobichaud what project is this for? My guess is the recent yaml is not a valid format and therefore not currently being used.

```
curl --data-binary @codecov.yml https://codecov.io/validate
```

**Comment by frobichaud** [comment]
thanks @stevepeak 
here is the validate output

Valid!

{
  "comment": {
    "behavior": "default",
    "layout": "header, diff, changes, sunburst, uncovered"
  },
  "coverage": {
    "precision": 2,
    "status": {
      "project": {
        "default": {
          "target": "auto",
          "if_not_found": "success",
          "if_no_uploads": "error",
          "enabled": true,
          "if_ci_failed": "error"
        }
      },
      "patch": {
        "default": {
          "target": 60.0,
          "if_not_found": "success",
          "if_no_uploads": "error",
          "enabled": true,
          "if_ci_failed": "error"
        }
      },
      "changes": {
        "default": {
          "if_ci_failed": "error",
          "if_not_found": "success",
          "if_no_uploads": "error",
          "enabled": true
        }
      }
    },
    "round": "down",
    "range": [
      70.0,
      100.0
    ],
    "notify": {
      "slack": {
        "default": {
          "branches": [
            "master"
          ],
          "attachments": "sunburst, diff",
          "url": "https://hooks.slack.com/services/xxxxxxxx"
        }
      }
    }
  },
  "codecov": {
    "bot": "petalbot",
    "branch": "master",
    "token": "xxxxxxxx"
  }
}

**Comment by stevepeak** [comment]
Whats the owner/repo? Thanks

**Comment by frobichaud** [comment]
@stevepeak petalmd/petalmd.ios (private)

**Comment by stevepeak** [comment]
From what I see the yaml was last updated on master as of `ec9dcdb36`.

What was the commit sha for the original issue?

**Comment by frobichaud** [comment]
@stevepeak 
We recently moved from gitlab to github. This is our current repo?
https://codecov.io/gh/petalmd/petalmd.ios

codecov.yml was last updated by ```7fa06f0 ```

**Comment by stevepeak** [comment]
I wonder if the issue if this: codecov will always use the codecov.yml at the time of commit being tested and not the most recent on master. So if your commit is behind master it will not pick up the changes in the codecov.yml. This is the default behavior and you can change this to always use a tip of the master branch if you would like.

**Comment by frobichaud** [comment]
Hi @stevepeak, 
Here are the details:
- in our petalmd/petalmd.ios repo: our codecov.yml was last merged into master with 7fa06f0 11 days ago. The setting is 60%
- I juste created a branch off master, and pushed c538995. 
The pull request shows 
```codecov/patch — 100% of diff hit (target 80.00%)```

Pretty sure everything is fine on our side.

**Comment by jmaitrehenry** [comment]
I have a similar issue with the bot field:
```
codecov:
  token: xxxxx
  branch: master
  bot: petalbot
```
Coverage is uploaded with:
`curl -s https://codecov.io/bash > coverage.sh && chmod +x coverage.sh && ./coverage.sh -J '^#{ENV['IOS_SCHEME']}$' -D ../#{ENV['BUILD_OUTPUT']}"`
But codecov post comments in pull request with my account, not with petalbot account.
(same repository as @frobichaud)

It's like the YAML is not used

**Comment by jmaitrehenry** [comment]
Other strange point, commit `ec9dcdb36` not exist on this repository

**Comment by frobichaud** [comment]
@stevepeak it seems fixed. Have you changed anything on your end?

**Comment by stevepeak** [comment]
@frobichaud We have changed a couple things here and there, but I'm not sure if it pertains to this issue. Let me know if you see it again. At one point your yaml had 80% (from what I recall reviewing), the change to 60% may would only reflect on that pull request it was presented on. Codecov will always use the yaml at current commit being tested (you can change this behavior if you would like).

@jmaitrehenry when was `bot: petalbot` included? I'm not seeing it the yaml cached in our db as of `ec9dcdb36`

**Comment by jmaitrehenry** [comment]
It's now resolved for me and @frobichaud.
You can close this issue @stevepeak !
