### ISSUE TITLE
excluding directories from C++ coverage count

### ISSUE THREAD

**Issue by nschloe** [codecov/support#226]
When using CodeCov + gcov with a C++ code, e.g., [Mikado](https://codecov.io/gh/nschloe/mikado), I noticed that the directories `src/` _and_ `test/` are accounted for in the coverage report. Obviously, though, I don't really care if all tests are executed; I really only want to see coverage in the actual `src/` library.

Is there a way to exclude directories from the coverage report?

**Comment by stevepeak** [comment]
Hey @nschloe You can ignore coverage by adding a `codecov.yml` to your project:

```
coverage:
  ignore:
    - "test/*"
```
> Learn more about the yaml on your https://codecov.io/gh/nschloe/mikado/settings/yaml

Thank you 👍
