### ISSUE TITLE
Bot says coverage will decrese, report says not

### ISSUE THREAD

**Issue by burabure** [codecov/support#232]
Bot says:
![image](https://cloud.githubusercontent.com/assets/3132298/16157889/f06e8cb2-3490-11e6-9187-77f3d8c230c2.png)

report says:
https://codecov.io/gh/springboardretail/springboard-retail/pull/2541?src=pr

that PR didn't change any covered files, so bot is crazy

**Comment by burabure** [comment]
@stevepeak this is happening constantly in almost all of out PRs now. halp please! this is really counterproductive

**Comment by stevepeak** [comment]
Hey @burabure, sorry for the delayed reply. I'm currently debugging this setup and will return to this feed shortly. I appreciate you pointing this out and will have answers shortly.

**Comment by stevepeak** [comment]
@burabure I've applied a fix server side. The issue was merging lcov report statements and branches.
