### ISSUE TITLE
badge colors too bright

### ISSUE THREAD

**Issue by nschloe** [codecov/support#233]
Codecov's badge colors are generally brighter than others [1] or so light that it's hard to read the text e.g., [2].

A better default set of colors may be derived from [shield.io's default colors](https://github.com/badges/shields/blob/master/colorscheme.json).

[1] https://github.com/nschloe/pygmsh
[2] https://github.com/nschloe/meshio

**Comment by zbeekman** [comment]
At first glance I thought this was a stupid issue, but upon looking at the example badges, I completely agree: The shield.io color palette should be adopted, because the codecov badges are often illegible, depending on your coverage level

**Comment by stevepeak** [comment]
Just deployed new colors to match shields. Thanks

**Comment by nschloe** [comment]
The issue occurs again. @stevepeak reopen?

**Comment by stevepeak** [comment]
The image could be cached.. What is the endpoint you are viewing the badge at? Can you link me the url?

https://cl.ly/2a050f0n2r1u

**Comment by nschloe** [comment]
It occurs with disabled cache too. Check [here](https://github.com/nschloe/meshio). (It does _not_ match the current badged link. – Perhaps a deployment issue?)

**Comment by stevepeak** [comment]
@nschloe Thanks for helping out. I'll review the other images endpoint to see if there is an issue with colors there.

**Comment by nschloe** [comment]
@stevepeak Thanks for the PR!

**Comment by destroyerofbuilds** [comment]
Using: https://codecov.io/gitlab/hutson/semantic-release-gitlab/branch/master/graphs/badge.svg
![branch](https://cloud.githubusercontent.com/assets/10657293/17384059/f1e4f6f2-599e-11e6-9b1e-5d2aeb0555b9.png)

Using: https://codecov.io/gitlab/hutson/semantic-release-gitlab/coverage.svg?branch=master
![coverage](https://cloud.githubusercontent.com/assets/10657293/17384061/f4ce40e4-599e-11e6-8b55-7524669b2c62.png)

**Comment by nschloe** [comment]
It's weird that it should be different, but well.

**Comment by stevepeak** [comment]
Looks like there was a color adjustment that caused the brighter colors. Fixed and deploying today.
