### ISSUE TITLE
[Ruby] reports not being generated.

### ISSUE THREAD

**Issue by ledbettj** [codecov/support#236]
I'm seeing bot comments and commit information, but Codecov is still showing:

> No reports uploaded yet.

Even for PRs that are several days old.  Related to this, I think, I'm not seeing any Github checks for Codecov.

The semaphoreci output doesn't indicate that anything went wrong:

```
{"queued": true, "message": "Coverage reports upload successfully", 
  "uploaded": true, "id": "<snip>", "meta": {"status": 200}, "url": "http://codecov.io/github/<snip>"}
```

This was working fine previously.  Not sure if it started being flakey around the time settings got migrated to YAML or not.

**Comment by stevepeak** [comment]
Hey @ledbettj I can checkout the logs with the `owner/repo@sha`.

The known issues with ruby upload are (a) no tests written will produce no reports, (b) not properly importing files will no be tracked.

You can PM me on https://gitter.im/codecov/support

Thanks :)

**Comment by ledbettj** [comment]
Late update, but this was def. resolved.
