### ISSUE TITLE
Coverage report isn't including most files

### ISSUE THREAD

**Issue by aem** [codecov/support#237]
When I run `istanbul` locally I see proper output for all `.js` files in my project, and `codecov` says the report was uploaded successfully:

```sh
// test output omitted
  2 passing (1s)

=============================================================================
Writing coverage object [/Users/Adam/git/docs-soap/coverage/coverage.json]
Writing coverage reports at [/Users/Adam/git/docs-soap/coverage]
=============================================================================

=============================== Coverage summary ===============================
Statements   : 81.51% ( 119/146 )
Branches     : 79.25% ( 126/159 )
Functions    : 84.62% ( 11/13 )
Lines        : 82.61% ( 114/138 )
=============================================================================
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v1.0.1
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration: 
    Endpoint: https://codecov.io
{ commit: 'e4999e24a7f31ca27a2c1bc2de8b47d999c075d9',
  branch: 'codecov-testing',
  token: 'e8eee2b9-f7fc-4a10-92b3-4b9b68c3cc91',
  package: 'node-v1.0.1' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find . -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + ./coverage/lcov.info
    + ./coverage/coverage.json
==> Uploading reports
    Success!
    View report at: http://codecov.io/github/aem/docs-soap/commit/e4999e24a7f31ca27a2c1bc2de8b47d999c075d9
```

But when I look at coverage on https://codecov.io/gh/aem/docs-soap/commit/e4999e24a7f31ca27a2c1bc2de8b47d999c075d9 there's only one small file with coverage reported.

Any idea what's causing the discrepancy between the local coverage report and what I'm seeing in codecov.io?

**Comment by stevepeak** [comment]
Happy to help out. Can you help point out file paths that are missing from the report?

**Comment by aem** [comment]
@stevepeak thanks for getting to this quickly! The only file shown in coverage reports is `parseHTML.js` in this directory: https://github.com/aem/docs-soap/tree/master/src but all files in that directory should be eligible for coverage.

**Comment by aem** [comment]
The correct statement and branch counts are shown after running `istanbul` as I showed in that snippet above, but the coverage reports on codecov.io only show 8 statements eligible for coverage

**Comment by aem** [comment]
@stevepeak resolved this on my own. a combination of my own stupidity (had my test file pointing at my `dist/index.js`) and istanbul not handling ES6 code properly
