### ISSUE TITLE
large execution counts de-sync with lines on codecov.io

### ISSUE THREAD

**Issue by zbeekman** [codecov/support#24]
Check out this: https://codecov.io/github/zbeekman/json-fortran/src/json_module.F90?ref=master#l-1166

The issue seems to be that large execution counts cause text wrapping in the second column on the left which then causes to counts to de-sync with their source lines

**Comment by stevepeak** [comment]
Thanks for bringing this to my attention. I have a fine solution for this. I'll add it to my work log for tomorrows hack :+1:

**Comment by zbeekman** [comment]
This looks like it’s fixed so I’m going to close this issue
