### ISSUE TITLE
coverage report stuck while processing

### ISSUE THREAD

**Issue by hannesmuehleisen** [codecov/support#240]
i have two commits which are stuck saying " Waiting for CI to finish and reports to complete processing. Please review commit coverage with caution, it may change." - it's been five hours so perhaps something is off there?

https://codecov.io/gh/hannesmuehleisen/MonetDBLite/commit/287608bd7b92d7b9f556a981f24e2cb1e830eacd

**Comment by stevepeak** [comment]
Looks like the hold up was an AppVeyor job that is still pending

See here: https://api.github.com/repos/hannesmuehleisen/MonetDBLite/commits/287608bd7b92d7b9f556a981f24e2cb1e830eacd/statuses

Would you like to ignore AppVeyor builds?

**Comment by hannesmuehleisen** [comment]
yes!

**Comment by stevepeak** [comment]
Ok :) Please add this to your `codecov.yml`

```yaml
codecov:
  ci:
    - !ci.appveyor.com
```

**Comment by hannesmuehleisen** [comment]
cool thanks

**Comment by gvegayon** [comment]
Hi, I have the same issue here but both [travis](https://travis-ci.org/USCCANA/netdiffuseR/builds/167210751) and [appveyor](https://ci.appveyor.com/project/gvegayon/netdiffuser) have already finished https://codecov.io/gh/USCCANA/netdiffuseR/commit/c471e249540febda0bfeb0208749912463e4fea3 The commit was done ~17 hours ago by the time of this message. Is there anything I can do?

**Comment by stevepeak** [comment]
@gvegayon I'll check it out and restart our backend jobs. Thanks!

**Comment by gvegayon** [comment]
Hey! Sorry to bother again, but a [new push](https://codecov.io/gh/USCCANA/netdiffuseR/commit/53a2538b390cc4bd38b359f21dd4ce26b76a9749) got stuck (21 hours now). Both [travis](https://travis-ci.org/USCCANA/netdiffuseR/builds/167470315) and [appveyor](https://ci.appveyor.com/project/gvegayon/netdiffuser/build/1.0.139) are OK.
