### ISSUE TITLE
Show coverage trend in overview

### ISSUE THREAD

**Issue by csoltenborn** [codecov/support#241]
For me, one of the most interesting metrics is how coverage develops over time. Can you add a *Coverage history* widget to the Overview tab? Here's an example of an according diagram from Jenkins:

![image](https://cloud.githubusercontent.com/assets/352576/16566131/6b9646e4-4212-11e6-9843-fde024b855ba.png)

Some more thoughts:
* x axis should obviously be coverage in percent
* y axis should be either builds (as shown above) or time (with actual builds marked somehow, eg. as dots
* time period should probably be configurable
* if available, different coverage criteria (e.g., line and branch converage) could be shown as differently colored lines
* same holds for different collections of tests (e.g. unit and integration tests, see #242 )

**Comment by stevepeak** [comment]
Excellent suggestion 👍  we are looking into providing more trending metrics on the dashboard.

We do have a line chart that you can try out. 

```
https://codecov.io/gh/OWNER/REPO/branch/master/graphs/commits.svg
```

**Comment by csoltenborn** [comment]
I'd seen that svg, but it's rather rudimentary :-) No offense intended - you surely cannot implement all features at once...

**Comment by stevepeak** [comment]
Totally understand! We are working on a new dashboard with trends and graphs galore 👍

**Comment by stevepeak** [comment]
Coming this week ;) 
<img width="1177" alt="screen shot 2016-07-20 at 7 12 01 am" src="https://cloud.githubusercontent.com/assets/2041757/16984640/540491e6-4e49-11e6-9f76-7908f0132751.png">
