### ISSUE TITLE
Support unit and integration test coverage (and more)

### ISSUE THREAD

**Issue by csoltenborn** [codecov/support#242]
My use case is as follows: I'd like to execute my unit/integration/load/... tests separately, each measuring its own coverage. I'd then like to upload all coverage data and get it displayed side by side at codecov.io, probably enhanced by information such as percentage of unit/integration/... tests of project.

I'm aware that this is probably a rather complex requirement, but it should certainly set codecov apart from its competitors :-) If you would be willing to implement this feature, I'd be happy to discuss specifics and do beta testing...

**Comment by stevepeak** [comment]
Give this a shot:

```
bash <(curl -s https://codecov.io/bash) -F unittests -f path/to/report.txt
bash <(curl -s https://codecov.io/bash) -F integration -f path/to_other/report.txt
-- or --
# ci build 1
bash <(curl -s https://codecov.io/bash) -F unittests
# ci build 2
bash <(curl -s https://codecov.io/bash) -F custom_title
```

We call these **Flags** which are used to tag where metrics came from and result in: http://cl.ly/1v013x3C2446 you can quickly toggle the flags in the UI. We plan to add support to all feature and UI views concerning flags in the near future.

**Comment by csoltenborn** [comment]
Ok, that's plain awesome :-) - sorry for not seeing this in the docs...

However, I just gave it a try (see branch [CodeCov](https://codecov.io/gh/csoltenborn/GoogleTestAdapter/branch/CodeCov)) - uploading works just fine, but the different coverage categories do not show up in the UI. This is probably related to UI support not being implemented yet!?

By uploading unit and integration coverage data, will I be able to see unit, integration, and overall coverage (the latter merging unit and integration coverage data)? And will I also be able to provide that data by means of badges on my project homepage?

**Comment by csoltenborn** [comment]
Just to let you know: This issue can be closed from my point of view (but I'm leaving the decision to you). I'll see what you guys come up with :-)

**Comment by stevepeak** [comment]
Excellent, thank you!

PS if you have interest in doing a blog post on this feature we would be thrilled to help out :)

**Comment by csoltenborn** [comment]
Sorry, I fear I don't have a blog... But thanks for implementing #241! Looking forward to see information about coverage of the different test kinds in the new dashboard!
