### ISSUE TITLE
Badge-like embeddable report

### ISSUE THREAD

**Issue by squest** [codecov/support#245]
Can you make the report on the dashboard embeddable (probably in markdown format for readme). I think it will be very useful, so we can let everyone know which part of the codebase already covered by the tests.

Thanks!!

Btw, Thanks for making Clojure available, really helpful for us!

**Comment by stevepeak** [comment]
Thank you for the feature request! Love the idea and will look into implementation in the near future.

From my experience the only way to embed such objects in a readme is through images (specifically svgs). Which can refresh and receive click events 👍

**Comment by stevepeak** [comment]
Concept look. All feedback welcome.

```
path/to/file.py ......          57%
path/to/file.py .............   73%
```

----

### Endpoint
```
https://codecov.io/gh/owner/repo/branch/master/graphs/files.svg
```

### Arguments

- `?path=` only show files from this path(s)
- `?flag=` only show details from this flag(s)
- `limit`, `sortby`

**Comment by squest** [comment]
👍

**Comment by stevepeak** [comment]
Deploying this week. :)
