### ISSUE TITLE
Repository must be activated.

### ISSUE THREAD

**Issue by amatkivskiy** [codecov/support#247]
Hi guys,

I have a private repository where I am a collaborator.
After following the guide how to setup integration with codecov.io for android gradle project and while uploafing the coverage report I get this error: 

```
 -> Pinging Codecov
    -> to Codecov
    HTTP 402
Repository must be activated.
```

Thanks in advance.

**Comment by stevepeak** [comment]
Hey @amatkivskiy if the repository is private it must be activated in our UI first before uploading reports. If you have proper authorization to the project you can enable the project on the setting page:
https://codecov.io/gh/OWNER/REPO/settings

Thanks!

**Comment by amatkivskiy** [comment]
@stevepeak Thanks, I tried it but it doesn't work. 
See screenshot:
![screenshot 2016-07-06 18 13 14](https://cloud.githubusercontent.com/assets/3864884/16623127/616d971e-43a5-11e6-8f28-b5ba4fca5cf6.png)

In browser console I get this error:
```
{"error": {"context": null, "reason": "Not Found."}, "meta": {"status": 401}}
```

**Comment by stevepeak** [comment]
What is the owner/repo name? Thanks

**Comment by amatkivskiy** [comment]
Sent an email to you with this info.

**Comment by stevepeak** [comment]
Hey, I have not seen an email come through yet. Try hello@codecov.io 
What email did you use?

**Comment by amatkivskiy** [comment]
I have resent it to hello@codecov.io. Previously sent it to steve@codecov.io.

**Comment by stevepeak** [comment]
I have not received :( i hope it's not our mail servers...

**Comment by amatkivskiy** [comment]
@stevepeak I have sent one more email today's morning.

**Comment by stevepeak** [comment]
Got the email. Will follow up with you there.
