### ISSUE TITLE
branch button should also have drop down menu of available branches

### ISSUE THREAD

**Issue by zbeekman** [codecov/support#25]
The ‘Features’ —> ‘commits’ menu accurately shows the commits and branches available. Therefore it shouldn’t be too hard to switch branches with the branches menu rather than just showing how to modify the url to do it.

**Comment by stevepeak** [comment]
I do agree. It was once like that but had to refactor some code and temporarily remove it. But I'll be adding it back tomorrow :+1:

**Comment by zbeekman** [comment]
cool, thanks for the cool product… also just curious: is codecov a one man shop?

**Comment by stevepeak** [comment]
At the moment I'm the only active man on the project. I have part-time help in the graphics and marketing. Thank you for the feedback :+1:
