### ISSUE TITLE
Show coverage trend in overview

### ISSUE THREAD

**Issue by EmilyBjoerk** [codecov/support#252]
**As a user I would like to see coverage over time in a simple line (or area) graph in the overview page.**

I believe that the this graph could share space with the recent commits block which could be compacted a bit. For example by moving the commit link button to be on the same row as the branch, scaling down the font on the commit message and committer icon a bit.

I want to motivate this change by focusing on the purpose of a coverage tool, the purpose is of course coverage. Not logging of commits, hence the commit log has to be considered a secondary information priority (if I want to view the log, I'll look in github/atlassian/bucket/gitk w/e) and as such can be given in a brief and abbreviated form just to be able to identify the commit and committer. 

Pardon my poor attempt at gimp-shop: 

Before:
![image](https://cloud.githubusercontent.com/assets/5306929/16707116/ce91c6e6-45c4-11e6-9c99-941f44fc6e95.png)

After:
![image](https://cloud.githubusercontent.com/assets/5306929/16707115/c9c3f594-45c4-11e6-8a50-4ff7a9c709b2.png)

**Comment by Flamefire** [comment]
See #241

**Comment by stevepeak** [comment]
Coming this week :)
<img width="1177" alt="screen shot 2016-07-20 at 7 12 01 am" src="https://cloud.githubusercontent.com/assets/2041757/16984643/592b851c-4e49-11e6-87a9-a53a2697b136.png">
