### ISSUE TITLE
Cannot get coverge reports to merge

### ISSUE THREAD

**Issue by frerich** [codecov/support#254]
In [my project](https://github.com/frerich/clcache) I'm basically running these four commands to execute the tests, generate code coverage data and upload the coverage data to codecov.io (the exact sequence is visible in [the `appveyor.yml` file](https://github.com/frerich/clcache/blob/master/appveyor.yml#L52)). The intention is to run two tests `unittests.py` and `integrationtests.py` and gather which lines in the file `clcache.py` have been executed (`PYTHON_INSTALL` is an environment variable identifying the currently used Python interpreter, e.g. `Python2.7`):

```
py.test --junitxml .\unittests.xml unittests.py --cov=clcache
codecov --no-color -X gcov -F unittests -e PYTHON_INSTALL
py.test --junitxml .\integrationtests.xml integrationtests.py --cov=clcache --cov-append
codecov --no-color -X gcov -F integration -e PYTHON_INSTALL
```

I'm calling `codecov` twice here, with different flags, to be able to see the code coverage per test lateron.

Alas, in the [generated codecov.io report](https://codecov.io/gh/frerich/clcache/src/0575dd50eb6bf41d3f3353696cf5b38532468776/clcache.py), the coverage appears to be a) too low and b) only include the results for the `unittests.py` run (or is it just `integrationtests.py`? I'm not totally sure -- but it does not look like a merged report).

I tried experimenting with the `py.test` invocations to include (or exclude) the `--cov-append` switch, but that didn't seem to have any effect. Is there anything obviously wrong with what I'm doing here? :-)

**Comment by stevepeak** [comment]
I believe the `--cov-append` is causing the issue. I'm using py.test with almost the same setup to test some of Codecov backend and it's working fine, so there is some configuration setup here that is off.


```bash
py.test --junitxml .\unittests.xml unittests.py --cov=clcache
# just checkiong output, remove when satisfied
coverage report
codecov --no-color -X gcov -F unittests -e PYTHON_INSTALL

# just to be safe, but should not be required
rm .coverage coverage.xml

# removed --cov-append
py.test --junitxml .\integrationtests.xml integrationtests.py --cov=clcache
# just checkiong output, remove when satisfied
coverage report
codecov --no-color -X gcov -F integration -e PYTHON_INSTALL
```

**Comment by frerich** [comment]
Thanks for your reply! I think I now have a better understanding what's going on - it turned out that one thing I overlooked was that the `integrationtests.py` test actually invokes the `clcache.py` program recursively (in separate Python interpreter processes), and those invocations did not generate coverage data because they were not executed via `coverage`! I fixed this now, but alas Codecov still doesn't seem to show the report I expected.

In my [latest attempt](https://github.com/frerich/clcache/blob/ad523938504cbc6f2278c8782efad7133c4cde67/appveyor.yml#L53), I'm

1. running `unittests.py` via `py.test` and then upload the report data. A sanity `coverage report` call I added (thanks for that idea!) [shows 36% coverage](https://ci.appveyor.com/project/frerich/clcache/build/1.0.510/job/p59mt6fodcto8ys6#L143).

2. Run `coverage erase` to delete all submitted data.

2. running `integrationtests.py` via `py.test`, which internally causes multiple `coverage` calls to be done (each of which is appending to the coverage data). A sanity check via `coverage output` [shows 64% coverage](https://ci.appveyor.com/project/frerich/clcache/build/1.0.510/job/p59mt6fodcto8ys6#L193) by the integration tests.

Still, showing at the [generated codecov.io report](https://codecov.io/gh/frerich/clcache/commit/ad523938504cbc6f2278c8782efad7133c4cde67) shows only 36.56% coverage for the `clcache.py` file I'm interested in. Somehow, it appears that only the coverage of the first test case is used.

**Comment by frerich** [comment]
I figured it out - the issue was that the `py.test` execution seems to generate a `coverage.xml` file. This file however is not deleted by a `coverage erase` call. So even though the `.coverage` file got updated correctly (and thus `coverage report` showed the right data), the uploaded XML file was still the one from the first run. A simple `coverage xml` call fixed the issue. :-)
