### ISSUE TITLE
"CI Failed" false negative

### ISSUE THREAD

**Issue by duckie** [codecov/support#257]
Hello guys

I experience an odd issue with my [public github repository](https://codecov.io/gh/duckie/cpp_project_template). All of my builds get a red cross apparently called "CI failed". The log shown seems to fail on `codecov.yml` retrieval, but on nothing else.

Well, a missing `yml` should not be an error in my opinion, but it gets better. I do have a `yml`, and it does work, because my ignore rules are correctly taken in account !

Is there any real failure in those builds ? I have not the slightest idea of what I could do.

Thanks by advance for any help.

**Comment by stevepeak** [comment]
Hey @duckie the failure status comes from the CircleCI failure as seen here: https://github.com/duckie/cpp_project_template/compare/8e0b9acbcd16cc18803ca0fc191c390f32f6ede3...master

Would you like some help ignoring CircleCI detection for this project?

**Comment by duckie** [comment]
I would like to know the proper way, as I would like to now how you identified the problem.

But I will eventually fix it.

**Comment by stevepeak** [comment]
You can ignore CircleCI by adding/creating the following to your `codecov.yml` file:

```yml
codecov:
  ci:
    - "!circleci.com"
```

Thanks 👍

**Comment by duckie** [comment]
It works perfectly, thanks.
