### ISSUE TITLE
Erlang support

### ISSUE THREAD

**Issue by lpgauth** [codecov/support#26]
Hi, it would be great to add support for Erlang. I'm happy to help if you have questions.

Thanks

**Comment by stevepeak** [comment]
Hey we would love to support Erlang. Could you help me? I need:

1. Example coverage output file, so I can parse it server side
2. An example on how to produce the file at [codecov/example-erlang](https://github.com/codecov/example-erlang). 
  - I can add you to our organization to contribute it if you'd like :)

**Comment by lpgauth** [comment]
Hi, that's great. I'll get back to you this week with answers.

**Comment by stevepeak** [comment]
@lpgauth thank you! I look forward to it :+1:

**Comment by manuel-rubio** [comment]
Hi, it's possible to use cobertura compatible XML files in Erlang using this as a dependency:

https://github.com/idubrov/covertool

I used to add it to my Jenkins projects and works very well.

**Comment by stevepeak** [comment]
@manuel-rubio thank you for this awesome find! Do you have an example repository that I can checkout using this? Just so I can test against it. I'd like to add this covertool directly into the [bash uploader](https://github.com/codecov/codecov-bash) to make the process really simple for customers.

**Comment by manuel-rubio** [comment]
I was checking a personal project... https://github.com/altenwald/ephp (branch `codecov`), the changes I had to do:

```erlang
    %% rebar.config - deps section
    %% cobertura.xml export dependency
    {covertool,".*", {git, "https://github.com/altenwald/covertool.git", master}},
    {ct_tools, ".*", {git, "git://github.com/garazdawi/cth_tools.git", master}}
```

And later, in the general section, in the same file:

```erlang
{cover_enabled          , true}.
{cover_print_enabled    , true}.
{cover_export_enabled   , true}.

{plugins, [rebar_covertool]}.
{covertool_eunit, {".eunit/eunit.coverdata", "coverage.xml"}}.
```

That generates the files:

```
$ ls .eunit/*.xml *.xml
.eunit/TEST-ephp.xml              .eunit/TEST-ephp_interpr.xml      .eunit/TEST-ephp_lib_vars.xml
.eunit/TEST-ephp_class.xml        .eunit/TEST-ephp_lib_array.xml    .eunit/TEST-ephp_output.xml
.eunit/TEST-ephp_code_test.xml    .eunit/TEST-ephp_lib_control.xml  .eunit/TEST-ephp_parser.xml
.eunit/TEST-ephp_config.xml       .eunit/TEST-ephp_lib_date.xml     .eunit/TEST-ephp_parser_test.xml
.eunit/TEST-ephp_const.xml        .eunit/TEST-ephp_lib_file.xml     .eunit/TEST-ephp_shutdown.xml
.eunit/TEST-ephp_context.xml      .eunit/TEST-ephp_lib_func.xml     .eunit/TEST-ephp_test.xml
.eunit/TEST-ephp_context_test.xml .eunit/TEST-ephp_lib_info.xml     .eunit/TEST-ephp_util.xml
.eunit/TEST-ephp_error.xml        .eunit/TEST-ephp_lib_misc.xml     .eunit/TEST-ephp_vars.xml
.eunit/TEST-ephp_func.xml         .eunit/TEST-ephp_lib_ob.xml       coverage.xml
.eunit/TEST-ephp_include.xml      .eunit/TEST-ephp_lib_string.xml
```

You can download the project, and build it running `make test` to obtain those files (I recommend use Erlang/OTP R16 or 17... the dependencies are not still prepared for 18.0, I'll upload the changes for those libraries adapted to OTP 18.0 soon).

**Comment by gmr** [comment]
Here's a working implementation:
 - https://codecov.io/github/gmr/urilib
 - https://github.com/gmr/urilib

I cheated a little by including the covertool binary in my git repo - but it works just fine: https://github.com/gmr/urilib/blob/master/.travis.yml

**Comment by stevepeak** [comment]
@gmr would you be able to contribute an example repository at https://github.com/codecov/example-erlang?

**Comment by gmr** [comment]
Sure

**Comment by Pouriya-Jahanbakhsh** [comment]
Hello. I'm here to help. I know that  we can generate coverage details using well known erlang Test frameworks and dont need new dependencies and according to your docs we can have code coverage by adding 2 linest in .travis.yml. So how can i help ?

**Comment by tsloughter** [comment]
I'm a little confused from the examples. Does it have to be run through `covertool` first to generate cobertura compatible xml or not?

**Comment by tsloughter** [comment]
Ok, looks like you do. I've been updating the covertool rebar3 plugin to have better support and updating its readme.
