### ISSUE TITLE
Can't disable comments in pull-requests

### ISSUE THREAD

**Issue by rickmzp** [codecov/support#260]
We are trying to disable comments in pull requests, but the `comment: false` flag doesn't seem to have an effect.

https://gist.github.com/rickmzp/ebac4a3fbc4f919cf31de5e929aa4b18

We are following the docs at https://github.com/codecov/support/wiki/codecov.yml

Any ideas how we can turn it off? Thanks!

**Comment by stevepeak** [comment]
This config looks good! What is an owner/repo and PR number that a comment posted after adding this yaml config?

**Comment by stevepeak** [comment]
Continuing conversation in Intercom 👍

**Comment by waltflanagan** [comment]
@stevepeak Our team is also running into this issue.  Was a resolution found?

**Comment by stevepeak** [comment]
Hey @waltflanagan what is a project owner/repo that got a comment? I can review your setup. Thanks!

**Comment by waltflanagan** [comment]
https://codecov.io/gh/food52/food52 and the branch is `ReallyTUrnOffCodeCovComments` (yes that is a capital U that I typo'd while making the branch)

**Comment by rhysd** [comment]
I'm also facing this.

Config: https://github.com/vim-jp/vital.vim/blob/master/.codecov.yml
Comment: https://github.com/vim-jp/vital.vim/pull/526#issuecomment-352165304
