### ISSUE TITLE
Pull request commit status no longer updates

### ISSUE THREAD

**Issue by mpavlov** [codecov/support#261]
Opening a Pull Request on Gihub Enterprise results in the same Codecov comment post as usual, but the commit status is no longer updated.

The Codecov UI logs at `https://<myhostname>/ghe/<myorg>/<myrepo>/commit/b24c79c271ebe3f79e136137f5a6b829f5a71cd0/builds` include:
```
2016-07-20T13:55:52-04:00 notify  POST /repos/<myorg>/<myrepo>/statuses/b24c79c271ebe3f79e136137f5a6b829f5a71cd0 bot=codecov code=404  
      {"message":"Not Found","documentation_url":"https://developer.github.com/enterprise/2.6/v3"} 
```

Github responds with 404 when trying to update the commit status. This may be caused by Codecov not sending authentication information with the request. This is distinct from sending incorrect authentication (returns 401) and sending correct authentication with incorrect body (returns 400).

Codecov Enterprise v4.0.5 (5427ecb)

**Comment by stevepeak** [comment]
Hey @mpavlov can you re-login with the bot account to make sure it has a valid access_token. This typically fixes the issue.

**Comment by mpavlov** [comment]
Thanks for the suggestion.

I couldn't re-login with user `codecov` since I'm not a service admin for either Github or Codecov. Asking an admin for help is complicated since we're a big org across many time zones, and admins probably shouldn't get involved in testing cycles anyway.

However, I re-added the github user `codecov` to the repo as collaborator and that seems to have fixed it. Confusing. :|

**Comment by stevepeak** [comment]
Nice! So it appears that the user was not properly authorized to that project afterall. Thank you for the update!

> PS Just had a chat with GH staff and they are building a better application linking process to avoid issues just like this 👍
