### ISSUE TITLE
Merge commits aren't detected

### ISSUE THREAD

**Issue by wilzbach** [codecov/support#263]
Digging up the root for https://github.com/codecov/browser-extension/issues/22, I found that you have hard-coded how to detect merges:

```bash
  mc=$(git log -1 --pretty=%B 2>/dev/null | tr -d '[[:space:]]' || true)
  if [[ "$mc" =~ ^Merge[[:space:]][a-z0-9]{40}[[:space:]]into[[:space:]][a-z0-9]{40}$ ]];
  then
    # Merge xxx into yyy
    say "    Fixing merge commit sha"
```

If we consider a typical merge commit, `git log -1 --pretty=%B` will yield the following.

```
Merge pull request #4673 from wilzbach/fix_16331

Fix issue 16331 - std.container.array should allow uncomparable values
````

and further with spaces removed:

```
Mergepullrequest#4673fromwilzbach/fix_16331Fixissue16331-std.container.arrayshouldallowuncomparablevalues                                                                                       
```

Obviously this doesn't match the regex.

**Comment by stevepeak** [comment]
The intended purpose of the pattern here is to catch commits like https://github.com/dlang/phobos/commit/dbabeafac3e2a7381132dda1f305bc8e7e3fd2d5 which have a message of `Merge 5e8575d... into 6db08d3...`

This other commit message, `Merge pull request` is a seperate concern and needs to be addressed accordingly. The tricky thing about these commits messages is that we must use this process to determin the "actual" commit: https://github.com/codecov/codecov-bash/commit/923daecf2464a6a008786c4332b8ebc6a64bd0f2

We are experimenting with this pattern.

**Comment by stevepeak** [comment]
## Wrong
```json
# curl https://api.travis-ci.org/jobs/148099916 -H 'Accept: application/vnd.travis-ci.2+json' -H 'User-Agent: localhost' | grep message

"message": "Updated changelog",  # WRONG
```

## Correct
```
# curl https://api.github.com/repos/dlang/phobos/commits/dbabeafac3e2a7381132dda1f305bc8e7e3fd2d5 | grep message

"message": "Merge 5e8575dcac7e9ed220b34301028c11b5ffc1f4d1 into 6db08d3dadb007d930a4042a6140ca4fb22ea540", 
```

-----

The issue here was that we were looking at the Travis API `commit.message` for the merge commit message and skipping Github, because we assumed Travis would report the merge commit message.

Now Codecov will still check Travis but then check Github as well.

**Comment by stevepeak** [comment]
Deploying today. Thanks!

**Comment by wilzbach** [comment]
> Now Codecov will still check Travis but then check Github as well.

I don't know how many IPs the Travis workers share, but isn't it possible to run into rate limitations of the Github API?

> Deploying today. Thanks!

I can confirm [it's working](https://github.com/dlang/phobos/pull/4693/files) - thanks a lot :)

**Comment by stevepeak** [comment]
> I don't know how many IPs the Travis workers share, but isn't it possible to run into rate limitations of the Github API?

We check through the commit status api, rate-limit has never been an issue 👍

**Comment by stevepeak** [comment]
PS. the entire process will change soon. We are still investigating this article http://docs.codecov.io/docs/merge-commits
