### ISSUE TITLE
Comment only if coverage diff contains misses

### ISSUE THREAD

**Issue by wilzbach** [codecov/support#264]
Hey there,

I still very happy with CodeCov :), but here comes a feature request that I think would be handy for many repositories as it avoids a lot of unnecessary mails.

I have seen at #192 that one can add  `comments: false` to the repo, but what I would love to have is CodeCov only comment if there's something to report, i.e. only if the PR introduced _misses_. Of course if there's already a CodeCov comment, it should be updated to reflect new updates that might fix the _coverage misses_.

**Comment by stevepeak** [comment]
Awesome idea and not hard to pull off. It would be under a new config:

```yaml
comment:
  require_change: yes  # default no
```

**Comment by wilzbach** [comment]
> have a better key name? Feel free to suggest one

Hmm e.g. `needs_change`, `needs_difference`, `avoid_no_change_comments`, but `require_change` is already a good name ;-)

**Comment by stevepeak** [comment]
In order to not post comment (a) no tracked lines adjusted and (b) coverage is not affected by pr.

In the pipeline for deploy :)
