### ISSUE TITLE
Support matrix build

### ISSUE THREAD

**Issue by KostyaSha** [codecov/support#266]
Travis allows to have matrix runs, would be cool to have ability upload multiple test run results from matrix runs.

**Comment by stevepeak** [comment]
Codecov supports build matric completely, no setup required. We merge reports seamlessly into one coherent report. Checkout https://codecov.io/gh/pyca/cryptography/ for example

Are you having any issues with this process?

**Comment by KostyaSha** [comment]
Will it work for maven and gcov that run integration tests against different service for the same code lines?

**Comment by KostyaSha** [comment]
> e merge reports seamlessly into one coherent report.

Matched by commit? Where to read about?

**Comment by stevepeak** [comment]
> Will it work for maven and gcov that run integration tests against different service for the same code lines?

Yes 👍  

> Matched by commit?

Yes, by commit. You can upload from multiple CI, builds and languages to a single commit sha. Maybe this will help https://codecov.io/docs#multilingual
