### ISSUE TITLE
coverage graph does not display unified coverage

### ISSUE THREAD

**Issue by zbeekman** [codecov/support#27]
Check out the coverage graph below, and not the most recent commit, and a previous commit have coverage shown around %70:
![codecov.io](http://codecov.io/github/jacobwilliams/json-fortran/branch.svg?branch=master) 

However, if you look at the unified coverage [here](https://codecov.io/github/jacobwilliams/json-fortran) you’ll see that the graph is pulling those ~70% values from one of the travis jobs and is not showing unified coverage info.

**Comment by stevepeak** [comment]
I've deployed a fix that is related to PR builds being included in these charts. This may have fixed this specific issue. I'll be looking into it more as this recent deploy matures. HTanks!

**Comment by zbeekman** [comment]
Sweet! Looks fixed now
