### ISSUE TITLE
Don't show `tree` table when there is no coverage difference

### ISSUE THREAD

**Issue by wilzbach** [codecov/support#270]
As an alpha tester of the new `tree` feature introduced in #176, I think it would be nice if the table would be hidden if there is (a) no coverage report found or (b) no coverage difference reported, i.e. don't show the table if it's empty ;-)

![image](https://cloud.githubusercontent.com/assets/4370550/17456638/0790ea5a-5bdf-11e6-8640-29d461a0ce83.png)

**Comment by stevepeak** [comment]
🎉 👍 Thank you
