### ISSUE TITLE
Precision in the settings isn't ackknowledged

### ISSUE THREAD

**Issue by wilzbach** [codecov/support#271]
The precision setting in the `codecov.yml` doesn't seem to be acknowledged, e.g. for

```
coverage:
  precision: 4
```

Expected behavior:

Report with `%.4f`, e.g. `88.1234`

Observed behavior:

![image](https://cloud.githubusercontent.com/assets/4370550/17457545/45d96000-5bfb-11e6-9e78-de23f23ed30c.png)

![image](https://cloud.githubusercontent.com/assets/4370550/17457547/4f8ebad2-5bfb-11e6-9cf2-0752604ce386.png)

**Comment by stevepeak** [comment]
@wilzbach looks like the yaml location did not update from the old location. It should pick this up on your next commit properly.

**Comment by stevepeak** [comment]
Belated close. Fixed and deployed.
