### ISSUE TITLE
Allow user-defined service name for manual setup

### ISSUE THREAD

**Issue by peterjc** [codecov/support#273]
As a spin out from #268, I would like to be able to pass CodeCov results for a user-defined generic Continuous Integration system (e.g. a currently unsupported system like BuildBot #268, or an in-house bespoke cron-tab based test framework).

This would be a combination of environment variables (e.g. `$CODECOV_NAME=BuildBot`) and/or command line switches (e.g. `--name BuildBot` or `-n "Cron Tab"`), extending the options:
- `--commit` or `-c` or detected from `git` or `hg` directly
- `--branch` or `-b` or detected from `git` or `hg` directly
- `--token` or `-t` or `$CODEDOC_TOKEN`
- `--slug` or `-r` or `$CODECOV_SLUG`
- `--env` or `-e` or `$CODECOV_ENV`
- etc

Currently using the fallback system results in "Untitled" builds shown on CodeCov.

**Comment by peterjc** [comment]
This largely overlaps with https://github.com/codecov/codecov-python/issues/68 filed against the codecov-python repository.

**Comment by stevepeak** [comment]
Thank you for the suggestion. Buildbot will be added to our backend (with an icon). I'll look into including this issue in our next hack.

Love the `-n "Cron Tab"` that's real cool 👍

**Comment by stevepeak** [comment]
Deploying soon 👍 

e.g.,
```
bash <(curl -s https://codecov.io/bash) -n "Cron Tab"

bash <(curl -s https://codecov.io/bash) -n "Nightly Build"
```
