### ISSUE TITLE
Hiding/preventing duplicate coverage uploads?

### ISSUE THREAD

**Issue by peterjc** [codecov/support#274]
Continuous integration platforms like TravisCI etc should run the tests once for each commit (leaving aside branches and pull requests etc), but there can be multiple test runs ("builds") for each commit (e.g. different versions of Python) thus multiple coverage reports. CodeCov does a great job of merging multiple coverage reports for each commit, and you can view each upload under the "builds" tab.

However, systems like Buildbot (#268) or a hypothetical in house cron-tab based system (#273) take a different approach. Here the tests are run on a scheduled basis, typically overnight. This means many commits never get tested, and when there is a lull in development the same commit gets re-tested night after night.

Right now I worry that will lead to more (practically identical) coverage reports being uploaded to CodeCov, giving an overly busy "builds" tab. Note I would expect some slight variation between test runs (e.g. stochastic methods), and sometimes more dramatic changes (e.g. dependency updated).

(You might see this on a small scale with systems like TravisCI where the user can request a test be repeated via the web UI)

My suggestion is to discard duplicate builds for the same commit - my criteria would be matching tags (commit, branch, service name, ``$CODECOV_ENV`` variables, etc), and perhaps identical uploaded coverage report (e.g. compare the hash of the ``coverage.xml`` files).

**Comment by stevepeak** [comment]
Thank you @peterjc for the suggestion. Adding nightly builds and cron builds to Codecov is in our roadmap. We will need to come back here to discuss how to pull this off properly.

**Comment by stevepeak** [comment]
We have successfully added the concept of nightly builds to Codecov. This is not live yet, but in the pipeline for this weekend. Documentation can be found here: http://docs.codecov.io/docs/flags#section-hiding-builds-eg-nightly-builds

Cheers!
