### ISSUE TITLE
Provide a static branch link to the file listing

### ISSUE THREAD

**Issue by wilzbach** [codecov/support#276]
All file listing are based on one commit, e.g. 

https://codecov.io/gh/dlang/phobos/list/41a1d2bbb2b0aec221bea24d437876c52aba0652

That's usually great, but if one wants to share this link (in our case as a start for contributors to see what needs improval), they won't get the current master version. Thus maybe something like

https://codecov.io/gh/dlang/phobos/list/master

and in general

https://codecov.io/gh/dlang/phobos/list/<branch>

or 

https://codecov.io/gh/dlang/phobos/list/branch/master

which just could just lookup the lastest commit from the branch and display this information? (or for a start do a non-permanent redirect).

I know there's the dashboard, but especially if you work with multiple branches this could be handy.

**Comment by stevepeak** [comment]
https://codecov.io/gh/dlang/phobos/list/master should always pick the tip of master... Is that not working?

**Comment by wilzbach** [comment]
Oh nice, I just didn't know that one existed. Thanks
