### ISSUE TITLE
Specifying different root breaks web view

### ISSUE THREAD

**Issue by ThePadawan** [codecov/support#279]
On Commit 4f3c618524978a5cce4b40030215dcf7f325e853, I used the pip-supplied codecov-tool with the flag "--root src" to strip the leading "src/" from the web view. This worked and led to https://codecov.io/gh/ThePadawan/the_diary_peon/tree/4f3c618524978a5cce4b40030215dcf7f325e853. However, clicking on any file leads to a 404 since the "src/" is not added back in when trying to retrieve the file from Github.

I have reverted that change in the following commit (https://codecov.io/gh/ThePadawan/the_diary_peon/tree/fd84f8bb7c6200c19e4373833a61432d8feeb386), where Github linkage works again.

This might be related to https://github.com/codecov/support/issues/182.

**Comment by stevepeak** [comment]
Checkout https://github.com/ThePadawan/the_diary_peon/pull/1
Thanks!

**Comment by ThePadawan** [comment]
PR merged, although I had to flip the direction fo the fix (/src => / instead of / => /src) to get the output I wanted on codecov ;).
