### ISSUE TITLE
.codecov.yml not being used

### ISSUE THREAD

**Issue by peterjc** [codecov/support#280]
I added a ``.codecov.yml`` file to our master branch recently: https://github.com/biopython/biopython/commit/a20258a36fca5a3521b708128e0199f1dfbed4ad

This commit has been run on TravisCI and appears on CodeCov: https://codecov.io/gh/biopython/biopython/commit/a20258a36fca5a3521b708128e0199f1dfbed4ad

This YAML file was intended to exclude the ``Tests/`` folder from the coverage reports, but it has not taken effect. According to https://codecov.io/gh/biopython/biopython/settings/yaml 

> No codecov.yml file found on master yet.
>
> Already added one? Great! This message will be removed upon the next upload to master branch.

Is the leading dot a problem? I used this because the FAQ at https://github.com/codecov/support/wiki/Codecov-Yaml says that is supported.

**Comment by stevepeak** [comment]
Please see https://github.com/biopython/biopython/commit/a20258a36fca5a3521b708128e0199f1dfbed4ad#commitcomment-18644876 Thanks!

**Comment by peterjc** [comment]
Hopefully https://github.com/biopython/biopython/commit/208a2d8466f4f978d2e876a2f578afebf840e26c fixes this, thank you.

But could CodeCov report "Invalid YAML file" or something in this situation?

**Comment by stevepeak** [comment]
Certainly, the yaml is responsible for the ignore and failed because of the parsing.

**Comment by peterjc** [comment]
The fixed ``.codecov.yml`` file is now working, thank you. e.g. https://codecov.io/gh/biopython/biopython/tree/208a2d8466f4f978d2e876a2f578afebf840e26c does not show the ``Tests/`` folder.

However, https://codecov.io/gh/biopython/biopython/settings/yaml still says:

> No codecov.yml file found on master yet.
>
> Already added one? Great! This message will be removed upon the next upload to master branch.

Is this part of CodeCov not checking the ``.codecov.yml`` alternative filename?

**Comment by stevepeak** [comment]
Codecov will detect the file name during in the upload process and pass the location in the upload command. [See here](https://github.com/codecov/codecov-bash/blob/66828c28c24ddb28755a2134369c61d4b865f086/codecov#L573)

**Comment by peterjc** [comment]
Yes, its clear the upload side of things is fine with the leading dot - but the settings page is currently confusing because it says no codecov.yml file was found on the master branch.

**Comment by stevepeak** [comment]
That is a UI issue. I'll fix to be the last known location of the yaml.

Thanks!
