### ISSUE TITLE
Broken link on YAML settings page

### ISSUE THREAD

**Issue by peterjc** [codecov/support#281]
Go to the YAML setting page for a repository used on CodeCov, e.g. https://codecov.io/gh/biopython/biopython/settings/yaml

In the footer of the page is this text:

> Learn more about why we use a yaml file for team and project settings.

This is a URL linking to https://github.com/codecov/support/wiki/codecov.yml which now gives a 404 page.

Suggest changing URL to https://github.com/codecov/support/wiki/Codecov-Yaml and/or creating a wiki redirection?

**Comment by stevepeak** [comment]
Thank you @peterjc for pointing this out. I'll fix that link 👍
