### ISSUE TITLE
Reports not being shown for my project

### ISSUE THREAD

**Issue by crisfervil** [codecov/support#282]
Hi, 

For some reason, the coverage report for my project stopped working.

This is the latest coverage link and the message that I get when I try to access to it:

https://codecov.io/gh/crisfervil/DynamicsNode/commit/af4a0e92632b2394814e743be8bff28e35087947

![image](https://cloud.githubusercontent.com/assets/7902357/17671434/e1bf4ec0-630e-11e6-8890-c9a713a5b05f.png)

This is the latest Travis-CI building log saying that the coverage report was executed and uploaded correctly
https://travis-ci.org/crisfervil/DynamicsNode/builds/152424375

The project link in github: https://github.com/crisfervil/DynamicsNode

Any ideas about what may be going wrong?

Thanks,

**Comment by stevepeak** [comment]
Hey @crisfervil looks like the reports are not being mapped back from JS to TS https://github.com/codecov/example-typescript

**Comment by crisfervil** [comment]
Adding the ```--sourcemap``` flag when running the typescript compilation solves the problem.

Thanks for your help
