### ISSUE TITLE
Codecov cannot find `.codecov.yml` or `.github/codecov.yml`

### ISSUE THREAD

**Issue by ngokevin** [codecov/support#283]
I read in the support documentation that this configuration file can live anywhere in the repository. Yet after placing the config in several locations and as a hidden file, the Settings page says `No Codecov YAML file found on master yet.`

**Comment by stevepeak** [comment]
Hey @ngokevin What is the project owner/repo name? What uploading utility are you using?

**Comment by ngokevin** [comment]
It was previously on `aframevr/aframe`, but I moved it to `codecov.yml` to get it working.

We are using Travis CI. 

Check out https://github.com/aframevr/aframe/pull/1812 where I have disabled comments using a config in `.github/codecov.yml`, but the bot still comments.

**Comment by stevepeak** [comment]
I don't quite understand the context of `.github/codecov.yml` when the yml, as of latest on master is https://github.com/aframevr/aframe/blob/master/codecov.yml

**Comment by ngokevin** [comment]
I have since moved it to https://github.com/aframevr/aframe/blob/master/codecov.yml since putting it in `.github/codecov.yml` was not working. The PR shows it initially in the `.github` folder.

**Comment by stevepeak** [comment]
It should work in the `.github/codecov.yml` location. I've had a couple support requests on issues updating our internal cache when the yaml file changes location. We will investigate this more.

In the meantime, I can update the cached path if you would l like the file in a different location. Thanks!

**Comment by stevepeak** [comment]
So long as the yaml is checked into git it can be anywhere in the project under the title `.?codecov.ya?ml`. At the moment the bash uploader is required to detect these paths. Please contact support to change the path if not using the bash uploader.
