### ISSUE TITLE
Complexity

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#287]
---

> Please [join our Codecov Slack](mailto:steve@codecov.io) room for ABCs (Ask, Beta, Contribute) 👍 

---

Add code complexity to Codecov. 
## Overview
- Design UI
- Collect data
- Determine languages that provide complexity data
  - Java, PHP
- Generate [Cyclomatic Complexity](http://www.eclemma.org/jacoco/trunk/doc/counters.html) if available on other languages

<img width="905" alt="screen shot 2016-09-14 at 10 13 10 am" src="https://cloud.githubusercontent.com/assets/2041757/18518459/1765100c-7a6e-11e6-9f9d-d55a33e578a5.png">

> CC https://github.com/codecov/support/issues/265

**Comment by rlee287** [comment]
[Radon](https://pypi.python.org/pypi/radon) can calculate complexity for python, if this helps.

**Comment by stevepeak** [comment]
<img width="905" alt="screen shot 2016-09-14 at 10 13 10 am" src="https://cloud.githubusercontent.com/assets/2041757/18518459/1765100c-7a6e-11e6-9f9d-d55a33e578a5.png">

**Comment by stevepeak** [comment]
@rlee287 Nice find! I'll look into ways to include this complexity for python. The UI images above would mention these grades provided by radon.

**Comment by stevepeak** [comment]
> CC https://github.com/codecov/support/issues/265

**Comment by rakhimov** [comment]
[Lizard](https://github.com/terryin/lizard) supports multiple languages with various metrics.

**Comment by stevepeak** [comment]
@rakhimov this is super cool! I'll have to take a look at more. Thank you for pointing it out.

**Comment by stevepeak** [comment]
Coming out in next release for Java, PHP and C#! Thank you 👍

**Comment by stevepeak** [comment]
@rakhimov What language do you use Lizard on?

**Comment by rakhimov** [comment]
@stevepeak I mostly use it for C++ and contribute fixes for C++ support.
Actually, @terryyin is the project owner and very responsive for interesting-(feature|language) requests.

**Comment by terryyin** [comment]
Which language are we talking about here?

**Comment by rakhimov** [comment]
@terryyin if you look at his supported (> 20) [languages](http://docs.codecov.io/docs/supported-languages),
most of them are imperative and some functional.
Actually, I am not sure if @stevepeak is asking because he is already using Lizard
for the upcoming 3 languages or if he's asking in general.

**Comment by stevepeak** [comment]
@rakhimov right 👍 

To be clear: PHP, Java (via Jacoco) and C# (via OpenCover) include complexity metrics in the coverage reports. Codecov will start collecting this data and show it off across the UI and pr comments.

The use of Lizard (future) is still being reviewed. The likely technique to implement would be to add Lizard to the Codecov Bash uploader, which will call lizard and upload the report with the coverage files. We will post back to this thread when Lizard is ready to beta.
