### ISSUE TITLE
Coverage chart not showing SLOC axis on right

### ISSUE THREAD

**Issue by rlee287** [codecov/support#289]
The coverage chart displays a plotline for the coverage percentage and the lines of code in the project. However, the axis on the right that shows the lines of code is not showing in the plots. Without an axis, the curve showing the lines of code becomes useless.

The pictures below show this issue in the repo https://codecov.io/gh/rlee287/pyautoupdate.

This is a screenshot of the bug (from Firefox, but problem also present in Chrome):
![codecov-screenshot](https://cloud.githubusercontent.com/assets/14067959/18408377/f2b49252-76e2-11e6-95ac-03298c45c0cb.PNG)
This is the downloaded `coverage-chart.png`:
![coverage-chart](https://cloud.githubusercontent.com/assets/14067959/18408382/febcd320-76e2-11e6-8f9c-3533ac810d5c.png)

**Comment by stevepeak** [comment]
Thank you @rlee287 for pointing this out. We will be changing this chart in the near future with new features. For now, we will leave out the sloc axis and await the upcoming changes

**Comment by stevepeak** [comment]
Lines are removed from the charts in new releases. Thank you!
