### ISSUE TITLE
GitHub status not always reported for pull requests

### ISSUE THREAD

**Issue by jeppefrandsen** [codecov/support#290]
We have seen that the GitHub status is not always reported lately (e.g. pull request 431 on ase). Has there been any changes in this area? The coverage reports have been uploaded accordingly to the CodeCov bash script. Thanks.

**Comment by stevepeak** [comment]
Typically the issue is due to the bot losing access to the project. You can review this in the build logs on Codecov when viewing a commit click on the tab "builds".

http://docs.codecov.io/docs/team-bot

**Comment by jeppefrandsen** [comment]
Hi Steve,

Thanks. I actually see that upload to S3 is failing in one case:

    -> Pinging Codecov
    -> Uploading to S3 https://codecov.s3.amazonaws.com
    X> Failed to upload to S3
    -> Uploading to Codecov

Will try to look into the other cases as well.

**Comment by jeppefrandsen** [comment]
Hi Steve,

Any news regarding the big delays? Thanks.

Kind Regards,
Jeppe

**Comment by stevepeak** [comment]
@jeppefrandsen can you ping me the project name. There are no open issues of this occurring in other projects and I believe it is isolated to yours. Thank you!

**Comment by jeppefrandsen** [comment]
The project is called bang-olufsen/ase. Thanks.

**Comment by stevepeak** [comment]
@jeppefrandsen I reviewed a couple commits and I'm seeing successful statuses and comments posted. Do you have a specific commit I may review?

**Comment by jeppefrandsen** [comment]
Can you check this commit: 9ca2089f8edb90a11ce227f21e5b258854be4e8a (part of pull request #475). Here status is not reported in the pull request

**Comment by stevepeak** [comment]
The issue was the base commit did no process correctly: https://codecov.io/gh/bang-olufsen/ase/commits/5c04a34/builds

This restarted the [build job here](https://codecov.io/gh/bang-olufsen/ase/commits/9ca2089f8edb90a11ce227f21e5b258854be4e8a/builds) as it was waiting for the base commit to complete processing.

This may be a fluke... have you seen it repeat?

**Comment by jeppefrandsen** [comment]
We have seen it some times now but will check that the base commit is processed correctly the next time. I will close the issue for now. 

Thank you very much once again!

**Comment by donatello** [comment]
Also affected by this problem - e.g. https://github.com/minio/minio/pull/5295

The build logs on codecov don't seem to indicate that anything is wrong - https://codecov.io/gh/minio/minio/commits/df58a72/builds - is this issue being looked into?
