### ISSUE TITLE
Delete old data

### ISSUE THREAD

**Issue by anderspitman** [codecov/support#291]
When getting coverage via codecov set up it often takes some trial and error to get things working the way you want, for example excluding certain directories from being processed or uploaded. However, the behavior seems to be to just append new data to previous uploads, even you have since excluded directories and no longer want them shown. Is there a way to delete the earlier uploaded data?

**Comment by na-gupta** [comment]
I have the same issue. Code that has now been excluded still shows up in the reports and is still included in the coverage % calculation.

**Comment by stevepeak** [comment]
We have a delete commit endpoint now: https://docs.codecov.io/v4.3.0/reference#section-delete-a-commit

Thank you!
