### ISSUE TITLE
path status reported even though it is disabled

### ISSUE THREAD

**Issue by xh3b4sd** [codecov/support#294]
My `codecov.yml` looks as follows.

```
$ curl --data-binary @codecov.yml https://codecov.io/validate
Valid!

{
  "comment": {
    "layout": "header"
  },
  "coverage": {
    "precision": 2,
    "round": "nearest",
    "status": {
      "project": {
        "default": {
          "target": "auto",
          "threshold": 10.0
        }
      },
      "patch": false,
      "changes": false
    }
  }
}
```

I disabled the path status report some weeks ago. This was working properly for quite some time. Now the patch status is reported. I expect this to be a bug. I couldn't find anything I am doing wron in the documentation. This is a screenshot of [the pull request in which I experience the issue](https://github.com/xh3b4sd/anna/pull/217). 

<img width="793" alt="screen shot 2016-09-18 at 23 16 39" src="https://cloud.githubusercontent.com/assets/552769/18619174/ffd9c938-7df5-11e6-9326-51d4360b2e76.png">

**Comment by stevepeak** [comment]
Hey @xh3b4sd thank you for pointing this out. Looks like it has been resolved in this PR since, but I'll investigate more.

**Comment by stevepeak** [comment]
I think this was a yaml that was cached wrong. What's odd is that all the logs server side state it was disabled and did not post. If this has repeated please reopen issue. Thank you for your patience and help 😄

**Comment by xh3b4sd** [comment]
In https://github.com/xh3b4sd/anna/pull/228 I just experienced another anomaly. Usually the pull request comment looks as follows. 

<img width="794" alt="screen shot 2016-09-24 at 15 31 01" src="https://cloud.githubusercontent.com/assets/552769/18808787/09c05172-826c-11e6-9e8b-86e832465833.png">

The one made yesterday evening looks like this. 

<img width="786" alt="screen shot 2016-09-24 at 15 31 15" src="https://cloud.githubusercontent.com/assets/552769/18808792/1c6e436a-826c-11e6-91ac-f579dca36cd4.png">

I am still using the configuration as shown above. It explicitly states to only show the header.

**Comment by xh3b4sd** [comment]
I would reopen the issue. I am not allowed to do that on my own though.

**Comment by xh3b4sd** [comment]
I just saw the patch status is reported again in https://github.com/xh3b4sd/anna/pull/228, which is definitely not desired. 

<img width="792" alt="screen shot 2016-09-24 at 15 34 45" src="https://cloud.githubusercontent.com/assets/552769/18808808/7fca7398-826c-11e6-8930-d3e7147d35c5.png">

**Comment by stevepeak** [comment]
@xh3b4sd thank you so much for your patience and follow through. I'm tracking this down and reviewing our caching policy.

**Comment by stevepeak** [comment]
Assumed fixed. Thank you
