### ISSUE TITLE
Duplicating coverage on github commits

### ISSUE THREAD

**Issue by phlax** [codecov/support#295]
Hi there

Im seeing endlessly duplicating coverage stats on commits if i wiggle my mouse nearby

this is on firefox 45.3

![codecov-integration](https://cloud.githubusercontent.com/assets/454682/18685683/ff67a20a-7f70-11e6-974d-27c26d11690e.png)

**Comment by stevepeak** [comment]
Wow! Sorry about that I'll review and fix asap.
