### ISSUE TITLE
Incorrect relative timestamps in GUI

### ISSUE THREAD

**Issue by carusology** [codecov/support#299]
Within the CodeCov.io GUI, my commits are getting displayed with relative timestamps that say I checked in my code about 7 hours before I did.

This seems related to my timezone. My timezone (PDT) is -7 hours from UTC, and that is encoded in my GitLab commits. This makes me think that CodeCov is using the current UTC timestamp minus my commit's PDT timestamp to calculate a relative timestamp without factoring in the offsets from timezones. This would explain me seeing a relative timestamp of "8 hours ago" on a commit that was made some 20-30 minutes before getting uploaded to CodeCov via my continuous integration pipeline.

Here is the screenshot of an affected relative timestamp in the GUI:
![image](https://cloud.githubusercontent.com/assets/19539318/18812686/d4ef9db6-8290-11e6-8540-2cbfc56109d7.png)

Here is the same commit from GitLab fetched via their API:
```
{
  "id":"fe7d406e674e7f7fe7a5777cf6e6604072e709eb",
  "short_id":"fe7d406e",
  "title":"Make path combination consistent across platforms for InMemoryRepository",
  "author_name":"Brian Caruso",
  "author_email":"brian@invioinc.com",
  "created_at":"2016-09-23T16:27:26.000-07:00",
  "message":"Make path combination consistent across platforms for InMemoryRepository\n",
  "parent_ids":["af84e2d7d12c86ce6122a4284179c1c8484e5212"],
  "committed_date":"2016-09-23T16:27:26.000-07:00",
  "authored_date":"2016-09-23T16:27:26.000-07:00",
  "stats":{"additions":1,"deletions":1,"total":2},
  "status":"success"
}
```

Let me know if I can help provide more data. I [tweeted about it](https://twitter.com/codecov/status/779796814165925889) too.

**Comment by stevepeak** [comment]
Hey! Thanks for reporting this. So indeed the timestamp is not respecting the `-07:00` which needs to be respected. The database currently reflects `2016-09-23 16:27:26` but should be `2016-09-23 23:27:26`

**Comment by stevepeak** [comment]
Fixed in next release 👍

**Comment by carusology** [comment]
Nice! Thanks, @stevepeak. How can I track releases of codecov?

**Comment by stevepeak** [comment]
We don't have a live feed of changes, but will start posting updates here: http://docs.codecov.io/blog
