### ISSUE TITLE
Support skipping a build

### ISSUE THREAD

**Issue by skirpichev** [codecov/support#300]
Sometimes you won't run CI tests, e.g. if PR has only documentation changes.

Travis support [this](https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build) mechanism to disable a build for a particular commit.  I hope that codecov.io will follow this convention.

**Comment by stevepeak** [comment]
Oh cool! So if the commit has `[ci skip]` Codecov should not post statutes/comments?

No problem! I can arrange this pretty quickly.

- [ ] match patterns: `(\[((ci[\s\-]?skip)|(skip[\s\-]?ci))\])`
- [ ] skip statuses
- [ ] skip comments
- [ ] mark build as `skipped` not pass/fail

@skirpichev ^^ look good to you?

**Comment by skirpichev** [comment]
I would suggest ``\[(skip ci|ci skip)\]`` egrep pattern (exact version from the travis-ci docs).  Unless there are other CI providers, which offer similar feature.

>  skip statuses, commits

yes, everything

> mark build as skipped not pass/fail

Which status will be for the master branch of the repo after merging pr with such "skipped" build?  Status of the previous (non-skipped) merge, right?  If so - it looks good for me.

**Comment by stevepeak** [comment]
> Which status will be for the master branch of the repo after merging pr with such "skipped" build? Status of the previous (non-skipped) merge, right? If so - it looks good for me.

Would be the most recent commit on master that was not skipped and passed CI.

> regex pattern

I'll look over the CI providers to confirm pattern. Thanks!
