### ISSUE TITLE
Validation endpoint not working on macOS Sierra

### ISSUE THREAD

**Issue by JohnCoates** [codecov/support#302]
I'm getting an error even when using the suggested command
````
Please validate in the following manner:
curl -X POST --data-binary @codecov.yml https://codecov.io/validate
````

![screen shot 2016-09-30 at 2 59 29 pm](https://cloud.githubusercontent.com/assets/967800/19008228/97771832-871e-11e6-9bf7-991036e2a671.png)

**Comment by stevepeak** [comment]
You need to include the `@` sign:

```diff
- curl -X POST --data-binary ./.codecov.yml https://codecov.io/validate
+ curl -X POST --data-binary @./.codecov.yml https://codecov.io/validate
```

**Comment by JohnCoates** [comment]
Oops, thanks Steve. I've never seen the `@` sign used in a command so I thought it was a placeholder.
