### ISSUE TITLE
Repository home page looking for develop branch instead of master

### ISSUE THREAD

**Issue by na-gupta** [codecov/support#305]
https://codecov.io/gh/IBM-Swift/Kitura/ shows this message: "No commits found on develop yet." This repository does not have a develop branch. The master branch does show up under https://codecov.io/gh/IBM-Swift/Kitura/branches , but for some reason, for this particular repo, it is looking for develop instead of master, which is supposed to be the default branch.

**Comment by stevepeak** [comment]
@na-gupta I can fix server side. Thank you!

**Comment by stevepeak** [comment]
All set 👍

**Comment by na-gupta** [comment]
👍 Thanks @stevepeak
