### ISSUE TITLE
The `totals` object in API responses does not always match the documented format

### ISSUE THREAD

**Issue by 0xced** [codecov/support#307]
From the [Codecov API Reference](http://docs.codecov.io/reference#totals)

> Many Codecov responses include a totals object. The format of this object is outlined below.
> **JSON**
> 
> ``` javascript
>  {
>   "totals": {
>     "c": "70.00000",  // coverage ratio
>     "f": 2,           // files count
>     "n": 10,          // lines count
>     "h": 7,           // hits count
>     "m": 2,           // missed count
>     "p": 1,           // partials count
>     "b": 3,           // branches count
>     "d": 0,           // methods count
>     "M": 0,           // messages count
>     "s": 3            // sessions count
>   }
> }
> ```

This is working fine for https://github.com/0xced/XCDYouTubeKit/commit/020a4aacb7df323947b3a092b63e7b416705bdd7:

```
$ curl -s https://codecov.io/api/gh/0xced/XCDYouTubeKit/commit/020a4aacb7df323947b3a092b63e7b416705bdd7 | jq .commit.totals
{
  "p": 0,
  "s": 2,
  "h": 515,
  "M": 0,
  "n": 545,
  "m": 30,
  "c": "94.49541",
  "b": 72,
  "d": 132,
  "f": 11
}
```

but is failing for https://github.com/AFNetworking/AFNetworking/commit/88f13053b1d1f20bf657f5c36459b87a5d317ad7 where `totals` is an array instead of the documented object:

```
$ curl -s https://codecov.io/api/gh/AFNetworking/AFNetworking/commit/88f13053b1d1f20bf657f5c36459b87a5d317ad7 | jq .commit.totals
[
  5,
  2491,
  1949,
  542,
  0,
  78.24,
  0,
  0,
  0,
  0
]
```

Any idea what’s happening here?

**Comment by 0xced** [comment]
Ping.

**Comment by stevepeak** [comment]
Hey @0xced sorry for the delay. Indeed the object is not user friendly. We are building out an API v2 that will change the structure of the totals object.

Meanwhile, I'll take a look into all our endpoints to make sure they write out as json objects and not lists.

**Comment by stevepeak** [comment]
In an upcoming release we are fixing the output of totals to be an object.

```
"totals": {
        "files": 1,
        "lines": 192,
        "hits": 118,
        "misses": 73,
        "partials": 1,
        "coverage": 61.45833,
        "branches": 49,
        "methods": 0,
        "messages": 0,
        "sessions": 1,
        "complexity": 0,
        "complexity_total": 0,
        // data below is for backwards compatibility 
        "f": 1,  // sum files
        "n": 9,  // sum lines
        "p": 2,  // sum partials
        "h": 6,  // sum hits
        "m": 1,  // sum missed
        "C": 0,  // sum changes
        "s": 1,  // sum sessions
        "b": 0,  // sum branches
        "d": 0,  // sum methods
        "M": 0,  // sum messages
        "c": 100  // coverage ratio
    }
```

**Comment by 0xced** [comment]
Is there a beta API endpoint available? Also, the [documentation](https://docs.codecov.io/reference#totals) is still referencing the old format.
