### ISSUE TITLE
Partial coverage support for reports generated by Xcode (llvm-cov)

### ISSUE THREAD

**Issue by 0xced** [codecov/support#308]
It would be nice to have partial coverage support for Swift and Objective-C.

I think it could be achievable with the llvm-cov reporting tool (which is already used by the codecov bash uploader).

By changing the current report generation from 

``` bash
xcrun llvm-cov show -instr-profile "$1" "$dest" > "$_proj_name.$_type.coverage.txt"
```

to

``` bash
xcrun llvm-cov show -use-color -instr-profile "$1" "$dest" > "$_proj_name.$_type.coverage.txt"
```

we can keep the color information (i.e. escape codes) that we see when running the command in a terminal.

Without `-use-color`:

``` objc
      1|   39|          NSArray *preferredLocalizations = [[NSBundle mainBundle] preferredLocalizations];
      0|   40|          NSString *preferredLocalization = preferredLocalizations.firstObject ?: @"en";
      0|   41|          return [NSLocale canonicalLanguageIdentifierFromString:preferredLocalization] ?: @"en";

```

With `-use-color` (&lt;ESC&gt; is the actual 0x1b escape byte):

``` objc
      1|   39|          NSArray *preferredLocalizations = [[NSBundle mainBundle] preferredLocalizations];
      0|   40|          NSString *preferredLocalization = preferredLocalizations.firstObject ?: <ESC>[0;41m@"en"<ESC>[0m;
      0|   41|          return [NSLocale canonicalLanguageIdentifierFromString:preferredLocalization] ?: <ESC>[0;41m@"en"<ESC>[0m;

```

With that information, it seems it could be pretty straightforward to implement partial coverage for reports generated with llvm-cov.

**Comment by stevepeak** [comment]
Hey @0xced sorry for the delay and thank you for the feature request.

So what you are saying is `<ESC>[0;41m....` starts a partial miss and `<ESC>[0m` ends the partial miss? If so, that is quite easy to implement and support.

**Comment by stevepeak** [comment]
@0xced could you produce an example report so I can test against it? Thank you

**Comment by stevepeak** [comment]
@0xced would you like to beta this? 

```
bash <(curl -s https://github.com/codecov/codecov-bash/blob/f81a7b47aef0fad3900e887a7ad9c96c0d12c47f/codecov)
```

**Comment by 0xced** [comment]
It did not work, I opened https://github.com/codecov/codecov-bash/pull/60 to address one issue I found.

**Comment by 0xced** [comment]
Even after fixing the [-use-color error](https://github.com/0xced/codecov-bash/commit/629b78aeb90bcaa6741dc97ed5c3daff8b63548e) (and [a small modification](https://github.com/0xced/codecov-bash/commit/ab6bec11466248315260cda9c2d7d77b6e2c03b0)), partial coverage is not working. Codecov reports [this error](https://codecov.io/gh/0xced/XCDYouTubeKit/commit/793ea425a7f303b7e3088f510e9e5c9a589a525d):
> Woops!
> There was an error processing coverage reports.

Here is the build: https://circleci.com/gh/0xced/XCDYouTubeKit/63
Here is the coverage report generated by `llvm-cov show -use-color […]`: https://63-10132053-gh.circle-artifacts.com/0/tmp/circle-artifacts.6Et6DDM/coverage/XCDYouTubeKit.framework.coverage.txt

**Comment by 0xced** [comment]
Ping.

**Comment by stevepeak** [comment]
@0xced Please use our new xcodeplist which is in the last stages of beta:

```
bash <(curl -s https://codecov.io/bash) -X xcodeplist
```

Please provide feedback on this solution which is much better than `llvm-cov`. Thanks
