### ISSUE TITLE
support .yaml files in addition to .yml

### ISSUE THREAD

**Issue by andreleblanc-wf** [codecov/support#309]
Codecov appears to only check for `codecov.yml` or `.codecov.yml`.  There is no support for the `.yaml` extension which seems to be common among most other tools that rely on a yaml configuration in the repository.  

Please support codecov.yaml

**Comment by stevepeak** [comment]
Can do! Thank you for suggesting this.

**Comment by stevepeak** [comment]
Supported in the bash uploader. Other uploader support coming soon.
