### ISSUE TITLE
Broken image instead of GitLab avatar

### ISSUE THREAD

**Issue by carusology** [codecov/support#313]
My GitLab group "invio" (the logical grouping of repositories) has an avatar. However, in CodeCov, instead of seeing that avatar, I see a broken image. Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/19539318/19742394/b7e77bc4-9b79-11e6-9a6a-67e53745142a.png)

Is there something I need to do to make it so that our avatar appears in CodeCov, or is this a bug?

**Comment by carusology** [comment]
I should note that a 403 (Forbidden) is being thrown on the page for the avatar to a CloudFront CDN. AFAIK, GitLab does not use CloudFront to host images (at least, it doesn't in its own GUI), so this seems to be on CodeCov's side of things. Here's a screenshot of the 403:

![image](https://cloud.githubusercontent.com/assets/19539318/19742541/601cf382-9b7a-11e6-9588-464fbf98972f.png)

**Comment by stevepeak** [comment]
Thanks for reporting! Will look into and fix today.

**Comment by carusology** [comment]
Catching up on an older issue, @stevepeak.

It looks like things are no longer broken, but they are still not accurate. The 403 is gone from the logs, and it looks like you updated this to be the little CodeCov monster (cute, that one) instead of the broken image.

<img width="302" alt="missingavatar" src="https://cloud.githubusercontent.com/assets/19539318/22765498/77482330-ee25-11e6-8b33-3367bd7ab01f.png">

Is this going to get updated to be the profile image from the GitLab group?

**Comment by stevepeak** [comment]
Thanks! Gitlab changed their avatar location. We'll look into a better option. Gravatar looks like the right fit.
