### ISSUE TITLE
Slow processing time

### ISSUE THREAD

**Issue by jeppefrandsen** [codecov/support#315]
We see that it takes ~20 minutes to process uploaded reports. Are we doing anything wrong?

```
  ... 
  2016-10-28T13:15:15+02:00 upload  Report archived download   
  2016-10-28T13:15:09+02:00 upload  Processed file name=coverage.info language=lcov   
  2016-10-28T13:15:08+02:00 upload  Processed file name=coverage.json language=node   
  2016-10-28T13:15:08+02:00 upload  Processed file name=ui-coverage.json language=node   
  2016-10-28T12:52:51+02:00 upload  Upload archived download
  ... 
```

**Comment by stevepeak** [comment]
Hey @jeppefrandsen thank you for expressing this. There may have been a queue of builds or a worker process that got stuck with your job prefetched. Very sorry about the delay.

**Comment by jeppefrandsen** [comment]
'-X fix' solved the issue. Thanks once again!

**Comment by jasonmp85** [comment]
20 minutes would be great. I'm seeing ≈ 1 hour. What's up with that?!?

> 2016-12-06T16:24:10-07:00 upload  GET /repos/citusdata/citus/contents/codecov.yml […]
> 2016-12-06T15:31:01-07:00  Upload accepted ci=travis build=4213.2   
> 2016-12-06T15:30:38-07:00  Upload accepted ci=travis build=4214.2   
> 2016-12-06T15:30:38-07:00  Upload accepted ci=travis build=4214.1   
> 2016-12-06T15:30:24-07:00  Upload accepted ci=travis build=4213.1

**Comment by stevepeak** [comment]
We had a huge delay just not in jobs. Everything is back to normal. Thank you for your patience :) We are experience high demand for Codecov and working hard to scale and manage accordingly.

**Comment by jasonmp85** [comment]
Ah, ok. Is this typical? Is there a way around it? I'd like to make the codecov statuses required for us to merge a pull request, but waiting an hour is a bit of a high bar.

It was actually my _first_ build after merging codecov support, so I'm fairly new and the one-hour processing time put me off (we used coveralls previously but I wanted to try codecov with this project due to the richer feature set).

**Comment by stevepeak** [comment]
@jasonmp85 it is certainly not typical at all. This delay occurs once a week for a hour at most.
