### ISSUE TITLE
Overview and bagde is not updating

### ISSUE THREAD

**Issue by cloutiertyler** [codecov/support#316]
It seems like I have the exact same issue as #286. I forced push my repo (terribly I know) and now I'm not seeing an updated overview.

https://codecov.io/gh/SwiftOnEdge/Edge

Would it be possible to fix this error?

**Comment by stevepeak** [comment]
Hey! Sorry for the delay, just had a baby 👶 🎉 

Your project seems on track. What is the latest force-push commit I can investigate? Are you able to reproduce this issue? 

Thank you!

**Comment by stevepeak** [comment]
@cloutiertyler How is this looking? Sorry for the delay. Closing because [this looks](https://codecov.io/gh/SwiftOnEdge/Edge) nice 👍

**Comment by cloutiertyler** [comment]
Yep, I was able to resolve this problem, although I can't remember what the fix was. Thanks for the help though!
