### ISSUE TITLE
patch.target and project.threshold not working?

### ISSUE THREAD

**Issue by safareli** [codecov/support#317]
Here is pr https://github.com/safareli/free/pull/32

In `#1` commit I have set:
- `threshold` to `5%` 
- `patch` to `no`
-  made such changes to which drop coverage by `4%`
- pushed it and it failed in codecov/project and in codecov/patch too when non of this should have happened

in `#2` commit i have:
- added more uncovered lines 
- now `codecov/project` should have failed but `codecov/patch` is still failing

in `#3` commit  i have:
- set `patch` `target` to `0`
- pushed and `codecov/patch` is still failing when it should have not

---

What I want is to not fail if coverage in patch is low, but fail if merging a PR will drop coverage  by more than 5%

---

Might be related #135

**Comment by safareli** [comment]
It would be nice to document this kind of stuff, as I have spend half the day trying to fix that :/

**Comment by stevepeak** [comment]
@safareli Documentation is at http://docs.codecov.io/docs/commit-status

Still reviewing all these details. Thanks

**Comment by stevepeak** [comment]
The system still thinks `codecov.yml` is the file location, not `.codecov.yml` I'll update that now. Please send a new commit through CI to Codecov. Thanks

**Comment by safareli** [comment]
also `behavior`  of comments was set to `new` in first commit but as you can see new comments are not made

**Comment by stevepeak** [comment]
That issue is also based on the yaml name. :)

**Comment by safareli** [comment]
Fixed, Thanks!
