### ISSUE TITLE
Gitlab Branch Detection

### ISSUE THREAD

**Issue by thornbill** [codecov/support#319]
Codecov is showing all commits in my Gitlab repository as being on the `master` branch.
https://codecov.io/gl/thornbill/node-password-store/commits

Also looking at the "Branches" tab, only shows the `master` branch.
https://codecov.io/gl/thornbill/node-password-store/branches

I am using Gitlab CI to run my coverage reports. My Gitlab CI yaml file is available for reference here.
https://gitlab.com/thornbill/node-password-store/blob/master/.gitlab-ci.yml

This also causes my badge to report the incorrect coverage information, so any help would be greatly appreciated!

**Comment by billt2006** [comment]
After doing a bit more digging, it looks like the issue is with the way that the `codecov-node` tool detects the Gitlab CI.

I checked the value of `CI_SERVER_NAME` in a build and it seems to be "Gitlab" instead of "Gitlab CI" that is expected here.
https://github.com/codecov/codecov-node/blob/master/lib/services/gitlab.js#L7

Would you like me to submit a pull request to add support for "Gitlab"?

**Comment by billt2006** [comment]
Actually it looks like all versions of Gitlab CI should support a `GITLAB_CI` environment variable that indicates a build is happening inside of Gitlab CI environment.

[GitLab Documentation](https://docs.gitlab.com/ce/ci/variables/README.html)

**Comment by nfm** [comment]
I think the codecov gem is also affected by this same issue: https://github.com/codecov/codecov-ruby/blob/036aed103ea1b9f1b855f3df787c39c430794209/lib/codecov.rb#L164

`https://codecov.io/gl/:orgname/:reponame/branches` is only showing `master` for us.

**Comment by stevepeak** [comment]
Checking in to see if this issue is still occurring. There has been a lot of progress with the GitLab integration lately.

**Comment by nfm** [comment]
@stevepeak I can confirm this is still happening. The current `master` commit for `codecov-ruby` is referencing the wrong environment variable value here: https://github.com/codecov/codecov-ruby/blob/f07d1dce427302edd560d2d86d4a87d95c779f83/lib/codecov.rb#L164

Here is [our fork](https://github.com/usabilityhub/codecov-ruby/tree/fix-gitlab-ci-detection), where the `fix-gitlab-ci-detection` branch fixes this: https://github.com/usabilityhub/codecov-ruby/commit/b1dbc8194ba9e9fdd54bb3cf51c23e05e8b1495b

Here are GitLab's official docs on environment variables they set: https://docs.gitlab.com/ce/ci/variables/README.html#predefined-variables-environment-variables

FYI, on gitlab.com the `CI_SERVER_NAME` env var is set to `GitLab`, not `GitLab CI`. I expect this env var would vary though if you were self hosting. I think `ENV.key?('GITLAB_CI')` is a safer way to detect that codecov is running on GitLab CI.

**Comment by thornbill** [comment]
I agree it seems checking `GITLAB_CI` would be the best option to detect if it is being run via Gitlab CI. I have an open [pull request](https://github.com/codecov/codecov-node/pull/37/files) for the NodeJS tool to do just that.

**Comment by stevepeak** [comment]
Thank you all for your patience. Deploying this patch today.

**Comment by thornbill** [comment]
This has not been corrected for `codecov-node`. Could someone take a look at my [pull request](https://github.com/codecov/codecov-node/pull/37) to fix it there? Thanks!
