### ISSUE TITLE
The link to fsharp example is broken

### ISSUE THREAD

**Issue by rleonid** [codecov/support#320]
here http://docs.codecov.io/docs/supported-languages,
specifically https://github.com/codecov/example-fsharp doesn't exist.

**Comment by stevepeak** [comment]
Woops! Looks like we do not have an F# example yet :(

Are you familiar with F#? Would you like to help us create one?

Thank you!

**Comment by rleonid** [comment]
I haven't worked in the language for quiet a number of years; it would take me to long to provide an idiomatic example.

**Comment by stevepeak** [comment]
Removed the F# link. Awaiting community help to create example.
