### ISSUE TITLE
Deleting repo from org fails with invalid redirect

### ISSUE THREAD

**Issue by xh3b4sd** [codecov/support#321]
I falsely added a repo to codecov which has no tests. Therefore I wanted to delete it. When I did so the following screenshot shows what happened. The repo being removed from the org within codecov was https://github.com/the-anna-project/collection. 

<img width="1440" alt="screen shot 2016-11-18 at 01 09 10" src="https://cloud.githubusercontent.com/assets/552769/20413186/b3dc6c06-ad2b-11e6-88cf-4190cb486291.png">

**Comment by stevepeak** [comment]
@xh3b4sd thank you for the bug report. 👍

**Comment by jcubic** [comment]
Have the same when deleting normal repo.

**Comment by stevepeak** [comment]
Fixing in this weekends release. Thank you!
