### ISSUE TITLE
Coverage for functional tests

### ISSUE THREAD

**Issue by jcheron** [codecov/support#322]
Is there a way to measure code coverage with codecov for functional tests, written with Selenium for example?

**Comment by stevepeak** [comment]
@jcheron we do have a unique technique in handling this. http://docs.codecov.io/docs/flags

```
# selenium build 1.0
./run functional_tests
bash <(curl -s https://codecov.io/bash) -F functional

# selenium build 1.1
./run unittest_tests
bash <(curl -s https://codecov.io/bash) -F unittest
```

Cheers!

**Comment by jcheron** [comment]
Thank you for the response.

The problem is that there is no hit on the lines of code to test.
Selenium interacts with the interface, but does not directly call the lines of code to be tested.
So the code coverage remains at 0%
