### ISSUE TITLE
Pull request says "no report uploaded yet" but console output shows successful upload

### ISSUE THREAD

**Issue by noisecapella** [codecov/support#323]
This is the PR: https://github.com/mitodl/micromasters/pull/1827
The codecov pulls page for this repo has this PR listed but it's marked 'No report uploaded yet': https://codecov.io/gh/mitodl/micromasters/pulls
The code coverage output is at the bottom of the Travis logs here (also linked in PR): https://travis-ci.org/mitodl/micromasters/builds/177171724

Specifically, the JS build has this output:

    =============================== Coverage summary ===============================
    Statements   : 97.75% ( 7456/7628 )
    Branches     : 88.9% ( 1177/1324 )
    Functions    : 97.29% ( 1723/1771 )
    Lines        : 97.89% ( 6991/7142 )
    ================================================================================
    Uploading coverage...
      _____          _  
     / ____|        | |  
    | |     ___   __| | ___  ___ _____   __  
    | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
    | |___| (_) | (_| |  __/ (_| (_) \ V /  
     \_____\___/ \__,_|\___|\___\___/ \_/  
                                    v1.0.1
    ==> Detecting CI Provider
        Travis CI Detected
    ==> Configuration: 
        Endpoint: https://codecov.io
    { service: 'travis',
      commit: 'efda9414079e4ddd0eaa466b6990506555c54407',
      build: '9123.2',
      branch: 'gs/codecov6',
      job: '177171726',
      pr: 'false',
      slug: 'mitodl/micromasters',
      root: '/src',
      package: 'node-v1.0.1' }
    ==> Building file structure
    ==> Generating gcov reports (skip via --disable=gcov)
        $ find /src -type f -name '*.gcno'  -exec gcov  {} +
    ==> Scanning for reports
        + /src/coverage/coverage.raw.json
        + /src/coverage/lcov.info
    ==> Uploading reports
        Success!
        View report at: https://codecov.io/github/mitodl/micromasters/commit/efda9414079e4ddd0eaa466b6990506555c54407

The python output:

    py35 runtests: commands[1] | /src/travis/codecov_python.sh
    Uploading coverage...
    
          _____          _
         / ____|        | |
        | |     ___   __| | ___  ___ _____   __
        | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
        | |___| (_) | (_| |  __/ (_| (_) \ V /
         \_____\___/ \____|\___|\___\___/ \_/
                                        v2.0.5
    
    ==> Detecting CI provider
        Travis Detected
    ==> Preparing upload
    ==> Processing gcov (disable by -X gcov)
        Executing gcov (find /src -type f -name '*.gcno'  -exec gcov -pb  {} +)
    ==> Collecting reports
        + /src/coverage.xml bytes=182413
    ==> Appending environment variables
        + TRAVIS_OS_NAME
        + TRAVIS_RUBY_NAME
    ==> Uploading
        .url https://codecov.io
        .query slug=mitodl%2Fmicromasters&branch=gs%2Fcodecov6&job=177171725&build=9123.1&pr=false&commit=efda9414079e4ddd0eaa466b6990506555c54407&service=travis&package=py2.0.5
        Pinging Codecov...
        Uploading to S3...
        https://codecov.io/github/mitodl/micromasters/commit/efda9414079e4ddd0eaa466b6990506555c54407

The commit referenced exists and appears to show correct coverage output, but it doesn't appear linked to the PR even though it is the only commit on that PR's branch

Thanks for your help!

**Comment by stevepeak** [comment]
Hey @noisecapella Thanks for asking!

First thing I would suggest is setting up a team bot. The user in the past seems to have lost access to the repository. http://docs.codecov.io/docs/team-bot

I'm not quite sure why the pull request's head did not get updated properly. I'll need to review that process in more detail to see if there are any issues. Meanwhile, I've manually updated it.

Thank you!

**Comment by noisecapella** [comment]
Thanks for your quick reply. We have a team bot which was set up with that account: https://github.com/odlbot
We noticed that we didn't specify the bot in the settings so we updated that. However we are still seeing a problem. I created a new PR https://github.com/mitodl/micromasters/pull/1830 with the same commit and an additional empty commit and it shows the same 'no report uploaded yet' message in the PR list.

We are running these tests within docker. Are there any environment variables which need to be specified? We are passing all `TRAVIS*` and `CI*` environment variables, is there another which would be relevant here?

Is there any logging we can turn on to see if there's an issue the logs are not showing?

**Comment by stevepeak** [comment]
Hum... I'll need to investigate the pull request linking issue. Hopefully it will not take long. Thanks

**Comment by stevepeak** [comment]
Strange... the GH API is returning multiple pull requests with a simple commit:

https://api.github.com/search/issues?q=efda9414079e4ddd0eaa466b6990506555c54407+repo:mitodl%2Fmicromasters+type:pr+state:open

1830 and 1827 are returned. Humm

**Comment by noisecapella** [comment]
Things appear to be working now, I'm guessing maybe the recent Github outages have had something to do with it. Anyway I'll close this issue and open another one if the problem comes back. Thanks for your help
