### ISSUE TITLE
no hits for Selenium tests

### ISSUE THREAD

**Issue by jcheron** [codecov/support#324]
I use Selenium for functional testing of web applications.
Selenium interacts with gui, but does not directly call the lines of code to be tested.
Therefor, Codecov does not trigger any hit on the lines of code to be tested.
So the code coverage remains at 0%.

Is there a way to avoid this problem?

**Comment by jcheron** [comment]
No one in the codecov team has any experience with Selenium to share ?

**Comment by stevepeak** [comment]
Hey @jcheron thank you for asking.

Is this all for Javascript? I know you can wrap JS with a coverage collection agent and submit the results after tests complete.

**Comment by jcheron** [comment]
Hi @stevepeak , thank you for your interest.
this is for PHP MVC (using Ajax, but javascript is not central)

**Comment by stevepeak** [comment]
I see. My first impression is that this is may not be possible in PHP, as far as I know. The objective is to collect coverage data while executing the application right? 

I'm more familiar with python and it's possible, in theory, to run a python program with coverage enabled. e.g. `coverage run server.py` then run ui tests and cleanly exit the server with coverage collected.

**Comment by stevepeak** [comment]
Closing issue, but welcome new information is there are unresolved issues.
