### ISSUE TITLE
Jacoco Report.xml not getting processed

### ISSUE THREAD

**Issue by anderGonzalez** [codecov/support#326]
I generated Jacoco coverage report within an ant build file. The reports get generated properly on  my local machine and show no error on travis log. Once the message gets to codecov the log shows a **no-reports-generated** error.  The report.xml is generated on the project's root.

**CI:** Travis-ci
**Build:** ant + JacocoAnt
**Codecov console log:**
- 2016-11-22T23:35:20+01:00 upload  no-reports-generated  error=Error   
- 2016-11-22T23:35:20+01:00 upload  Processed file name=report.xml language=jacoco   
- 2016-11-22T23:35:20+01:00 upload  Upload archived download   

I'm new to Codecov and I know that most of the projects are built using more modern bouilding systems as gradle or maven. But from what I got from the help and the examples I thought that reports woulg get processed as long as the report.xml file is generated with an acepted fomat (as Jacoco).

**Comment by stevepeak** [comment]
Hey @anderGonzalez  happy to help out! This is likely a path mapping issue. Files in the Jacoco report are not pointing back to your projects file network.

Can you link me to a commit in Codecov so I may inspect more? You can PM me on Gitter https://gitter.im/stevepeak

**Comment by agonzalezt** [comment]
Hi @stevepeak here you have the links to a commit. One is the[ commit on codecov](https://codecov.io/gh/Maracars/POPBL5/commit/8555be09b2481ae864c9ecec8506a9f561197d62) and [the respective travis-ci commit](https://travis-ci.org/Maracars/POPBL5/builds/179223900). I hope it helps and thanks a lot!

**Comment by stevepeak** [comment]
Odd.. so there is no actual line coverage data in the [uploaded Jacoco report](https://codecov.s3.amazonaws.com/v4/raw/2016-11-27/35F1AF24AB052E336A7093B95E1CE152/8555be09b2481ae864c9ecec8506a9f561197d62/9243acf0-4fff-4132-9723-e79ce9d123a3.txt). Can you run coverage locally and review the jacoco file to see if there are source lines (via `<line>` nodes) in the report.

**Comment by agonzalezt** [comment]
Thanks a lot, you've hit the nail on the head! It's working now. The problem was that I wasn't compiling the source with debug info what made it impossible for jacoco to generate the per line coverage information.

Again, thanks a lot.

**Comment by stevepeak** [comment]
@agonzalezt great! So what did you do exactly to fix this? I would like to add a note to https://github.com/codecov/example-java about this issue. (PR welcome with ❤️ )

**Comment by agonzalezt** [comment]
When using an ant buildfile to build the project the java compile instruction has to activate the debug option so that Jacoco then can generate the xml with information on line level.

So you compile the source with:
```xml
<javac ... debug="on">
```

And then execute the tests with coverage inspection and generate the result.xml

```xml
<jacoco:coverage destfile="${result.file}">
      <junit ...>
          ...
      </junit>
</jacoco:coverage>
```
```xml
 <target name="jacocoReport">  
    <jacoco:report>  
      <executiondata>    
        <file file="${result.file}"/>   
      </executiondata> 
       ...
    </jacoco:report> 
 </target>
```
More info [here](http://www.eclemma.org/jacoco/trunk/doc/ant.html).
