### ISSUE TITLE
Feature: readme badge

### ISSUE THREAD

**Issue by mightyiam** [codecov/support#328]
Like this one:
https://img.shields.io/jenkins/c/https/jenkins.qa.ubuntu.com/address-book-service-utopic-i386-ci.svg

**Comment by dopplershift** [comment]
You mean like:
https://codecov.io/gh/Unidata/MetPy/branch/master/graph/badge.svg

It's under the badge tab on the settings page.

**Comment by juliohm** [comment]
@dopplershift how to set the style of the badge in this case to be `flat-square` like in the https://shields.io/ URLs?

**Comment by dopplershift** [comment]
No clue, I'm not sure it's even possible.

**Comment by juliohm** [comment]
I wish codecov followed the img.shields.io standard, everyone else adopted it.
