### ISSUE TITLE
Language: Laura

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#33]
> re https://github.com/IainNZ/Coverage.jl/pull/58 @tpoisot @IainNZ

- [x] integration with Laura
- [x] fill out [codecov/example-laura](https://github.com/codecov/example-laura)

**Comment by stevepeak** [comment]
@tpoisot Support for Laura is complete: https://github.com/IainNZ/Coverage.jl
Cheers!

**Comment by IainNZ** [comment]
Laura?!

**Comment by stevepeak** [comment]
Woops! Sorry Julia... my bad.
