### ISSUE TITLE
Don't assume bash is default shell

### ISSUE THREAD

**Issue by seanf** [codecov/support#332]
The codecov instructions given in various places (eg Integration Guide for a new project):

    bash <(curl -s https://codecov.io/bash)

assume that the shell _calling bash_ supports process substitution (as bash does). If the execution environment uses a plain Bourne shell (eg Jenkins, by default), this will fail with an error message like this one:

    /tmp/hudson7928614965355543336.sh: line 7: syntax error near unexpected token `('

This alternative command should work with any Bourne-like shell:

    curl -s https://codecov.io/bash | bash -

**Comment by seanf** [comment]
Where the script needs an argument (like `-t TOKEN`), this should work:

    curl -s https://codecov.io/bash | bash -s - -t TOKEN

**Comment by stevepeak** [comment]
@seanf Thank you for expressing this. We do have some notes in https://github.com/codecov/codecov-bash but need to include this in the app too.
