### ISSUE TITLE
Codecov "External" builds are no longer links in GitLab

### ISSUE THREAD

**Issue by carusology** [codecov/support#333]
Whenever we have our GitLab CI runners send codecoverage metrics to codecov.io, codecov.io adds two more "builds" to our GitLab pipeline called "External." I loved this feature! Up until recently, these builds were buttons that acted like hyperlinks that you could click, taking you to the coverage report for the build's patch or the overall project. Somewhere between GitLab release 8.14 or GitLab 8.15, these were no longer links. You now have to look through the build logs or navigate within codecov.io's GUI to find the relevant code coverage report for that patch.

Here's a screenshot showing what I am talking about.

![gitlab_link](https://cloud.githubusercontent.com/assets/19539318/21528993/5eda3a0a-cceb-11e6-9911-cfdddb38a33a.png)

I am unsure if this is a underlying problem with GitLab (maybe they changed their API?) or with CodeCov (a regression?), but about a week ago it simply stopped working. The builds still appear, but I can no longer click on them. Perhaps the GitLab API changed in some unexpected way. For general reference, causing builds to act as links is still possible. As an example, I can still click the other builds steps, and that navigates me to the build logs generated by the relevant GitLab CI runner.

**Comment by stevepeak** [comment]
Hey @carusology Interesting issue... From what we can see the API docs did change on a number of endpoints (ugh) but the commit status are still the same.

https://docs.gitlab.com/ce/api/commits.html#post-the-build-status-to-a-commit

If you could confirm Codecov is setting the target url by checking the [Get the status of a commit](https://docs.gitlab.com/ce/api/commits.html#get-the-status-of-a-commit) API that would be very helpful.

**Comment by carusology** [comment]
This is actually working again sometime recently. I'm not sure exactly when, since I haven't been trying to click on it since I filed this issue. When I looked at a commit around the time that I filed this issue, the `target_url` you referenced is populated. Here's an example of what they looked like on a commit from December 29th. Based upon these symptoms, I'll guess that GitLab simply broke the link in the GUI, but the data was always there.

Since this is working again, I'm going to close the issue.

```
  {
    "id": 7997160,
    "sha": "068386aaaa62e0f951825e34607a3ecd273fec3b",
    "ref": "37-add-asynchronous-variants-to-iauthorizationservice",
    "status": "success",
    "name": "codecov/project",
    "target_url": "https://codecov.io/gl/invio/gambit/compare/91b7e4fa1c3b0fda49b9e9329c3ccec608ba5c54...068386aaaa62e0f951825e34607a3ecd273fec3b",
    "description": "Absolute coverage decreased by -0.19% but relative coverage increased by +3.26% compared to 91b7e4f",
    "created_at": "2016-12-29T21:21:32.504Z",
    "started_at": null,
    "finished_at": "2016-12-29T21:21:32.503Z",
    "allow_failure": false,
    "author": {
      "name": "Brian Caruso",
      "username": "carusology",
      "id": 525385,
      "state": "active",
      "avatar_url": "https://gitlab.com/uploads/user/avatar/525385/avatar.png",
      "web_url": "https://gitlab.com/carusology"
    }
  },
  {
    "id": 7997159,
    "sha": "068386aaaa62e0f951825e34607a3ecd273fec3b",
    "ref": "37-add-asynchronous-variants-to-iauthorizationservice",
    "status": "success",
    "name": "codecov/patch",
    "target_url": "https://codecov.io/gl/invio/gambit/compare/91b7e4fa1c3b0fda49b9e9329c3ccec608ba5c54...068386aaaa62e0f951825e34607a3ecd273fec3b",
    "description": "99.16% of diff hit (target 95.90%)",
    "created_at": "2016-12-29T21:21:31.849Z",
    "started_at": null,
    "finished_at": "2016-12-29T21:21:31.847Z",
    "allow_failure": false,
    "author": {
      "name": "Brian Caruso",
      "username": "carusology",
      "id": 525385,
      "state": "active",
      "avatar_url": "https://gitlab.com/uploads/user/avatar/525385/avatar.png",
      "web_url": "https://gitlab.com/carusology"
    }
  }
```

**Comment by stevepeak** [comment]
Interesting... I wonder if other CI services with `target_url` provided failed to link during that time too. Happy to hear it's working again
