### ISSUE TITLE
Broken Image for Badge

### ISSUE THREAD

**Issue by kosmologist** [codecov/support#335]
Badge is not being displayed with the following error:
`error on line 17 at column 63: StartTag: invalid element name`

See here:
https://codecov.io/gh/kosmologist/Andromeda/branch/master/graph/badge.svg
https://github.com/kosmologist/Andromeda/blob/master/README.md

**Comment by stevepeak** [comment]
Hey @kosmologist this is a known issue we are resolving shortly. It is due to coverage being `<1%`. Thank you
