### ISSUE TITLE
No Status Callbacks on Github

### ISSUE THREAD

**Issue by jkogara** [codecov/support#337]
As subject - I'm not getting any status callbacks from codecov - 

additionally this spinner runs forever on the repo 

![image](https://cloud.githubusercontent.com/assets/574876/21766364/e015e6fe-d665-11e6-8f8a-57551cdb826c.png)

I'm using circleCI, the project I'm working on is zoomer/zoomer 

Thanks in advance for any help.

**Comment by stevepeak** [comment]
Hey @jkogara I'm seeing recent commits are working. This issue is 99% of the time an issue with the bot user: http://docs.codecov.io/docs/team-bot

Thanks!
