### ISSUE TITLE
'istanbul ignore if' triggers a partial hit

### ISSUE THREAD

**Issue by idiotWu** [codecov/support#338]
I am using 'istanbul ignore' annotations to skip untestable statements. This works well with Istanbul but triggers partial hits with codecov:

Istanbul HTML report:
![wx20170110-095249](https://cloud.githubusercontent.com/assets/6022672/21789744/a2bb48ca-d71a-11e6-8448-b10bdee17909.png)

codecov report:
![wx20170110-095300](https://cloud.githubusercontent.com/assets/6022672/21789750/aaebe270-d71a-11e6-9729-29df936a6e5d.png)

**Comment by stevepeak** [comment]
Hey @idiotWu This is the first I've seen istanbul ignore. This issue is not with Codecov but with Istanbul. During the collection of coverage istanbul would be responsible for detecting the ignore.

I would suggest making a new issue at https://github.com/gotwarlost/istanbul
Thank you!

**Comment by idiotWu** [comment]
@stevepeak thanks for the message! I finally figured out that it was caused by the [sourcemap-istanbul-instrumenter-loader](https://www.npmjs.com/package/sourcemap-istanbul-instrumenter-loader). Due to the complexity of my workflow, I could hardly tell what was happening :(. Sorry for bothering here.

**Comment by stevepeak** [comment]
No worries :) Thank you!
