### ISSUE TITLE
Inaccurate code coverage

### ISSUE THREAD

**Issue by simov** [codecov/support#34]
Hi, I just pushed https://github.com/request/request/pull/1650 and my code coverage dropped with 7 percents in codecov, for just one line changed (plus I have a test for it).

I have both codecov and coveralls enabled for that project, and they both use the same output data.

- [codecov - 82%](https://codecov.io/github/request/request?branch=master)
- [coveralls - 89%](https://coveralls.io/r/request/request)

Here is the command used to send the reports:

```bash
npm run test-cov && cat ./coverage/lcov.info | codecov && cat ./coverage/lcov.info | coveralls
```

Both services were reporting the same coverage up until now.

**Comment by stevepeak** [comment]
We recently fixed `lcov` reports to expose partial line coverage as seen here: https://codecov.io/github/request/request/lib/har.js?ref=master#l-57

In Codecov a partial is considered a "miss", which would account for the drop in coverage.

**Comment by simov** [comment]
I see, so I guess we should improve our tests in this case. Is there going to be an option for counting the partials as misses or not?

BTW another noticeable difference between codecov and coveralls I'm seeing is the branches count.

**Comment by stevepeak** [comment]
For the sake on consistency we will always count a partial as a miss (as far as the overall coverage percentage is concerned). This is because if you add a test that changes a `parital` to a `hit` then the reward should be **increase** in coverage not a neutral change.

**Comment by simov** [comment]
Got it, that makes sense. I was probably misled by the fact that I was looking at the coverage report generated by `istanbul` locally where the partial misses were highlighted but still the overall percentage was not affected.

![partial](https://cloud.githubusercontent.com/assets/1694112/8299473/94e71ee8-1981-11e5-8052-a2dfb1c49cad.png)

Anyway, at least it would be a nice addition to highlight only the misses, not the entire line.
