### ISSUE TITLE
Compare URL: 404 not found when branch name contains slash (/)

### ISSUE THREAD

**Issue by svlapin** [codecov/support#340]
First of all I'd like to say thank you for the awesome tool!

Found smth like a small bug.
On `Compare` view I select two branches to compare, say `master` and `feature/my-awesome-feature`.
That brings me to `../compare/master...feature/my-awesome-feature` and shows 404.

If I manually escape the slash with `%2F`: `../compare/master...feature%2Fmy-awesome-feature`, everything works fine.

**Comment by stevepeak** [comment]
Thank you @svlapin for the kind words 👍 

This is a good issue you bring up here. The only problem I see here is that there are embedded links in the compare pages. e.g. `.../compare/base...head/src/...`. I'll need to play around with our url parser to see if we can accept the branch slashes while respecting the subsequent paths.

Thank you!

**Comment by stevepeak** [comment]
Awesome! Working in next major release.

✅ `/compare/BRANCH/NAME...BRANCH/NAME/*`
✅ `/branch/BRANCH/NAME/*`
❌ `/(src|tree|list)/BRANCH/NAME` because part of the branch name would append to the source name
