### ISSUE TITLE
GitLab repos aren't found

### ISSUE THREAD

**Issue by ConorIA** [codecov/support#343]
I've been trying to add a GitLab-hosted project to Codecov, but the list of my repos never populates and the when I try to navigate directly to a repo, I get a 500 code. GitHub projects appear without any trouble. 

![screenshot from 2017-01-27 16-29-51](https://cloud.githubusercontent.com/assets/870746/22388343/134ccc80-e4ae-11e6-8fea-d727af9e7992.png)

![screenshot from 2017-01-27 16-30-14](https://cloud.githubusercontent.com/assets/870746/22388346/172cb694-e4ae-11e6-98fe-30c7a9ea9814.png)

**Comment by stevepeak** [comment]
Thank you for reporting this. I'll check our logs and report back asap.

**Comment by stevepeak** [comment]
I don't indent on pointing fingers, but it appears GitLab API does not return a data point we had accounted for in the past. I'll fix now and deploy asap.

**Comment by ConorIA** [comment]
Amazingly fast! Thanks @stevepeak!

**Comment by ConorIA** [comment]
Different issue now. I can navigate to the repo, but as soon as I open a repo, my login session expires (or at least, I no longer appear as logged in) and am told that I need write access to access the repo token. 

Clicking around shows a 401 "bad credentials" message.

**Comment by stevepeak** [comment]
I'll check that out 😄

**Comment by ConorIA** [comment]
I guess there were a lot of GitLab api changes in the last release, but not much documentation about them, unfortunately!

**Comment by stevepeak** [comment]
We did have another issue with the Pull Commits api... the pagination broke 😦

**Comment by stevepeak** [comment]
@ConorIA ugh... some significant changes to their api that we were unaware of. Working through them now.

**Comment by stevepeak** [comment]
Ok @ConorIA lets give it another shot. Please let me know if you find any other API's not working.
