### ISSUE TITLE
Document codecov.json format

### ISSUE THREAD

**Issue by seanf** [codecov/support#344]
I haven't been able to find much in the way of current documentation for the codecov json format, as uploaded by Cloverage, and mentioned here: https://github.com/codecov/support/issues/106

Also, is it still possible to download the codecov.json files, as mentioned in the above issue? The API docs don't seem to mention it any more, and I can't find it in the UI.

The only references I have been able to find are:

- https://gist.github.com/codecov-io/96e1addb96856a9034c2
- https://github.com/cloverage/cloverage/pull/78/files#diff-5cc18e32574ae4748a00a0958e69947fR334

**Comment by stevepeak** [comment]
Thank you for pointing this out. I'll write some docs and close this issue with the link. Thanks!

**Comment by stevepeak** [comment]
Here we go https://docs.codecov.io/reference#upload

Specifically: https://docs.codecov.io/reference#section-codecov-json-report-format

**Comment by seanf** [comment]
Great, thank you!

@stevepeak is it still possible to download the json files after they have been uploaded?

**Comment by stevepeak** [comment]
Yes, you can download the raw uploaded reports and the codecov resulting report.

For the full report, you will need to use `?src=extension` for the time being to get the full contents.

```
curl https://codecov.io/gh/owner/repo/commit/sha?src=extension
```

> We are building a new api to expose more data soon.
