### ISSUE TITLE
comment report: wrong term increase

### ISSUE THREAD

**Issue by tleunen** [codecov/support#347]
I've noticed the comment says `increase` when it should say `decrease`.

![screen shot 2017-02-03 at 3 41 00 pm](https://cloud.githubusercontent.com/assets/1972567/22607810/8e60473e-ea27-11e6-9f31-4d37b41021b5.jpg)

**Comment by stevepeak** [comment]
Hey @tleunen, oh so silly! Sorry about that. Fixed up.
