### ISSUE TITLE
UI: "1 Repositories" / "1 Members"

### ISSUE THREAD

**Issue by hugovk** [codecov/support#348]
1. Add an organisation with one repo and one member
2. Visit https://codecov.io/gh

Actual result:
Says "1 Repositories" and "1 Members"
![image](https://cloud.githubusercontent.com/assets/1324225/22610219/163d0440-ea6d-11e6-840a-7678f35d7b09.png)

Expected result:
Says "1 Repository" and "1 Member"

**Comment by stevepeak** [comment]
Thanks@
