### ISSUE TITLE
Is it possible to push multiple reports by targets?

### ISSUE THREAD

**Issue by eMdOS** [codecov/support#353]
I'm developing a framework for `iOS` and `tvOS`. Locally in my Xcode project, I'm generating separated `cobertura.xml` files (one for each target, 'cause I could have different % of coverage by target).

So, I've been wondering if is possible to push multiple reports.

I'm using `Travis`, so, in my `.travis.yml` I have something like:

```yml
after_success: 
  - bash <(curl -s https://codecov.io/bash) -f slather/iOS/cobertura.xml -X coveragepy -X gcov -X xcode
  - bash <(curl -s https://codecov.io/bash) -f slather/tvOS/cobertura.xml -X coveragepy -X gcov -X xcode
```

... but ... seems like only the first report is being pushed, but I'm unsure.

Thanks in advance {^_^}.

**Comment by stevepeak** [comment]
Hey @eMdOS very nice job! This is perfect 👍  Can you provide me a link to the build in Codecov, I'll review the reports. Thank you!

> We have seen Slather cause conflicts when it generates xcode reports via llvm cov. Your use of cobertura.xml may not encounter this known issue. +1 for `-X xcode`

**Comment by eMdOS** [comment]
@stevepeak https://codecov.io/gh/eMdOS/Motu

**Comment by stevepeak** [comment]
@eMdOS Checkout the uploads: https://codecov.io/gh/eMdOS/Motu/commit/cc107faeb3821996f4b65a85f3ceaf655119df73/build

The two reports are the same according to the uploads. This may be an issue with Slather... I'm not sure.

**Comment by eMdOS** [comment]
@stevepeak is it possible to preview (in Codecov) `iOS` and `tvOS` reports separately?

**Comment by eMdOS** [comment]
0_0 awesome... I'll try it... Thank you so much {^_^} .. !!
