### ISSUE TITLE
Support for excluding from metrics but don't ignore entirely

### ISSUE THREAD

**Issue by krampe** [codecov/support#356]
It would be nice if there was the ability to exclude files or folders from being included in the calculation of the overall coverage percentage but still be able to visualize information for that content in the report.  For example if you have directories that include prototype code that you don't want to count against your coverage numbers, but you still want to be able to navigate to that directory in the coverage report and look at stats for it.

**Comment by stevepeak** [comment]
Thank you for your feature request. We build Flags to do just that: http://docs.codecov.io/docs/flags
With Flags you can change the commit statuses to remove your prototype code.

The "overall" coverage ratio is not able to be filtered at the moment. However, you can [ignore specific Flags](https://docs.codecov.io/docs/flags#section-hiding-builds-eg-nightly-builds) in the coverage. Here is an example:

```bash
run tests, not prototype
bash <(curl -s https://codecov.io/bash) -F core
run prototype tests
bash <(curl -s https://codecov.io/bash) -F prototype
```

```yaml
flags:
  prototype:
    joined: false
```

> Feedback always welcome 👍
