### ISSUE TITLE
Patch / Project Status Checks Not Displaying

### ISSUE THREAD

**Issue by nelson-liu** [codecov/support#359]
Hi,
I'm trying to turn on the patch and project coverage status checks on my repo (see: https://github.com/allenai/deep_qa/pull/208), but it doesn't seem like they are appearing. I thought they were actually enabled by default -- am I missing a switch I need to flip in the web UI?

Thanks!

**Comment by stevepeak** [comment]
Looks like there are 404's on the posting the status: https://codecov.io/gh/allenai/deep_qa/commits/00cc3fd2821ae8380e6c72c162f28d9913ab5a26/build

Please checkout http://docs.codecov.io/docs/team-bot to resolve 👍 Thank you
