### ISSUE TITLE
Use parent commit when base not found

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#363]
> For customers seeing `Missing base commit`

Impacted pull requests are those that fork from a commit not tested in CI. Examples:

# Example 1
```
master . a mc
pull        \ b
```
> `mc` (Merge commit) was not tested in CI. Codecov will use `a` instead for the pull request compare `a...b`

```
master . a "[ci skip]"
pull          \ b
```
> Skipped commits that were not tested in CI. Codecov will use `a` instead for the pull request compare `a...b

----

- [x] store the real base commit and the new comparison commit
- [x] continue to use `mc...b` for the pull request diff, however use the new compared to commit for comparing metrics
- [x] inform the end user that the base commit used to compare is not the "read" pull request base commit

**Comment by stevepeak** [comment]
@pcardune I believe you asked about this.

**Comment by stevepeak** [comment]
## New rules

1. **ALWAYS** use the pull base commit if report exists
2. **CAN** use base commit's parent  if base commit has no report
```
```

```yaml
codecov:
  pulls:
    allow_coverage_offsets: no  # default
```

**Comment by stevepeak** [comment]
Would you like to beta this? Ping us in Slack leaving a message in this format:

```
enable beta #363 on owner/repo
```

Thank you!

**Comment by stevepeak** [comment]
Deployed. Awaiting feedback and beta.

**Comment by stevepeak** [comment]
Beta closed and feature deployed 👍

**Comment by juancarlosfarah** [comment]
Is this working as expected? Just pushed a commit for a branch that was forked from master after a pull request that was sent to Codecov and then merged, but I get the "Missing base report." error. Does the merge need to have been sent to Codecov too?

**Comment by vanniktech** [comment]
Does not seem to be working [here](https://github.com/vanniktech/espresso-utils/pull/12).

**Comment by swrobel** [comment]
Any update here?

**Comment by matej** [comment]
We just deployed codecov to one project in our monorepo and are seeing the same problem. We have frequent commits from untracked projects in the repository so it's pretty likely that we branch off for a new pull request branch from a commit with no coverage data. In that case we hit the "Missing base commit". 

This sounds like it would resolve the issue for us. However, the deployed feature does not seem to work. 

Are we missing anything? Is this supposed to be the default behavior or are any configuration changes needed?

**Comment by ChrisBr** [comment]
Same problem problem in https://github.com/openSUSE/open-build-service/pulls. We frequently hit this problem which is really annoying :cry: 

One example is:
- https://github.com/openSUSE/open-build-service/pull/4813
You can see the commits here:
- https://codecov.io/gh/openSUSE/open-build-service/pull/4813/commits

Pull request base commit is, which is indeed a merge commit:
https://codecov.io/gh/openSUSE/open-build-service/commit/5911b57566cdfc9de9c5416ed719cce0bddbd7ce
https://github.com/openSUSE/open-build-service/commit/5911b57566cdfc9de9c5416ed719cce0bddbd7ce

@stevepeak any update on this? This results that we often just ignore the result of codecov :cry: which definitely not what we want...
