### ISSUE TITLE
Documentation coverage

### ISSUE THREAD

**Issue by junghans** [codecov/support#364]
It would be nice if you guys could analyze the documentation coverage as well.

Along the lines what [doxy-coverage.py](https://github.com/alobbs/doxy-coverage/blob/master/doxy-coverage.py) pull out of doxygen's xml output.

**Comment by stevepeak** [comment]
Hey @junghans this is really cool! We have plans to open up codecov to be pluggable and this would be an awesome tool to add.

**Comment by stevepeak** [comment]
On second thought. This could be implemented quicker. Can you generate an xml or json report for your documentation coverage?

**Comment by junghans** [comment]
@stevepeak, we are doing doxygen coverage combination codecov [here](https://github.com/laristra/flecsi/blob/master/docker/Dockerfile#L50), however the [output](https://travis-ci.org/laristra/flecsi/jobs/205326017#L1911) isn't very nice!

**Comment by stevepeak** [comment]
The output would have to be in a format that expresses `line_number: coverage` data per file.

Sounds like a pull request to doxy is in order. 👍

**Comment by stevepeak** [comment]
Here is Codecov json format that you can use: https://docs.codecov.io/v4.3.0/reference#section-codecov-json-report-format

**Comment by junghans** [comment]
Ok, I think I got [it](https://travis-ci.org/laristra/flecsi/jobs/205617926#L1947): laristra/flecsi@5a4470419156e810f6b320c950e1a237f92cc5c8. Where is the report stored?

**Comment by stevepeak** [comment]
Reports are uploaded to Codecov and archived from there. https://codecov.io/gh/laristra/flecsi/commit/5a4470419156e810f6b320c950e1a237f92cc5c8/build


```
# path=docs.coverage.json
[
  {
    "/home/flecsi/flecsi/flecsi/topology/test/gravity.cc": [
      {
        "symbol": "Aggregate::Aggregate", 
        "line": 12, 
        "documented": false, 
        "file": "/home/flecsi/flecsi/flecsi/topology/test/gravity.cc"
      }
    ], 
```

This format is new to us. But I can add a server side parser quickly to add support.

**Comment by junghans** [comment]
That would be nice if you could do it server-sided.

I seems [coverxygen](https://github.com/psycofdj/coverxygen) is generating lcov output, which could be useful long term as an intermediate format for other coverage tools.

On the other hand, @psycofdj might have an easy way to implement out in the [this format](https://docs.codecov.io/v4.3.0/reference#section-codecov-json-report-format), too.

**Comment by stevepeak** [comment]
It's no problem, I'm almost done with adding it 👍

**Comment by psycofdj** [comment]
I'll be glad to help by implementing new formats in [coverxygen](https://github.com/psycofdj/coverxygen). Feel free to open an issue.

**Comment by stevepeak** [comment]
Codecov already supports lcov among many other coverage report formats. It would be better to add an already accepted format, like lcov.

Can you already export as lcov?

**Comment by psycofdj** [comment]
Default output format is lcov tracefiles

**Comment by junghans** [comment]
@stevepeak, is it done? Should I try and push another documentation coverage build?

**Comment by stevepeak** [comment]
@junghans I did not deploy the parser for the json results. If you can get the results in lcov it will work immediately.

**Comment by junghans** [comment]
Ok, I did:
```
python -m coverxygen --xml-dir doc/doxygen/xml/ --src-dir .. --output doxygen.coverage.info
$HOME/.local/bin/codecov -X gcov -f doxygen.coverage.info -F documentation
```
and Codecov seems to take [it](https://travis-ci.org/laristra/flecsi/jobs/206624960#L1230), but where would I see the numbers for it?

**Comment by stevepeak** [comment]
@junghans issue is lack of file structure included in the upload:

```
TRAVIS_OS_NAME=
<<<<<< ENV

<<<<<< network
# path=doxygen.coverage.info
```
Can you call Codecov like this instead:

```diff
- $HOME/.local/bin/codecov -X gcov -f doxygen.coverage.info -F documentation
+ bash <(curl -s https://codecov.io/bash) -X gcov -f doxygen.coverage.info -F documentation
```
> The node uploader appears to [have issues](https://travis-ci.org/laristra/flecsi/jobs/206624960#L1246) in your environment when calling `git ls-files`

**Comment by junghans** [comment]
Nice, I got it working [now](https://travis-ci.org/laristra/flecsi/jobs/208783568#L1240).

Is there are a way to see the coverage for `documentation` independently of the `gcov` coverage, (generated for the same git sha, in different travis build) in the web interface?

**Comment by stevepeak** [comment]
When using Flags you can accomplish this in various ways. What specifically are you looking for? Statuses, badges, graphs, source overlay?

**Comment by junghans** [comment]
Basically I would like to see the source overlay for the `documentation` tag only.

**Comment by stevepeak** [comment]
You can toggle Flags in the UI (top right corner of the source page). https://cl.ly/2z1b3g3T3N1r

When you have more than one Flag it works better 👍

**Comment by junghans** [comment]
It works now, thanks!
