### ISSUE TITLE
be less intrusive on GitHub PRs

### ISSUE THREAD

**Issue by nschloe** [codecov/support#365]
Whenever I submit a PR to a GitHub repo (also my own), codecov will post a sophisticated reply with all sorts of coverage stats. This is in contrast to all other services I use (e.g., travis) which just post their updated in the merge info field.
![mergeinfo](https://cloud.githubusercontent.com/assets/181628/23499511/b8426f18-ff2c-11e6-8023-af6b9c84bf8b.png)
I would like to see the same thing for codecov.

**Comment by stevepeak** [comment]
@nschloe we do post commit statuses: https://docs.codecov.io/docs/commit-status

Can you provide a commit in Codecov that did not post the statuses.

Thank you,
Steve

**Comment by nschloe** [comment]
Thanks @stevepeak for the speedy reply.

You're right of course. What I try to do is get rid of the lengthy replies such as https://github.com/nschloe/voropy/pull/11#issuecomment-284519580.

**Comment by nschloe** [comment]
A screenshot of my GitHub landing page. The codecov spam hides the interesting information.

![sp](https://cloud.githubusercontent.com/assets/181628/23905372/2280b7f2-08cb-11e7-8dc4-c986cb30c446.png)

**Comment by stevepeak** [comment]
Sorry, but this is out of our control. This feed is presented by GitHub.

Posting a comment will:
1. email all subscribers of the comment
2. add item to landing page

Both those items are out of our control. If we could adjust the settings we would give you that option. Sorry ☹️  but this is best presented to GH staff as a feature request. (This is a daily support question).

**Comment by nschloe** [comment]
@stevepeak It's right that posting a comment will trigger all these actions. That's why I would like to turn off the comments and just have the statuses.

**Comment by stevepeak** [comment]
> That's why I would like to turn off the comments and just have the statuses.

```yaml
# in your codecov.yml
comment: no
```

**Comment by nschloe** [comment]
Perfect.
