### ISSUE TITLE
I copied and pasted the codecov token into another project and now can't fix it

### ISSUE THREAD

**Issue by angeloocana** [codecov/support#368]
I used this project:
https://github.com/polutz/ptz-user-domain
as a starter point to:
https://github.com/polutz/ptz-user-graphql

And i forgot to get a new token for ptz-user-graphql, 
and now the ptz-user-domain keeps showing the ptz-user-graphql code in codecov.

What can i do?
Please help me!

**Comment by stevepeak** [comment]
Hey! Did you change the token so that new uploads go to the right project?

I'm unclear what action you would like us to take on the older commits.

Thank you,
Steve

**Comment by angeloocana** [comment]
Thanks steve for the quick reply!
Yes, I fixed the tokens, but the code on codecov did not change =/

This page keeps showing the code from the other project:
https://codecov.io/gh/polutz/ptz-user-domain/tree/master/dist
and a message: 'Unable to retrieve commit from GitHub API.'

What should i do?
I tried deleting the repo from codecov, but it comes back in the same way.

**Comment by angeloocana** [comment]
NOW IT'S WORKING!!!
I dont know why, but thank you!!!

**Comment by stevepeak** [comment]
Oh, cool! 👍 Happy to help out!
