### ISSUE TITLE
Create flags when using codecov-node or codecov-ruby

### ISSUE THREAD

**Issue by allenwq** [codecov/support#372]
Seems this is no API to create flags if we are using codecov-node or codecov-ruby ?

Then i need to use the bash uploader, but the issue of bash uploader is that it treats comments (ruby) as not covered code.

Any ideas ? Thanks in advance !

**Comment by stevepeak** [comment]
Hey! You can use the environment variables to include flags in **Ruby**.

```
CODECOV_FLAGS=this
CODECOV_FLAGS=this,that
```

> Node support coming very soon.

Thank you,
Steve

**Comment by allenwq** [comment]
@stevepeak Thanks for confirming !

I know the ruby one by reading the source :(

Hope node one will come soon.
