### ISSUE TITLE
Totally wrong coverage view on master

### ISSUE THREAD

**Issue by skirpichev** [codecov/support#375]
Take look on [this](https://codecov.io/gh/diofant/diofant/src/master/diofant/functions/special/gamma_functions.py), for example.  Here lines of some docstrings are marked as uncovered(red), e.g. [L53](https://codecov.io/gh/diofant/diofant/src/master/diofant/functions/special/gamma_functions.py#L53).  Or some [blank lines](https://codecov.io/gh/diofant/diofant/src/master/diofant/functions/special/gamma_functions.py#L464).  Also, directory view shows that there is no uncovered lines in this file...

Same happens for other files, e.g. [this](https://codecov.io/gh/diofant/diofant/src/master/diofant/functions/special/error_functions.py).  I restarted build on master, but this doesn't fix the problem.

**Comment by stevepeak** [comment]
@skirpichev according to the coverage reports: Codecov is accurate

```xml
<class branch-rate="0.4202" complexity="0" filename="diofant/functions/special/gamma_functions.py" line-rate="0.5238" name="gamma_functions.py">
					<methods/>
					<lines>
						<line hits="1" number="1"/>
						<line hits="1" number="3"/>
						<line hits="1" number="5"/>
						<line hits="1" number="6"/>
						<line hits="1" number="7"/>
```

https://codecov.s3.amazonaws.com/v4/raw/2017-03-25/4423A5DE0B6C709E72AD9ECEBF4644F4/58b068a88f0c0b7219c5a0096896cf13a8e90397/774ff7e5-83e6-4add-8728-1fa14655c772.txt

**Comment by skirpichev** [comment]
@stevepeak, I'm not looking on raw data.  Please examine the html reports, referenced above.  For instance, below is a screenshot for L53 link:
![1](https://cloud.githubusercontent.com/assets/2155800/24322681/acce29b6-1182-11e7-8c76-587d0913782b.png)

**Comment by stevepeak** [comment]
@skirpichev Checking it out. Thank you

**Comment by stevepeak** [comment]
Ok. Figured it out. Deploying fix now. Thank you!!!

> Issue was due to new aggressive caching system. Only impacted viewing source files because the cached details were not pulled out of cache properly and therefore used the wrong overlay details.

Thank you so much for your patience and help.

**Comment by stevepeak** [comment]
Fixed 👍

**Comment by skirpichev** [comment]
@stevepeak, thank you!

**Comment by jessesnyder** [comment]
@stevepeak  I'm seeing this problem with version 2.0.9. See for example:
https://codecov.io/gh/Dallinger/Dallinger/src/features%2F662-better-qualify/dallinger/command_line.py#L739
