### ISSUE TITLE
"CI Failed" false negative with wercker CI

### ISSUE THREAD

**Issue by javierfernandes** [codecov/support#382]
Hi guys !

We have an issue in the integration between GH + CodeCov + Wercker.
When building a PR Wercker built fine, but codecov integration with GH tells us that the build failed because of "CI Failed".

Here is the sample commit

https://codecov.io/gh/SCVLabs/nes-backend/commit/0ec2a0c076270e1b9b0da6a780374d0f7dbffbf8/builds

A screenshot in case you cannot see it

![image](https://cloud.githubusercontent.com/assets/4428120/24754828/56b475d2-1aae-11e7-90be-c47b140a8979.png)

Now if we click on "View CI Build", we can see that wercker build was fine

![image](https://cloud.githubusercontent.com/assets/4428120/24754852/70d3a32a-1aae-11e7-9241-c63a1232941f.png)

I workarounded it by following this other issue recommendation

https://github.com/codecov/support/issues/257

But I'm not sure which side effects that has. Does it remove the codecov + wercker integration ? and some features ?

Thanks !

**Comment by stevepeak** [comment]
Hey :) Thank you for pointing this out. Looks like the Wercker CI statuses are not being identified properly.

I'll fix and deploy today.
