### ISSUE TITLE
Unable to determine a parent commit to compare against.

### ISSUE THREAD

**Issue by junghans** [codecov/support#383]
I have see that a couple of time, e.g.:
https://codecov.io/gh/quinoacomputing/quinoa/commit/9e262426735ed2b64df208f83e4087c93ee77be1
even though the parent (https://codecov.io/gh/quinoacomputing/quinoa/commit/46af906b44173b822783972c63b7e38febac3adc) has a report.

**Comment by stevepeak** [comment]
I believe the issue here is due to the commits being back to back and the CI checks and/or processing lagging.

I'll need to review this concept more since it is a tricky process.

**Comment by stevepeak** [comment]
I updated the query concerning direct parent matching. Ping me if the issue comes up again 👍

**Comment by jedwards1211** [comment]
This happened to me here: https://codecov.io/gh/jcoreio/superquery/commit/023ee7b52c10538293a35c552268d2e02faad9c7

Why should this ever mark the commit as failed in GitHub?
