### ISSUE TITLE
Provide a way to get more decimal places on the badge?

### ISSUE THREAD

**Issue by nedbat** [codecov/support#384]
I'm at the point in my project (coverage.py!) of making tiny incremental changes. Is there a way to get two decimal places on the badge?

**Comment by stevepeak** [comment]
Great question! I believe we have some work on this, but need to review this more to give you specific details. Nonetheless, if it is not supported I'll add it.

**Comment by stevepeak** [comment]
I'll have this deployed today. Please add `badge.svg?precision=2` to the badge endpoint.
Thank you!

**Comment by nedbat** [comment]
Thanks! No sign of it yet, but I'm sure a deploy soon will bring it to the surface.
