### ISSUE TITLE
[Feature Request] Reduce noise in PR comments

### ISSUE THREAD

**Issue by wibosco** [codecov/support#389]
At the moment, at it's smallest the codecov comment looks like:

<img width="845" alt="screen shot 2017-04-13 at 13 34 33" src="https://cloud.githubusercontent.com/assets/649456/25004807/07bb2c46-204e-11e7-9a9f-7466b61f0fbe.png">

As you can see it contains Legend information about something that isn't being shown in the PR comment. Could this be removed to reduce the amount noise in the comment?

Ideally (for me) the most minimum comment should contain the code coverage change and a link to get more information, similar to what you see with coveralls comment:

<img width="798" alt="screen shot 2017-04-13 at 13 39 42" src="https://cloud.githubusercontent.com/assets/649456/25004950/be6003fe-204e-11e7-83bb-80ab17b56a0b.png">

**Comment by stevepeak** [comment]
You would like to reduce the footer essentially? I can arrange that.

However, you will lose the `Last updated` and legend.

**Comment by stevepeak** [comment]
I'll add `footer` to the comment layout. You should set this in your aml:

```yaml
comment:
  layout: "header"
```

> Will deploy soon.

**Comment by wibosco** [comment]
@stevepeak that would be great - thanks for getting back so quickly and making the change, it's very impressive.

**Comment by stevepeak** [comment]
Thanks 😃 It should be deployed today or tomorrow at the latest. Cheers!
