### ISSUE TITLE
Incorrect coverage results

### ISSUE THREAD

**Issue by sbuberl** [codecov/support#392]
Hello,

I have like 20 of so class files being tested.  I was like 48% last time I checked.  I haven't worked on the repo in a while.  Yesterday, I committed 3 line diff for a bug fix and my overall coverage dropped 14.3%:

https://codecov.io/gh/sbuberl/fSQL/commit/b5540905c760d358899253813537131d9219f973

And this file for example says 4% when it should be 100%:
https://codecov.io/gh/sbuberl/fSQL/src/master/src/File.php

I have no idea what's up with this changelog between that commit and previous one:
https://codecov.io/gh/sbuberl/fSQL/compare/570fd4964bd36ee7a123450e74964d36c352fc68...b5540905c760d358899253813537131d9219f973/changes

And nothing changed on my end as far as I know.  Same version of testing framework.  Same Travis setup.

Any help would be appreciated.

**Comment by sbuberl** [comment]
Since no response in a month, any way to purge the old coverage data?   I tried deleting/removing the repo on codecov and adding it back.  But the data is still there no matter how long I wait.

**Comment by stevepeak** [comment]
> Sorry for the delay. We prioritize GH issues last, atm.

Can you please chat with us in Intercom (in-app chat) to get help on your project. 
Please provide a new commit sha that we can review. Thank you!
