### ISSUE TITLE
Code coverage not updated for Resharper detailed xml file

### ISSUE THREAD

**Issue by smatsson** [codecov/support#393]
Hi! 

I saw that you recently added support for Resharper's detailed xml reports which is awesome! OpenCover does not yet support .NET Core projects (in csproj format) but Resharper does so thanks for this :) 

I'm having a bit of a problem with it though and I'm not sure if I'm doing something wrong. I tried to upload the detailed xml report using the Codecov upload script (version 910f204) and it says that everything is OK but the stats on https://codecov.io/github/smatsson/tusdotnet/ are not updated. The result that is there is from before when I tried using OpenCover resulting in only the test-project being covered.

Any ideas on how to solve it? Below is the output from the upload script and attached is the results.xml file from Resharper. [results.xml.txt](https://github.com/codecov/support/files/925452/results.xml.txt)

```
$ ./CodeCovUploader.sh -t <removed> -f results.xml

  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                              Bash-910f204


x> No CI provider detected.
    Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
    Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-t     ox
    project root: C:/Repos/tusdotnet/tusdotnet
    Yaml not found, that's ok! Learn more at http://docs.codecov.io/docs/codecov     -yaml
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + results.xml bytes=869425
==> Uploading reports
    url: https://codecov.io
    query: branch=master&commit=199a904ba8bf9939060cabdd8bcf2ce6d43bd21b&build=&     build_url=&name=&tag=&slug=smatsson%2Ftusdotnet&yaml=&service=&flags=&pr=&job=
    -> Pinging Codecov
    -> Uploading to S3 https://codecov.s3.amazonaws.com
    -> View reports at https://codecov.io/github/smatsson/tusdotnet/commit/199a9     04ba8bf9939060cabdd8bcf2ce6d43bd21b
```

**Comment by stevepeak** [comment]
Thank you for your patience. Have you tried this again recently? The newest commit on this project is 5 months ago.

**Comment by stevepeak** [comment]
Repository specific issues are best handled in our in-app chat or [Slack](slack.codecov.io)
