### ISSUE TITLE
"chat with out team" doesn't work

### ISSUE THREAD

**Issue by nschloe** [codecov/support#395]
The _Woops_ pages say

>  Need some help? No problem. Chat with our team.

(e.g., [here](https://codecov.io/github/nschloe/meshio/commit/c94f25ee72cfffdd7f2165b3a5494cb1a97e3716)), but clicking the link doesn't do anything.

This is on Chrome 57.0.2987.133 (64-bit).

**Comment by nic-hartley** [comment]
Sorta-repro, same build. Are you middle-clicking? If you just left-click, it works for me; middle-clicking does nothing.

**Comment by nschloe** [comment]
Nope, I'm left-clicking. The console says
```
GET https://widget.intercom.io/widget/nxdkbgzj net::ERR_BLOCKED_BY_CLIENT
l @ c94f25e…:700
```
– perhaps that's related.

**Comment by stevepeak** [comment]
Thank you for reporting. Fixing now.

**Comment by stevepeak** [comment]
Deploying soon.
