### ISSUE TITLE
How to enable Codecov to post comments in pull requests for Bitbucket

### ISSUE THREAD

**Issue by eman6576** [codecov/support#398]
Hello again,

I was wondering how to enable comments for pull requests in Bitbucket. I noticed that when a pull request is created and our CI finishes running and sending the coverage reports to Codecov, no comments appear. Also the build status shows only CI and not Codecov. I also added a `codecov.yml` file and added the comment part to see if that will work. Doing that didn't affect anything. The `codecov.yml` file is valid when running the validation script. Is there any settings that need to be set? We already have an account with Codecov and the account registered does comment on all pull requests for our backend.

**Comment by stevepeak** [comment]
Hey :) By default Codecov will post comments on Bitbucket pull requests. Can you send me a pull request link in Bitbucket that did not get a comment. I'll debug from there. Thank you!

**Comment by eman6576** [comment]
Here is a link to a pull request that ran successfully: https://bitbucket.org/silverlogic/baseapp-ios-v2/pull-requests/43/ba-554-coredatastack-insertion-and/diff .

**Comment by stevepeak** [comment]
Hey, sorry for the delay. When you open another pull request can you ping me so I can investigate more. Thank yoU@!

**Comment by stevepeak** [comment]
Please contact us through our In-App messagner or [Slack](http://slack.codecov.io). Thank you
