### ISSUE TITLE
File looks completely covered, but codecov says it's ~36% covered

### ISSUE THREAD

**Issue by marco-c** [codecov/support#400]
https://codecov.io/gh/marco-c/crashsimilarity/src/c2c30a5fabc4a55a21626aafdac40cf7b198e677/crashsimilarity/utils.py

**Comment by stevepeak** [comment]
Hey Marco,

In the [upload](https://codecov.s3.amazonaws.com/v4/raw/2017-04-21/D9A21A23B61E6AB853E116D8045C8899/c2c30a5fabc4a55a21626aafdac40cf7b198e677/eccbfcad-472a-44bb-99cd-566c1472065f.txt) there are site-package files that are being joined into your project. I suggest removing site-packages by declaring ignore patterns in your [.coveragerc](https://coverage.readthedocs.io/en/latest/config.html)

Thank you!

**Comment by marco-c** [comment]
Thanks, looks good now.
