### ISSUE TITLE
how can I re-create codecov webhook in my private organization?

### ISSUE THREAD

**Issue by eddedd88** [codecov/support#401]
The webhook that codecov created in my organization was deleted and I can't figure out how to create it again.

**Comment by stevepeak** [comment]
Happy to help out! Webhooks are on repositories only. 👍 
`https://codecov.io/gh/OWNER/REPO/settings` to reset the hook.
If you are using the [GitHub Integration](https://github.com/integration/codecov) - the webhooks are managed automatically.

**Comment by eddedd88** [comment]
Should I be seeing a codecov webhook in my repo? Or this webhook not necessary? Because I don't see a codecov webhook in my repo.

When I first installed the Github integration,the webhook was there, but then I mistakenly deleted it from the repo manually. I tried uninstalling and re-installing the Github integration but the webhook is still not showing

**Comment by stevepeak** [comment]
When using the Github integration you will not see a webhook in your project settings on Github. The webhook is managed by the integration itself.

**Comment by eddedd88** [comment]
Gotcha, thanks a lot for the quick response, really appreciate it
