### ISSUE TITLE
Monorepo + docker?

### ISSUE THREAD

**Issue by beaugunderson** [codecov/support#403]
We have a monorepo and we also use docker.

I've seen the instructions for manually uploading multiple coverage reports, which is fine.

But I can't figure out how to get the file paths to match up correctly.

Every docker container has its tests run from a directory called `/app`, but those are all actually subdirectories of the monorepo. I don't see a relevant codecov-bash option, and the yaml `fixes` array seems to require differentiated paths to be useful.

**Comment by stevepeak** [comment]
Happy to help out!

```yaml
fixes:
  - "app/::"  # remove app/ from all paths
```

> http://docs.codecov.io/docs/testing-with-docker
> https://docs.codecov.io/docs/fixing-paths

If you link me to a commit in Codecov I can help out without guessing 👍

**Comment by beaugunderson** [comment]
@stevepeak the issue is within `/app` in the docker only the application files for that sub-project of the monorepo exist, so they end up in the root of the codecov report.

See [this commit](https://codecov.io/gh/canvas-medical/canvas/tree/0f85abfa61855e0b16c685b6ea1b915f5e7f4eaa), for example.

(Both `app` and `surescripts` and the files at the root in that commit exist under `/app` in the docker container, e.g. `1/app/app`, `/app/surescripts`, etc.).

**Comment by beaugunderson** [comment]
To be more explicit:

I have the monorepo cloned to:

- `~/p/canvas/`

One project that I want to run tests on is at:

- `~/p/canvas/pharmacy/`

When I run the tests within a docker container, the files from `~/p/canvas/pharmacy/*` are at `/app/*` within the docker container.

I'd like the coverage data for those files to be within `/pharmacy/` in the coverage report. :)

**Comment by beaugunderson** [comment]
The issue with rewriting `/app/` to `/pharmacy/` in the `codecov.yml` is that we use `/app/` within the container for every project, so it's not unique. I tried playing with renaming or creating a symlink from `/app/` to `/pharmacy/` inside the docker container as part of the test-running process but quickly got out of my depth in terms of the internals of `codecov-bash`. :)

**Comment by stevepeak** [comment]
Let's chat this out :) http://slack.codecov.io ping `@steve`
Thanks!
