### ISSUE TITLE
Comparing branch in Tree view

### ISSUE THREAD

**Issue by alyyousuf7** [codecov/support#404]
I have two branches, **master** and **feat/somework** (with a slash in it).

When I compare these two branches (the **Files** tab):
`https://codecov.io/gh/myusername/myrepo/compare/master...feat/somework/tree`

And click a directory, named **abc**, it replaces the slash in **feat/somework** with **%252F** in the URL and it doesn't show any file under that directory.
`https://codecov.io/gh/myusername/myrepo/compare/master...feat%252Fsomework/tree?path=abc`

I have to manually replace **%252F** with a slash and then it works.

**Comment by stevepeak** [comment]
Nice discovery. Looks like it's escaping the `%` => `%25`. I'll fix this up now. Thank you!

**Comment by stevepeak** [comment]
Deploying shortly. Thank you
