### ISSUE TITLE
Have to run Travis-CI twice to get report on PR

### ISSUE THREAD

**Issue by roversch** [codecov/support#405]
I see a slightly weird behavior from Codecov: whenever I try to merge a pull request (e.g. `Merge pull request #77 from myrepo/whatever`), I get an error message like this, even if all tests pass and `codecov-bash` says it did its job correctly:

<img width="826" alt="screen shot 2017-05-10 at 09 09 05" src="https://cloud.githubusercontent.com/assets/1436556/25911287/1e0ad440-3568-11e7-88f3-08c2f2af0791.png">

If I then re-run Travis-CI (without pushing any code), the reports get generated correctly.

I should say that I only run `codecov` on one entry (out of four) in the build matrix.

**Comment by roversch** [comment]
It also gives me this option: 

`Notifications are pending CI completion. Waiting for GitHub's status webhook to queue notifications. Push notifications now.`

**Comment by stevepeak** [comment]
Can you link me to the commit in Codecov - I'll review the uploaded reports which are found by clicking the **Download** button in the logs.

**Comment by roversch** [comment]
Sorry for getting back so late, but this issue came up again today, exactly same error message as above. Different cause though: this time, it was by pushing an edit to `README.md` from the Github web interface. Please have a look at [this codecov report](https://codecov.io/gh/acados/acados/commit/d7838edcebd4a3ec8d613763d614b0591a037681). 

From [this Travis build](https://travis-ci.org/acados/acados/jobs/238879522), it seems everything is fine though. Could the issue be caused because I only run `codecov` on one build in the build matrix?

**Comment by stevepeak** [comment]
This is really odd... I see the gcov reports processed and added, but they do not end up in the loaded report. First I've ever seen this.

E.g., this [upload](https://codecov.io/github/archive/v4/raw/2017-06-02/549A6AFBE1FB8A4B6247988D8CCDBA23/d7838edcebd4a3ec8d613763d614b0591a037681/fcdc41ae-f6a9-4cad-82e0-346314aefac6.txt) does not contain any `gcov` reports. 

Can you run a build with `-v -d` to get a verbose logs and dump to stdout to see if report content is properly being collected.

**Comment by roversch** [comment]
I did that [here](https://api.travis-ci.org/jobs/242179423/log.txt?deansi=true), but the log is incomplete, due to Travis limits..

**Comment by stevepeak** [comment]
@roversch I'm so confused why the reports are not being included in the upload. This is the first time I've seen this.

Have your tried to debug locally?

**Comment by roversch** [comment]
When I run it locally with -v -d, I get

+ say '    \033[0;31mX> Failed to upload coverage reports\033[0m'

+ echo -e '    \033[0;31mX> Failed to upload coverage reports\033[0m'

    X> Failed to upload coverage reports

+ exit 0

**Comment by roversch** [comment]
@stevepeak I ran a diff on the passing and failing Travis output, and I notice this when the reports are _empty_ (repeated for each file):

    /home/travis/build/.../ocp_qp_ooqp.c.gcda:stamp mismatch with notes file

**Comment by roversch** [comment]
I think I found the issue. It's because I recompile some code after the coverage data is created (see https://github.com/cb-geo/lbm-dem/issues/1 ).
