### ISSUE TITLE
CodeCov.io UI does not state that codecov.yml should be on master

### ISSUE THREAD

**Issue by mpsijm** [codecov/support#406]
Hey guys,

I was trying to get my (private) repository to display coverage results, but I had a hard time configuring my Slack notifications, because CodeCov would not recognize the `.codecov.yml` we have in our repository. (Note: we use feature branches that get PRs into a develop branch, and once every sprint `dev` gets merged into `master`. The YAML file resided on a feature branch.)
Later, I found out that the YAML file should be on the master branch. I had to search old issues in this support repo to find this out. This resulted into two questions for me:

1. Why does the UI nor the documentation state that this file has to be on the `master` branch?
2. Why should the YAML file reside on the master branch anyway? Why isn't it possible to use the YAML file that belongs to the branch of the commit of which the coverage is being displayed?

Anyway, I'm glad we finally got everything to work, thank you guys for creating this awesome tool :smile: 
Thanks in advance for your response!

**Comment by stevepeak** [comment]
Hey @mpsijm Happy to help out! The issue could have been the name of the file. Codecov will always use the commit codecov.yml version that is being tested.

What is the `owner/repo` name? Thank you!

**Comment by mpsijm** [comment]
Hey Steve,

The name of the file is (copy-pasted) `.codecov.yml`, so I'm guessing that's not the issue here.
I only have one repo on my name registered at CodeCov, so you will probably find it easily :slightly_smiling_face: 
The branch containing the correct configuration (afaik, of course) is named `3-code-coverage-tool-3`.

Thanks for helping! :slightly_smiling_face:

**Comment by mpsijm** [comment]
Hey Steve,

Overnight we didn't change anything, and fifteen minutes ago we suddenly got a Slack notification from Codecov's webhook about the latest commit! So the configuration works now :smile: :tada:
