### ISSUE TITLE
status.codecov.io: HTTPS 

### ISSUE THREAD

**Issue by nschloe** [codecov/support#407]
There's a certificate error on https://status.codecov.io (which I just tried ot visit for the first time -- Chrome won't allow me though b/c of the error).

See https://www.ssllabs.com/ssltest/analyze.html?d=status.codecov.io&s=104.192.142.99&ignoreMismatch=on&latest.

**Comment by stevepeak** [comment]
Thank you! Fixing the status page to HTTP now.
