### ISSUE TITLE
File displayed on codecov.io that does not exist in the repo?

### ISSUE THREAD

**Issue by fd0** [codecov/support#409]
Hi,

as discussed [in the Gitter channel](https://gitter.im/codecov/support?at=5910b8ffc4d73f445a87b96b), we have some problems displaying and browsing the [restic](https://github.com/restic/restic) coverage information online: There's a file called `sftp.go` that's displayed in the root directory which does not exist in the repo: https://codecov.io/gh/restic/restic. Clicking on the file returns a 404: https://codecov.io/gh/restic/restic/src/master/sftp.go. So, something seems to be off here.

I've left this issue to track progress asynchronously, because I'm only seldom online in the Gitter channel.

Thank you very much for your support for Free Software projects!

Cheers,
Alex

**Comment by stevepeak** [comment]
Hey @fd0 Thank you for your patience. Can you add a Codecov.yml with the following:

```yaml
codecov:
  disable_default_path_fixes: true
```

This won't be required after we improve our path resolving.

**Comment by fd0** [comment]
Hm, does not look like that works: https://codecov.io/gh/restic/restic/tree/4640d1a28e55991e02109344024a66a658b1450f

The files there are not clickable...

**Comment by fd0** [comment]
So, anything else I can do?

**Comment by fd0** [comment]
At the moment it's not working at all, just an infinite redirect :/

**Comment by stevepeak** [comment]
Hey @fd0 I'm on it.

**Comment by stevepeak** [comment]
Can you remove the `disable_default_path_fixes: true` now that we have resolved this issue in our backend. Then submit a new build to Codecov. 
Thanks!

**Comment by fd0** [comment]
Will do later today, thanks!

**Comment by fd0** [comment]
submitted as https://github.com/restic/restic/pull/997

**Comment by fd0** [comment]
here's a PR without the config setting: https://github.com/restic/restic/pull/1002

**Comment by fd0** [comment]
There are still errors: Files are listed which do not exist (in that path) and I cannot click on them, e.g. the the `swift.go` and `sftp.go` in the top level here: https://codecov.io/gh/restic/restic/pull/1002/tree

**Comment by fd0** [comment]
So, anything else I can do? At the moment using codecov is really annoying for me: It marks PRs as having failed because the coverage dropped by an insignificant proportion, but I cannot figure out why it thinks that (e.g. [here](https://github.com/restic/restic/pull/999)).

If there's anything else I can do to help, please let me know!

**Comment by stevepeak** [comment]
@fd0 Can you book a chat with me to review this together. https://calendly.com/codecov/chat Well get this all sorted out.

**Comment by fd0** [comment]
Will do, great idea!

**Comment by fd0** [comment]
FYI: The slack invite website at https://slack.codecov.io/ reports an error `token revoked!`...

**Comment by fd0** [comment]
I still cannot register on the codecov slack, shall we do that on gitter.im?

**Comment by stevepeak** [comment]
Fixed the Slack 👍  - Can you join there to chat. Thanks

**Comment by fd0** [comment]
Done, ready when you are.

**Comment by fd0** [comment]
This is resolved, thank you very much for your support!
