### ISSUE TITLE
no-reports-generated error although Travis CI seems OK

### ISSUE THREAD

**Issue by tkrotoff** [codecov/support#411]
I have a somewhat similar issue to #405:

```
  2017-05-29T23:03:17+02:00 upload  no-reports-generated  error=Error   
  2017-05-29T23:03:17+02:00 upload  Processed file name=lcov.info language=lcov   
  2017-05-29T23:03:17+02:00 upload  Processed file name=clover.xml language=clover   
  2017-05-29T23:03:17+02:00 upload  Upload archived download   
  2017-05-29T23:03:17+02:00 upload  GET /repos/tkrotoff/ReactFormWithConstraints/contents/codecov.yml bot=tkrotoff code=404  
      {"message":"Not Found","documentation_url":"https://developer.github.com/v3"}    
  2017-05-29T23:03:11+02:00  Upload accepted ci=travis build=13.1   
  2017-05-29T20:14:02+02:00 upload  no-reports-generated  error=Error   
  2017-05-29T20:14:02+02:00 upload  Processed file name=lcov.info language=lcov   
  2017-05-29T20:14:02+02:00 upload  Processed file name=clover.xml language=clover   
  2017-05-29T20:14:02+02:00 upload  Upload archived download   
  2017-05-29T20:13:57+02:00 upload  
```
See https://codecov.io/gh/tkrotoff/ReactFormWithConstraints/commit/aaf3e8eaf16e466cb7bf0fa08585fb41ede7cef5

Travis CI seems to be OK:
https://travis-ci.org/tkrotoff/ReactFormWithConstraints/builds/237254360

```
  _____          _  
 / ____|        | |  
| |     ___   __| | ___  ___ _____   __  
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /  
| |___| (_) | (_| |  __/ (_| (_) \ V /  
 \_____\___/ \__,_|\___|\___\___/ \_/  
                                v2.2.0
==> Detecting CI Provider
    Travis CI Detected
==> Configuration: 
    Endpoint: https://codecov.io
{ service: 'travis',
  commit: 'aaf3e8eaf16e466cb7bf0fa08585fb41ede7cef5',
  build: '13.1',
  branch: 'master',
  job: '237254361',
  pr: 'false',
  slug: 'tkrotoff/ReactFormWithConstraints',
  root: '/home/travis/build/tkrotoff/ReactFormWithConstraints',
  package: 'node-v2.2.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find /home/travis/build/tkrotoff/ReactFormWithConstraints -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + /home/travis/build/tkrotoff/ReactFormWithConstraints/coverage/clover.xml
    + /home/travis/build/tkrotoff/ReactFormWithConstraints/coverage/lcov.info
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/tkrotoff/ReactFormWithConstraints/commit/aaf3e8eaf16e466cb7bf0fa08585fb41ede7cef5
```

GitHub repository: https://github.com/tkrotoff/ReactFormWithConstraints
Commit that adds codecov support: https://github.com/tkrotoff/ReactFormWithConstraints/commit/aaf3e8eaf16e466cb7bf0fa08585fb41ede7cef5

**Comment by stevepeak** [comment]
Looks like the file network (`git ls-files`) are quite incomplete. We use this list to map files back to their rightful place.

When you run Codecov is it ran from the git project directory?
Do you change the git structure of the project at all?

**Comment by tkrotoff** [comment]
This is what `git ls-files` gives me ([this is a small React project](https://github.com/tkrotoff/ReactFormWithConstraints)):
```
$ git ls-files
.gitignore
.npmignore
.travis.yml
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
README.md
dist/.gitkeep
doc/demo-password.png
doc/email.html
doc/input-required.png
doc/input-type-email.png
examples/HttpStatusCode/App.tsx
examples/HttpStatusCode/index.html
examples/HttpStatusCode/style.css
examples/MDN_Form_validation/App.tsx
examples/MDN_Form_validation/index.html
examples/MDN_Form_validation/style.css
examples/NativeFormWidgets/App.tsx
examples/NativeFormWidgets/index.html
examples/NativeFormWidgets/my-img.png
examples/moduscreate/App.jsx
examples/moduscreate/index.html
examples/password/App.tsx
examples/password/index.html
examples/password/style.css
index.ts
package.json
src/Bootstrap4Helpers.tsx
src/FormWithConstraints.test.tsx
src/FormWithConstraints.tsx
tsconfig.json
tslint.json
webpack.config.ts
```

It fails with both Travis CI and when running `node --trace-warnings node_modules/.bin/jest --no-cache --coverage && codecov -t xxx` locally.

Each time it says everything is OK (both Travis CI and locally):
```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                                v2.2.0
==> Detecting CI Provider
    No CI Detected. Using git/mercurial
==> Configuration:
    Endpoint: https://codecov.io
{ commit: 'aaf3e8eaf16e466cb7bf0fa08585fb41ede7cef5',
  branch: 'master',
  token: 'xxx',
  package: 'node-v2.2.0' }
==> Building file structure
==> Generating gcov reports (skip via --disable=gcov)
    $ find . -type f -name '*.gcno'  -exec gcov  {} +
==> Scanning for reports
    + ./coverage/lcov.info
    + ./coverage/clover.xml
==> Uploading reports
    Success!
    View report at: https://codecov.io/github/tkrotoff/ReactFormWithConstraints/commit/aaf3e8eaf16e466cb7bf0fa08585fb41ede7cef5
✨  Done in 9.28s.
```
and https://codecov.io/github/tkrotoff/ReactFormWithConstraints/commit/aaf3e8eaf16e466cb7bf0fa08585fb41ede7cef5 does not show the report.

I don't have a `codecov.yml` file (shouldn't be needed in my case).
The `coverage` directory generated by Jest is OK and I can read the HTML report:

![Coverage directory](https://cloud.githubusercontent.com/assets/643434/26587675/45b985a4-4553-11e7-9773-e9b1f00cacbe.png)

![Coverage HTML report](https://cloud.githubusercontent.com/assets/643434/26587761/88879204-4553-11e7-8290-d0b254fbdc3e.png)

What do you mean by
> Do you change the git structure of the project at all?

There is nothing fancy. Code is written in TypeScript (src directory) and compiled to dist and lib directories. Coverage report is inside the default coverage directory.
dist, lib and coverage directories are git ignored.

**Comment by stevepeak** [comment]
This is because `FormWithConstraints.js` does not exist in your `git ls-files`.

Please use source mapping to map the coverage back to your `ts` files.

https://github.com/codecov/example-typescript#frequently-asked-questions

**Comment by tkrotoff** [comment]
> FormWithConstraints.js does not exist in your git ls-files

Do you suggest to git commit the compiled files? Your [example](https://github.com/codecov/example-typescript) does not and [git ignore them](https://github.com/codecov/example-typescript/blob/ffa68f95e278ab3b4731289d3d5e7bec00c9c09e/.gitignore#L38) like [me](https://github.com/tkrotoff/ReactFormWithConstraints/blob/v0.2.3/.gitignore#L5).

If I understand well codecov cannot generate a report only based on what is inside the coverage directory?

> use source mapping to map the coverage back to your ts files

This is already what [I do](https://github.com/tkrotoff/ReactFormWithConstraints/blob/v0.2.3/tsconfig.json#L9), same as your [example](https://github.com/codecov/example-typescript/blob/ffa68f95e278ab3b4731289d3d5e7bec00c9c09e/tsconfig.json#L3).

![screen shot 2017-06-01 at 12 06 14](https://cloud.githubusercontent.com/assets/643434/26675063/c0afe3aa-46c2-11e7-8f45-a5530078655e.png)

**Comment by Tim-W** [comment]
I'm having the same issue using OpenCover for a C# project. 

CodeCov log: 
```
  2017-06-08T13:16:09+02:00 upload  no-reports-generated  error=Error   
  2017-06-08T13:15:50+02:00 upload  Processed file name=coverage.xml language=csharp   
  2017-06-08T13:15:35+02:00 upload  Upload archived download   
  2017-06-08T13:15:18+02:00 upload  
WAITING FOR CI TO COMPLETE
   
  2017-06-08T13:15:13+02:00 upload  
WAITING FOR CI TO COMPLETE
   
  2017-06-08T13:15:07+02:00 upload  
WAITING FOR CI TO COMPLETE
   
  2017-06-08T13:15:07+02:00 upload  GET /search/issues?q=e43f8fdd1c12ac088caa0a6e9c288a683f54aa04+repo:Tim-W%2FVR-The-Champions+type:pr+state:open bot=Tim-W code=200  ratelimit=29/30 reset=1496920567     
  2017-06-08T13:15:07+02:00 upload  GET /repos/Tim-W/VR-The-Champions/commits/e43f8fdd1c12ac088caa0a6e9c288a683f54aa04 bot=Tim-W code=200     
  2017-06-08T13:15:07+02:00 upload  GET /repos/Tim-W/VR-The-Champions/contents/codecov.yml bot=Tim-W code=200     
  2017-06-08T13:15:06+02:00  Upload accepted ci=appveyor build=ws7um7pixe6wdja6   
```

AppVeyor build log (shows no errors):
```
codecov -f "coverage.xml" -t 99592183-e950-4dd7-865a-1a1de108c9f2
File not found - '*.gcno'
      _____          _
     / ____|        | |
    | |     ___   __| | ___  ___ _____   __
    | |    / _ \ / _  |/ _ \/ __/ _ \ \ / /
    | |___| (_) | (_| |  __/ (_| (_) \ V /
     \_____\___/ \____|\___|\___\___/ \_/
                                    v2.0.9
==> Detecting CI provider
    AppVeyor Detected
==> Preparing upload
==> Processing gcov (disable by -X gcov)
    Executing gcov (find C:\projects\vr-the-champions -type f -name '*.gcno'  -exec gcov -pb  {} +)
    Error running `find C:\projects\vr-the-champions -type f -name '*.gcno'  -exec gcov -pb  {} +`: None
==> Collecting reports
XX> Searching for reports disabled
    Targeting specific files
    + coverage.xml bytes=2135
==> Uploading
    .url https://codecov.io
    .query service=appveyor&package=py2.0.9&job=Tim-W%2Fvr-the-champions%2F1.0.30&token=<secret>&build=qg4eml5w7y088p7f&branch=master&commit=710244c3bb9e2a692d063effd64b225d4ef3d3d7&slug=Tim-W%2FVR-The-Champions
    Pinging Codecov...
    Uploading to S3...
    https://codecov.io/github/Tim-W/VR-The-Champions/commit/710244c3bb9e2a692d063effd64b225d4ef3d3d7
```

**Comment by stevepeak** [comment]
Please contact support directly through in-app messanger or slack.codecov.io for specific repository help. Thank you

**Comment by tkrotoff** [comment]
I've tried with `remap-istanbul` and still not working: https://github.com/tkrotoff/ReactFormWithConstraints/commit/7e469e04ed4a9bc38803754cf2416d32849cf39d

```JavaScript
// package.json
{
  "coverage:remap:json": "remap-istanbul --input coverage/coverage-final.json --type json --output coverage/coverage-final.json",
  "codecov": "node --trace-warnings node_modules/.bin/jest --no-cache --coverage && npm run coverage:remap:json && codecov"
}
```

Problem is that the message is _"Woops! There was an error processing coverage reports"_. You don't have a clue about why it failed.

**Comment by tkrotoff** [comment]
Manage to make it work, see https://github.com/codecov/example-typescript/issues/7

---


What you need to change in your code for it to work: https://github.com/tkrotoff/ReactFormWithConstraints/commit/b5817829141ea6b28e77a8eeaa6bdb1571dc495c

- Configure TypeScript to generate the source maps by adding [`"sourceMap": true`](https://www.typescriptlang.org/docs/handbook/compiler-options.html) to your [tsconfig.json](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html)
- Configure Jest so that it generates only `coverage-final.json` thanks to [`"coverageReporters": ["json"]`](http://facebook.github.io/jest/docs/en/configuration.html#coveragereporters-array-string). By default Jest generates everything including the HTML report (`lcov-report`) and `lcov.info`
- Then use remap-istanbul to rewrite `coverage-final.json` using the source maps
- And finally `istanbul report` to generate the right HTML report (`lcov-report`) and `lcov.info` from the correct `coverage-final.json`

Spent several hours on this trying to understand what meant _"Woops! There was an error processing coverage reports"_.

This blog post: https://medium.com/@novemberborn/code-coverage-with-babel-istanbul-nyc-83b8c2f1093 allowed me to understand.

**Comment by micksatana** [comment]
In case someone want to use remap-istanbul to solve this problem.

In `package.json` should contain something like this in the `"scripts"` attribute.
```
  "coverage": "istanbul cover node_modules/mocha/bin/_mocha -- -r ts-node/register test/**/*.spec.ts --exit",
  "coverage:remap": "remap-istanbul -i coverage/coverage.json -o coverage/coverage.json",
```

And in `.travis.yml`
```
language: node_js
node_js:
  - "8"
sudo: false
script:
  - npm run coverage
  - npm run coverage:remap
after_success:
  - npm run codecov
```
