### ISSUE TITLE
commit branches are "random"

### ISSUE THREAD

**Issue by ggeorgiev** [codecov/support#413]
The branches for particular commit is assigned at random. In git one sha could be in multiple branches. If commit is created in a feature or task branch and then merged to master the same sha will be at the same time in more than one branch.

Codecov seems to try to determine the branch with some kind of query, resulting in almost every sha shown in a different branch.

**Comment by stevepeak** [comment]
Branches are assigned based on the upload variables detected during your CI. It may be that your CI does not have a branch variable, in which case Codecov would try to find one.

Branches may change during pull request merging.

**Comment by ggeorgiev** [comment]
This is one example output

x> No CI provider detected.
    Testing inside Docker? http://docs.codecov.io/docs/testing-with-docker
    Testing with Tox? https://docs.codecov.io/docs/python#section-testing-with-tox
    project root: /go/src/github.com/peernova-private/cuneiform
    Yaml found at: codecov.yml
==> Running gcov in /go/src/github.com/peernova-private/cuneiform (disable via -X gcov)
==> Python coveragepy not found
==> Searching for coverage reports in:
    + /go/src/github.com/peernova-private/cuneiform
    -> Found 1 reports
==> Detecting git/mercurial file structure
==> Reading reports
    + /go/src/github.com/peernova-private/cuneiform/src/coverage.txt bytes=86985254
==> Appending adjustments
    http://docs.codecov.io/docs/fixing-reports
    + Found adjustments
==> Uploading reports
    url: https://codecov.io
    query: `branch=master`&commit=3f87cef95d407c1b3e91f237526c6ac8e1e90884&build=&build_url=&name=&tag=&slug=peernova-private%2Fcuneiform&yaml=codecov.yml&service=&flags=&pr=&job=
    -> Pinging Codecov
    -> Uploading to S3 https://codecov.s3.amazonaws.com
    -> View reports at https://codecov.io/github/peernova-private/cuneiform/commit/3f87cef95d407c1b3e91f237526c6ac8e1e90884


You can clearly see that the query sets the branch to master, but if you follow the link https://codecov.io/github/peernova-private/cuneiform/commit/3f87cef95d407c1b3e91f237526c6ac8e1e90884 you will see that it believes that it assumes that the branch should be `ying_config`
![screen shot 2017-08-17 at 4 38 12 pm](https://user-images.githubusercontent.com/1084892/29438288-8a2e7faa-836a-11e7-81c1-0c492b0e4a20.png)

**Comment by stevepeak** [comment]
Hey, we have a couple reports of this and are looking into why this is happening. Thank you for your patience.

**Comment by stevepeak** [comment]
Potential patch deployed. Please advise us if this occurs again.
