### ISSUE TITLE
Bug: Removing "final" Modifier From Java Interface Parameter Decreases Code Coverage

### ISSUE THREAD

**Issue by ykcilborw** [codecov/support#415]
Per https://stackoverflow.com/questions/5380177/final-arguments-in-interface-methods-whats-the-point, a final modifier on a method parameter is not mentioned in the rules for matching signatures of overridden methods. 

Consequently, removing the "final" modifier on a parameter in an interface should not decrease code coverage because the "final" is not being enforced in the first place.

However, when I use Codecov, it tells me the code coverage has decreased.

**Comment by stevepeak** [comment]
@ykcilborw Thank you for reporting this. Can you link me to a commit in Codecov that expresses this issue.

**Comment by ykcilborw** [comment]
https://codecov.io/gh/opentok/anvil/compare/783f0d8a4554fc867b0638bef0393b24b683b1e1...efa0eba55ef8a59b69668c083e098668f7dc3385
