### ISSUE TITLE
Hits/Misses Line Reporting is Incorrect

### ISSUE THREAD

**Issue by paltman** [codecov/support#418]
The coverage.py report that is uploaded looks like this for `organization/models.py`:

![](https://d26dzxoao6i3hh.cloudfront.net/items/0F3i0j19133D2w2R2s0X/Screen%20Shot%202017-06-29%20at%2012.36.44%20PM.png)

As you can see lines 1, 3, 4, 5, 6, 7 are "hits".

Yes, the reporting looks like:

![](https://d26dzxoao6i3hh.cloudfront.net/items/2M0n0Q0c1g0x2t3j3S0w/Screen%20Shot%202017-06-29%20at%2012.37.27%20PM.png)

It's clearly wrong:

* 2 is not a hit
* 4 is a hit but not highlighted
* 6 is a hit but not highlighted

It's as if CodeCov is parsing the XML report and applying the hit/miss to the wrong file.

---

_I have reported this issue to both Intercom and Slack support channels and haven't received any response. Posting it here in hope of a response but this also seems like a bug that needs to be filed._

**Comment by stevepeak** [comment]
There is a file simply called 

```
<class branch-rate="0.08333" complexity="0" filename="models.py" line-rate="0.5273" name="models.py">
					<methods/>
					<lines>
						<line hits="1" number="1"/>
						<line hits="1" number="2"/>
						<line hits="1" number="3"/>
```

That is being moved to mgh/organizations/models.py causing the issue.

Can you look into removing the extra files in your coverage.xml report? 

Thanks

**Comment by paltman** [comment]
@stevepeak thanks for your quick response.

That's not an extra file though. That's a top level `models.py` file that I'm also interested in tracking coverage on.

**Comment by paltman** [comment]
Well, I thought it was a top level `models.py` file.  Now I'm not sure where it's coming from.

**Comment by stevepeak** [comment]
How are you running coverage? The file paths do not line up to your project layout so Codecov tries to resolve, but appears to be doing it wrong.

**Comment by paltman** [comment]
Yeah, I'm just noticing that.  When I just run `coverage xml -i` and inspect the file I have the full paths that I would expect.

In my CI, I'm running:

```
coverage run --source mgh manage.py test mgh
```

inside `tox.ini`

and then in the Travis `after_success`, I'm running codecov with my token (I'm assuming this is running `coverage xml -i` but it seems perhaps to be doing some path translation?

**Comment by paltman** [comment]
Something seems to be stripping the `mgh` package in the `coverage xml` generation.

**Comment by paltman** [comment]
I wonder if `tox` executing the coverage and then travis's `after_success` executing the `coverage xml` via `codecov` is the problem.

I'm testing that theory by pulling out the execution from tox and directly into my `travis.yml`.  I'll let you know shortly if that solves it.  It will at least remove that bit of the puzzle.

**Comment by paltman** [comment]
That did it!

Thanks @stevepeak for the tip cluing me into the paths.  I had been looking at the source file uploaded for awhile but didn't notice it until you pointed it out.
