### ISSUE TITLE
Code coverage only for pull request

### ISSUE THREAD

**Issue by yyunikov** [codecov/support#419]
We are having the following issue with CodeCov. Consider case when making pull request from some PR branch to main branch. The pull request contains changes in 4 files and does not actually affect the main branch coverage. However, since the pull request was created, there were few changes that affected code coverage in main branch.

So, for this case, code coverage shows that 17 files were changed (this is a difference between main branch and PR branch), but really, PR only changed 4 files. As a result, PR comment shows that code coverage was decreased.

![Code coverage screenshot](https://files.slack.com/files-pri/T04KHQ16W-F62A7KT0U/code_coveragechanges.png?pub_secret=92d705cea2)

Our goal is to see the code coverage changes which were **only affected by the pull request**. 
Currently, the report and changes are shown on another files (I suppose on the files made outside of pull request). Is it possible to see only code coverage on diff files with CodeCov?

**UPDATE:**
I've created an example Github project to demonstrate similar issue. Please check [this pull request](https://github.com/yyunikov/codecov-example-java/pull/2) which does not really affect master.
<img width="1252" alt="screen shot 2017-06-30 at 7 51 13 pm" src="https://user-images.githubusercontent.com/5285857/27745827-87690ff0-5dcd-11e7-9412-bf4cf7d4b13d.png">
.

**Comment by stevepeak** [comment]
Hey :)

> `only affected by the pull request`

I see you are reviewing a pull request in Codecov - Great. 
We show this this data off in the Diff and Changes tabs. Also the Files tab can help.

Think the coverage is wrong? Please review the [raw uploaded reports to confirm](https://docs.codecov.io/docs/unexpected-coverage-changes#section-review-reports-yourself) the findings (I manually do this for customers everyday and I always find it accurate). Let me know a specific filename and line number you think is wrong.

> the report and changes are shown on another files (I suppose on the files made outside of pull request). Is it possible to see only code coverage on diff files with CodeCov?

Yes. E.g. you remove a test then coverage may change but you did not "touch" those lines.

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/4621 - this is the same problem we saw here as well. 

![screenshot](https://user-images.githubusercontent.com/622699/27890033-3cd41760-61a5-11e7-8228-d995555966e0.png)

The PR just changes one file and is fully covered but the overall coverage indicates some files actually lost coverage which shouldn't be the case since the code flow path or PR doesn't even affect these values.

**Comment by yyunikov** [comment]
@stevepeak Could you explain how this then happened? New file was created in PR and was fully covered with test. It was successfully submitted to CodeCov, however shows 0% coverage for the file. See the screenshots below
![circle_ci](https://user-images.githubusercontent.com/5285857/27915981-7b1ff068-6270-11e7-8f2e-799a560aa25d.png)
![new-file](https://user-images.githubusercontent.com/5285857/27915982-7b3c0d66-6270-11e7-8019-1a69acac669b.png)
![test-file](https://user-images.githubusercontent.com/5285857/27915984-7d0b76cc-6270-11e7-87e0-aa67d3fa7c20.png)

**Comment by yyunikov** [comment]
Guys, any ideas of what's happening above?

**Comment by yyunikov** [comment]
I've created a [test PR on a public repo](https://github.com/yyunikov/codecov-example-java/pull/4) to reproduce an issue. Please check.

**Comment by stevepeak** [comment]
Fixed here: https://github.com/codecov/support/issues/467

**Comment by JimBobSquarePants** [comment]
Fixed?

**Comment by stevepeak** [comment]
@JimBobSquarePants I'll follow up in #467. Thanks
