### ISSUE TITLE
Suggestion: do not show redundant packages in Sunburst and Iceberg charts

### ISSUE THREAD

**Issue by yuriykulikov** [codecov/support#420]
Hello guys,
thanks a lot for an awesome platform! Loving it!

I have a suggestion though. In many Java/Kotlin projects there is normally a deep hierarchy of empty folders. For example, in my project: src/java/main/com/better/alarm. The only folder with source files and other packages is src/java/main/com/better/alarm, whereas all other folders above contain only the next folder.

This causes the charts to initially look like this:
![image](https://user-images.githubusercontent.com/827794/27994092-a5e4f526-64b6-11e7-8d02-2e3cae96c498.png)

After a click on the empty folders the chart looks better (more informative, anyway):
![image](https://user-images.githubusercontent.com/827794/27994105-e90156f6-64b6-11e7-98b0-6a7adb269459.png)

My suggestion is to remove empty folders from the sunburst and to treat the first folder with content as the base folder.

The same goes for the Iceberg chart.

Thank you for consideration.

**Comment by stevepeak** [comment]
Thank you for the awesome feedback :) I'll look over the svg flare to see if we can accommodate this quickly.

**Comment by manh84** [comment]
Hep me

**Comment by stevepeak** [comment]
Deployed. Thanks!
