### ISSUE TITLE
Dashboard empty since removal of a couple of reports

### ISSUE THREAD

**Issue by marco-c** [codecov/support#424]
After the removal of a couple of commits (using the API, https://docs.codecov.io/reference#section-delete-a-commit), the dashboard at https://codecov.io/gh/marco-c/gecko-dev got empty.

The page says "No commits found on master yet.", even though there is a list of commits at https://codecov.io/gh/marco-c/gecko-dev/commits.

**Comment by stevepeak** [comment]
There is known issue when deleting the head commit on a branch: project get's stuck in this state.
Fixed 👍

**Comment by marco-c** [comment]
Thanks!

**Comment by marco-c** [comment]
Hey @stevepeak, I've removed the head commit again as there was a problem, could you fix it again?

**Comment by marco-c** [comment]
Automatically fixed itself with the new build ;)
