### ISSUE TITLE
Paths can't be ignored in .codecov.yml

### ISSUE THREAD

**Issue by zeux** [codecov/support#426]
I had to rename .codecov.yml to codecov.yml to be able to ignore paths for code coverage; see this commit:

https://github.com/zeux/meshoptimizer/commit/763351990366031fd3044d159bd7ac1526376cf4

This behavior is extremely surprising and - as far as I can tell - undocumented. It would be nice to fix it.

**Comment by stevepeak** [comment]
This projects codecov.yml location is cached at `./codecov.yml` at the moment, which appears accurate. Is it working since the location change?

**Comment by zeux** [comment]
Yeah it is - but it was *not* working when the file was named `.codecov.yml` (note the dot), which is why I had to rename it in the commit above.

**Comment by psavery** [comment]
I can confirm this is an issue. I ran into this problem as well. 

Although the codecov output said that the .codecov.yml was found, the ignore paths were not ignored until I changed the name to codecov.yml (removing the dot).

As a note in case it matters: I'm using C++, cmake, ctest, lcov, and gcc on an Ubuntu 14.04 travis-CI server.

**Comment by Lectem** [comment]
I confirm removing the dot worked for me too.
With ".codecov.yml" : https://codecov.io/gh/Lectem/Worldstone/commit/28db3915fa5cfe009f6b744d0fef487275fe0cbb
With "codecov.yml" : https://codecov.io/gh/Lectem/Worldstone/commit/1949c84fa54ce30d9ac090cf0e5c748fc4a87bac     <<< source/system/tests/systemtests.cpp is ignored, expected behaviour

**Comment by Apidcloud** [comment]
I had the same issue while trying to set **patch threshold**. Renaming the file to **codecov.yml** made it work!

**Comment by ccbrown** [comment]
Also encountered this issue with `ignore` not working for .codecov.yml, but working for codecov.yml. Weird.

**Comment by horenmar** [comment]
Also got hit by this

**Comment by stevepeak** [comment]
Applied a patch today concerning this issue. Thank you all for your patience.

**Comment by LebedevRI** [comment]
Hmm. I'm also having an issue with ignoring some paths, but i'm not sure if my issue is different:
The ignore patterns are specified:
https://github.com/darktable-org/rawspeed/blob/67a9e11d275a002d4599b7c6e1db9e2632bebd90/.ci/codecov.yml#L16-L20
```
...
coverage:
  ...
  ignore:
    - "test"
    - "test/*"
    - "test/**/*"
    - "**/test/**/*"
...
```
Yet the report still shows `test/librawspeed`
https://codecov.io/gh/darktable-org/rawspeed/tree/2cce64527b4d32ea6a3c1174a53e496415465965
Am i doing something wrong?

**Comment by LebedevRI** [comment]
The ignore feature appears to be really wonky.
This appears to work:
```yaml
coverage:
  ignore:
    - test/.*
```
Any of these did not work
```yaml
coverage:
  ignore:
    - **/test/**/*
    - "**/test/**/*"
    - "test"
    - "test/*"
    - "test/**/*"
    - "test/.*"
    - "test/**"
    - "test/**/*"
```
So it looks like it really does not like `**`, and `"`, *especially if it is the first in the ignore pattern. :(

**Comment by stevepeak** [comment]
We have patched a number of issues concerning the yaml locations. If anyone has outstanding issues please contact our support. Thank you!
