### ISSUE TITLE
One-line CSS change is reported as coverage decrease?

### ISSUE THREAD

**Issue by nylen** [codecov/support#427]
Hi,

It looks like the codecov report for https://github.com/WordPress/gutenberg/pull/2074 was a bit off.  This was a one-line CSS change which should not have had any impact on code coverage.  However, the report shows that it decreased 0.57% (or 0.58% if you look at the `codecov/project` status check, which failed).

It looks like something was off with the coverage for the merge base of this commit.  Why would this happen?  Should we expect this issue to recur?

**Comment by nylen** [comment]
Another PR that had an incorrect report of coverage change: https://github.com/WordPress/gutenberg/pull/1817

**Comment by stevepeak** [comment]
Codecov reports exactly what is uploaded. In this case the raw uploads express the drop of coverage for any number of reasons. The best I can help with is in this documentation: https://docs.codecov.io/docs/unexpected-coverage-changes
