### ISSUE TITLE
Inability to access files from a private repository is classified on-site as paths being relative

### ISSUE THREAD

**Issue by 13steinj** [codecov/support#428]
This took me a good few days to figure out-- so I'm posting here in an attempt to alleviate any headache of someone else with the same issue.

Upon first login and setup, codecov was only granted the public repository scope. From then I proceeded to log in on a few machines, and later set up continuous integration and coverage reports for one of my private repositories.

While the reports were uploaded fine, every time I attempted to view the code coverage on a file I received an error stating that the Github api returned 404 not found and the resolution offered was that the paths of my files were relative, and I'd need to setup path fixes in my .codedov.yml in order to have CodeCov properly view these files-- this was not the case. CodeCov merely didn't have the private repo scope. Only after logging out of CodeCov on one machine, and having the offer to log in with the private scope then, was I able to resolve the issue. CodeCov did not offer to add the private repo scope on the repositories listing until after that-- and did not offer this on the error page either.

**Comment by stevepeak** [comment]
Thank you for the feedback. We try to show a message stating that private repo access is not enabled on your profile, was this message not provided in your project?

**Comment by 13steinj** [comment]
Unless I completely missed it multiple times, this wasn't shown, definitely not on the actual file pages which claimed the paths to be relative. I'm unaware of how in-depth the github api responses are in terms of explaining why a page is forbidden; but perhaps if more detailed the full  explanation shown.

If not done already, when checking for the contents of the repo using the api contents_url the entire repo should be checked, because if that specifically 404s it is an access issue instead of a "file in a different place issue" and the user should be notified.

**Comment by 13steinj** [comment]
I'm closing this because whether it be due to my suggestion or not, on the file view page when I logged on from a new phone and codecov didn't originally authenticate with the private scope, the system notified me on the file page that that could be the issue, and let me add it from there.
