### ISSUE TITLE
Python: coverage.py enhancements

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#43]
> Issues pertaining to customers with (a) multiple builds for (b) python

#### Waiting for [ned/coveragepy#53](https://bitbucket.org/ned/coveragepy/pull-request/53/store-missed-branches-data-in-xml-report/diff)

This issue will fix customers seeing incorrect partials. [See line 11 here](https://codecov.io/github/coala-analyzer/coala/coalib/parsing/ConfParser.py?ref=b1e86365bd5d53c5b810e3ef86f284dd9b9cf7d2) which clearly is covered, but but by different builds. The unified report cannot distinguish this issue until `coverage.py` is fixed.

[Read more about the logic here](https://github.com/codecov/support/wiki/Python-Branch-Condition-Logic)

-----

## Work Around

```sh
# already in Codecov Bash Uploader
pip uninstall -y coverage
pip install git+git://github.com/codecov/coveragepy.git
```

> Disabled feature via `-X issue/43`

**Comment by sils1297** [comment]
Still help wanted?

**Comment by sils1297** [comment]
Anything else you need?

**Comment by stevepeak** [comment]
Thanks @sils1297 for your help. I need to patch the server side and bash uploader to implement this work around. I'll keep in touch on the progress. Thanks!
