### ISSUE TITLE
"There can be only one."

### ISSUE THREAD

**Issue by gdamore** [codecov/support#432]
A very minor nit, but there is a misquote in the little "loading" messages that come up...

The quote should be "There can be only one." 

Instead it says "There can be only one Highlander." 

That's wrong... the quote is *from* Highlander, but "one" in this case refers to one out of many contending immortals.  (Several contenders are indeed from the Scottish highlanders, including the main protagonist, but numerous others are from other places.)

**Comment by stevepeak** [comment]
HAHA! 👍 Best feedback yet.
