### ISSUE TITLE
Bash script unclear about why it can't find `codecov.yml` when source-control not present

### ISSUE THREAD

**Issue by adamdicarlo** [codecov/support#433]
Feature request for codecov bash script:

1. Allow _at least_ project-root-only `codecov.yml` files when source control is unavailable
2. Show _why_ `codecov.yml` was not found when it's not (eg. "We couldn't find .git or .hg directories, so we only looked in the project-root directory")

Figuring out _why_ codecov.yml wasn't being found sucked up a few hours of my and my coworker's time.

Our builds are in CodeShip Pro; since it's a Docker build, the `.git` directory is unavailable. Codecov's bash script says `Yaml not found!` despite it being present in the current directory (the problem was actually that `.git` is unavailable).

Here's the code in the bash script that is causing this problem for us:

```
yaml=$(cd "$git_root" && \
       git ls-files "*codecov.yml" "*codecov.yaml" 2>/dev/null \
       || hg locate "*codecov.yml" "*codecov.yaml" 2>/dev/null \
       || echo '')
yaml=$(echo "$yaml" | head -1)
```

**Comment by jayvdb** [comment]
This should be submitted to https://github.com/codecov/codecov-bash

**Comment by adamdicarlo** [comment]
Thanks, I must not have noticed that repo when I submitted this.

**Comment by adamdicarlo** [comment]
https://github.com/codecov/codecov-bash/issues/100
