### ISSUE TITLE
Simple Text UI

### ISSUE THREAD

**Issue by elharo** [codecov/support#434]
I've used code coverage tools for years. Codecov nicely integrates with Github, which is a huge plus. However the UI appears to me to be distinctly less useful than older tools such as Fisheye and Cobertura. In particular. it is difficult to impossible to drill down into the code and see what is covered and what is not. The graphical maps look impressive, but are not as usable as plain HTML tables.

All we need is a straightforward HTML tables that let us drill down into our code and show coverage metrics for each directory, class, line etc. No heat maps. No code folding. These UI widgets make the relevant numbers harder to find and understand.

**Comment by stevepeak** [comment]
@elharo You can view this information from a single commit file list: https://codecov.io/gh/GoogleCloudPlatform/google-cloud-eclipse/tree/041fe0b474b9f4698dcee980543bd0b12311351d

See here: https://cl.ly/1n3b2h2W3o1L
Is that what you are looking for? Thank you!

**Comment by elharo** [comment]
No, I don't think that's it. This isn't about changing from tree to list and back. It's about changing from heat map to list/tree or better yet making tree/list the default view instead of heat map.

E.g. when I go to https://codecov.io/gh/GoogleCloudPlatform/google-cloud-eclipse I want to see a tree or a list view for that project. I'm sure there's some way to navigate to it through the various tabs and buttons, but I can't find it. :-(

All the graphs and pretty pictures don't help me understand where I need to add coverage. The tree/list view does.
