### ISSUE TITLE
Appveyor upload issue for forked repos

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#44]
> Appveyor, forked public repos, no upload token

Customers are experiencing an issue with Appveyor forked repo builds when no upload token is presented. Seeking customer support for clarification of environment variable values.

Support requested: http://help.appveyor.com/discussions/questions/1413-forked-repos-variables

----

##### Environment variables we use for upload
```sh
branch = $APPVEYOR_REPO_BRANCH
build = $APPVEYOR_JOB_ID
job = $APPVEYOR_BUILD_VERSION
slug = $APPVEYOR_REPO_NAME
commit = $APPVEYOR_REPO_COMMIT
```

##### Build request
```sh
curl https://ci.appveyor.com/api/projects/$APPVEYOR_REPO_NAME/build/$APPVEYOR_BUILD_VERSION
```

**Comment by vasily-v-ryabov** [comment]
It's also not working for main repo in organization.
AppVeyor project: username/reponame
GitHub repo: organization/reponame

**Comment by FeodorFitsner** [comment]
`$APPVEYOR_REPO_NAME` is a full name of GitHub in the format `<owner>/<repo>`.

AppVeyor REST API URLs related to builds expect `$APPVEYOR_ACCOUNT_NAME` and `$APPVEYOR_PROJECT_SLUG`, so correct build request is:

    curl https://ci.appveyor.com/api/projects/$APPVEYOR_ACCOUNT_NAME/$APPVEYOR_PROJECT_SLUG/build/$APPVEYOR_BUILD_VERSION

**Comment by stevepeak** [comment]
@FeodorFitsner thank you for the quick response! I'll adjust our tools to account for this.

One clarification: which repo does the `commitId` reside on?
- A) `$APPVEYOR_ACCOUNT_NAME/$APPVEYOR_PROJECT_SLUG`
  - `https://github.com/$APPVEYOR_ACCOUNT_NAME/$APPVEYOR_PROJECT_SLUG`
- or B) `$APPVEYOR_REPO_NAME`
  - `https://github.com/$APPVEYOR_REPO_NAME`

**Comment by FeodorFitsner** [comment]
It's `$APPVEYOR_REPO_NAME`: `https://github.com/$APPVEYOR_REPO_NAME`

**Comment by stevepeak** [comment]
@vasily-v-ryabov can you send up another commit to see if my changed worked :+1: thanks!

**Comment by vasily-v-ryabov** [comment]
Started build here: https://ci.appveyor.com/project/vasily-v-ryabov/pywinauto/build/0.5.0.47 (organization repo)
and here: https://ci.appveyor.com/project/vasily-v-ryabov/pywinauto-8b7t7/build/1.0.35 (fork with hashed slug)

**Comment by stevepeak** [comment]
@vasily-v-ryabov looks like those builds failed and no coverage was submitted. Thanks

**Comment by vasily-v-ryabov** [comment]
I use codecov 1.1.9 installed by pip. So how can I use codecov with your fix?

**Comment by vasily-v-ryabov** [comment]
It works with codecov 1.1.10 for both cases! Thank you guys! :+1:

**Comment by stevepeak** [comment]
There is a new release of Codecov available that has the fixes. I should auto-update during the build. Thanks!
