### ISSUE TITLE
Patch status documentation incomplete

### ISSUE THREAD

**Issue by elharo** [codecov/support#443]
I'm having trouble following the patch status documentation below. In particular it seems to me the claims about coverage on the patch depend on the existing test coverage or lack thereof. In particular this page never says whether or not there are existing tests for the divide method in advance of the patch.

If there are, then this method might be up to 100% covered after the patch, depending on what those tests says. Even a single test should at least hit the `if y <= 0` line so we ought to be starting from 50% coverage minimum. If, OTOH, there are no tests at all then then the relevant number is that this method is 0% covered, not that the file is 72% covered. 
 
To illustrate the usage of the patch status lets make a couple commits

  def divide(x, y):
+     if y <= 0:
+         raise ValueError("y must be greater than 0")
      return x * y
The resulting codecov/patch status of this commit would be 0% covered because Steve has not added any tests to this method. Even though the project coverage is 72% (the entire code base) this patch status will only measure lines added.

Steve now makes another commit on this pull request adding tests.

+ def test_divide_by_1(self):
+     assert divide(10, 1) == 10
Running the tests will result in a patch coverage of 50% covered because we have not yet tested the behavior of dividing by zero. Let's add another test.

**Comment by stevepeak** [comment]
The patch status concerns **only the lines adjusted** the current "project" coverage is used as a target of the patch to encourage incremental coverage increasing.

If you do not adjust any lines of code coverage-tracked code than your patch status would be `n/a`. If you adjust one line of code that is coverage-tracked than your patch status would be `0%` or `100%` depending on the line being missed or hit, respectively.
