### ISSUE TITLE
[Improvement] Do not fail status checks if no initial report is available

### ISSUE THREAD

**Issue by robbieaverill** [codecov/support#447]
If codecov.io integration is being added to a GitHub repository, the first pull request (often the one containing this integration) will fail status checks since no base coverage report is available.

Personally, I think it would be nice for this situation to return a "pass" rather than a "fail" as it visually indicates that something is wrong with the pull request, when in fact it's a new check that doesn't have enough data to correctly report on itself.

A workaround would be to add codecov.yml specifying to disable the status checks in the first pull request, then re-enable it after that is merged. This seems a bit silly though.

Feel free to close this issue if you disagree with me! Thanks :)

**Comment by stevepeak** [comment]
@robbieaverill Thank you for your feedback. Indeed it would be nice to pass or ignore the status for new projects. We cannot set a pass for projects that are not new since it could be a way to skip checking the coverage.

I'll think of something to help this out. Thanks!
