### ISSUE TITLE
flat-square badge for codecov

### ISSUE THREAD

**Issue by juliohm** [codecov/support#451]
How to set the style of the badge to be flat-square like in the https://shields.io/ URLs?

Can you please add this functionality, or in other words, implement the shields.io interface?

**Comment by stevepeak** [comment]
We do support Shields. I'll make a note to add this to our UI.

http://shields.io/ then find Codecov

e.g., `[![Codecov](https://img.shields.io/codecov/c/github/codecov/example-python.svg)]()`

**Comment by juliohm** [comment]
@stevepeak your example doesn't answer my question. How to set the style to be flat-square? Open http://shields.io and search flat-square
