### ISSUE TITLE
How to specify root directory

### ISSUE THREAD

**Issue by ENikS** [codecov/support#452]
My repository structured like this:
```
src/
   code files ...
tests/
  test.project.x
  test.project.y
```
After processing results I am getting a view like [this](https://codecov.io/gh/unitycontainer/container) 
```
src/
  file.cs
  file.cs
 ...
```
I'd like to 'skip' src directory and only display tested files. If I use ``fixes`` files are displayed at the root but if I try to open any of the files it results in 404 error.

Any suggestions?

**Comment by blueyed** [comment]
I think "fixes" is meant for this, but might be broken?!

**Comment by stevepeak** [comment]
> `fixes` in the yaml are meant to help resolve paths to the repository if codecov fails to map them back automatically. 👍 @blueyed 

You can use `ignore` to ignore the test files.

```yaml
# codecov.yml
ignore:
  - tests/
```

**Comment by ENikS** [comment]
I am ignoring test files. It is not what I am trying to do. Did you even read my question before closing this issue?

**Comment by blueyed** [comment]
@stevepeak 
There seem to be issues with the mapping (see also the intercom issue I've posted where mapping (without `fixes`) was acting up.
