### ISSUE TITLE
Badge Padding

### ISSUE THREAD

**Issue by bagrat** [codecov/support#455]
The padding of the coverage percentage part in the CodeCov padge is very low (are maybe even absent?). Here's an example:

<img width="289" alt="screen shot 2017-11-05 at 7 36 03 am" src="https://user-images.githubusercontent.com/3033265/32411727-28be10c0-c1fc-11e7-9ed4-5540dffbd5b5.png">

It would be great if CodeCov badge percentage part padding would set like the one for the `health` badge in the example.

**Comment by bagrat** [comment]
Putting the real one, for demo and to track the issue status in realtime 🙂 

[![Coverage Status](https://codecov.io/gh/bagrat/untt/branch/master/graph/badge.svg)](https://codecov.io/gh/bagrat/untt)

**Comment by stevepeak** [comment]
Fixed in next release. Thank you!
