### ISSUE TITLE
F# example

### ISSUE THREAD

**Issue by MNie** [codecov/support#468]
Hi I created an F# example based on the old format of fsproj since the new one seems to [doesn't work right now](https://github.com/OpenCover/opencover/issues/787).

[Example repository](https://github.com/MNie/codecov-fsharp) Is it okay?

**Comment by stevepeak** [comment]
Fantastic job @MNie Thank you kindly.

**Comment by MNie** [comment]
@stevepeak no problem :) Do you want to transfer this repository to [codecov](https://github.com/codecov)?

**Comment by stevepeak** [comment]
Awesome :) You'll need to transfer it to @stevepeak first then I can push it in. Thanks!

**Comment by MNie** [comment]
@stevepeak repository transferred :)

**Comment by stevepeak** [comment]
https://github.com/codecov/example-fsharp

👍
