### ISSUE TITLE
Expand messages

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#47]
> cc @lefticus

Extend the messages feature in Codecov

- [ ] show messages inline w/in Codecov file view
- [ ] accept new messages layout (as seen below)
- [ ] (future) show messages in browser extension
- [ ] (future) show aggregate messages in pr comments
- [ ] (future) seek messages output file for specific linting/static analysis tools for each language

```json
"message": [
  {
    "severity": "info,warning,error",
    "message": "string",
    "title": "string",
    "display": "inline or popover",
    "start_line": "integar",
    "start_column": "?integar",
    "end_line": "?integar",
    "end_column": "?integar"
  }
]
```

**Comment by stevepeak** [comment]
@lefticus checkout [this comment](https://github.com/codecov/support/issues/54#issuecomment-130102710) for some ideas on what I'm going to work on. This is now in a planning phase. Cheers!

**Comment by kshyatt** [comment]
This looks awesome!

One option that might be useful/cool for me (feel free to ignore if it's dumb!) is to have an option to "stack" the same line highlighted in different colours for different conditions, so one doesn't have to tab around a bunch. I'm thinking of something a bit like the GitHub Unified view here. I can draw a picture if that would help?

**Comment by stevepeak** [comment]
Hey @kshyatt I love pictures :) :+1:

We are considering using a "darker" green to represent lines that are hit more then others. This data is provided by most languages. 

Thank you!

**Comment by lefticus** [comment]
@stevepeak excellent, thanks for the update.

**Comment by stevepeak** [comment]
We have included "messages" in our next major release. There will be official documentation available shortly!

The following features have been included with messages:
1. message title 
1. body with markdown support
1. icon choice via [FontAwesome](fortawesome.github.io/Font-Awesome/cheatsheet/)
1. column support (where the message spans to and from)

Example message:
```json
{
  "title": "Syntax Error",
  "icon": "warning",
  "body": ":custom markdown:",
  "columns": [5, 10]
}
```
