### ISSUE TITLE
Allow specifying a path prefix when uploading coverage reports

### ISSUE THREAD

**Issue by janpaul123** [codecov/support#472]
Can kind of work around this with the path fixing feature, but that requires relative paths to be unique. In our case, we have a directory structure like this:
- repo root
  - client
    - app
  - core
    - app

We upload coverage reports from both the "client" and "core" directories, but can't disambiguate between them because they both have "app" directories within them. We ended up renaming one of the "app" directories, but that's not ideal. Ideally we would do something like `codecov --prefix-path=client …`

**Comment by stevepeak** [comment]
@janpaul123 this is a good idea to implement and is not difficult. I'll submit a PR shortly.

**Comment by janpaul123** [comment]
Thank you!
