### ISSUE TITLE
badges are accidentally see-through

### ISSUE THREAD

**Issue by nschloe** [codecov/support#473]
As opposed to all other badges out there, the default codecov badges are see-through. This doesn't matter much if your background is white (like default GitHub), but you do notice a difference if it's not:

![bad](https://user-images.githubusercontent.com/181628/35183352-d31a2c24-fde4-11e7-82fa-d0e952cb548c.png)

**Comment by stevepeak** [comment]
Interesting. I'll take a look at this. Thank you

**Comment by stevepeak** [comment]
Are you using the badge from Codecov site or from Sheilds.io? Unless I'm mistaken, our badge should not produce this transparency.

**Comment by nschloe** [comment]
The badge from shields.io does not have the problem; only the native codecov one does. For example this one: https://codecov.io/github/nschloe/meshio/branch/master/graphs/badge.svg.

**Comment by VladShcherbin** [comment]
@stevepeak can you also fix the paddings https://github.com/codecov/support/issues/455?

This's not right when you are punished with 100% coverage or have to use shields.io just to get a normal badge.

**Comment by stevepeak** [comment]
@VladShcherbin Thanks for the poke on #455 -- I'll fix that up along with the transparency.

**Comment by stevepeak** [comment]
@nschloe can you help me out here... I must be missing the point. I just cannot find the transparency you are referring to :(

Checkout this screenshot: https://cl.ly/2n1y3q2f3N2F

**Comment by nschloe** [comment]
Check out the badge from betterbib for example. https://github.com/nschloe/betterbib

![cc](https://user-images.githubusercontent.com/181628/35565834-692194b4-05bf-11e8-8ad1-f48904b87b71.png)

**Comment by stevepeak** [comment]
@nschloe It's clear by your screenshot that something strange is going on, but I'm just not able to replicate it, no matter what I do. Are you able to provide HTML example of this? 

I'm sorry, but I've tried many ways to get it look like your screenshot, but it's not giving.

**Comment by nschloe** [comment]
Thanks again for the reply. I've also played around with HTML properties and indeed with those, I cannot reproduce the problem either. This surprised me. The color change only occurs when using the Stylish extension and [this theme](https://userstyles.org/styles/37035/github-dark).

I guess this classifies as too specific then. Since I can also use the shields badges, that's what I'll do. Closing.
