### ISSUE TITLE
"Oh wait! There's more" requires an apostrophe

### ISSUE THREAD

**Issue by rjw57** [codecov/support#474]
"There's" is a contraction of "There is" and requires an apostrophe between the "e" and "s". It's debatable whether there should be a comma between "Oh" and "wait" but that's a separate issue.

![screenshot from 2018-01-23 12-40-56](https://user-images.githubusercontent.com/146860/35276265-bcb2c114-003a-11e8-9788-61f2b6e9114a.png)

**Comment by stevepeak** [comment]
Thank you 👍

**Comment by rjw57** [comment]
No probs :).
