### ISSUE TITLE
Failing: codecov/patch — 0% of diff hit (target 65.13%)

### ISSUE THREAD

**Issue by evandrocoan** [codecov/support#477]
1. https://github.com/evandrocoan/PythonDebugTools/commits/master
1. https://codecov.io/gh/evandrocoan/PythonDebugTools/commit/6cd86e5d4443bf653e7c8141fee86aef3ead6971

![image](https://user-images.githubusercontent.com/5332158/35601765-f07f50f2-061b-11e8-81e9-46159867ca4d.png)

I do not understand why it is failing. Is it some kind of bug on my code or `codecov`?

**Comment by soleares** [comment]
The same thing started happening recently for our project as well. Were you able to figure it out?

**Comment by evandrocoan** [comment]
I think it is falling because the coverage did not increased, i.e., more code was added but the coverage did not increased. Hence, writing a new dummy text which increases the coverage should make it pass.

I am not sure I like this. I am more tempted to remove these covecov stuff than creating useless tests just to make him happy.

**Comment by soleares** [comment]
Thanks. I ended up setting patch to false. I'm hoping that takes care of it.

**Comment by stevepeak** [comment]
The `codecov/patch` status checks line that were adjusted in the pull request to make sure they are tested. In your screenshot above 0% represents that all the adjusted lines were not covered by tests.

More details here: https://docs.codecov.io/docs/commit-status

> Closing issue because it's not an issue, but a question that we are happy to continue to answer. Thanks!
