### ISSUE TITLE
Unable to use Altcover coverage reports

### ISSUE THREAD

**Issue by Nihlus** [codecov/support#479]
When attempting to upload a coverage report generated via [Altcover](https://github.com/SteveGilham/altcover), codecov accepts the file and appears to consume it, but fails with an error message on the service, claiming that no files were found in the report.

No coverage information is extracted or presented. I've included a sample file, build log from Travis, and the error log on the service.
[codecov.log](https://github.com/codecov/support/files/1740627/codecov.log)
[coverage.xml.txt](https://github.com/codecov/support/files/1740628/coverage.xml.txt)
[travis-log (1).txt](https://github.com/codecov/support/files/1740629/travis-log.1.txt)

**Comment by SteveGilham** [comment]
Having looked at your documentation, I see the underlying issue.

For historical reasons (being that it was originally written back when the freeware NCover version 1.5.x was the _de facto_ standard for .net coverage), altcover emits coverage data in classic NCover format, which is almost entirely unlike OpenCover format.  This support item is tantamount to a request support for this separate format.

OpenCover to NCover adapters I have to hand, the reverse will take a little work.

**Comment by Nihlus** [comment]
Codecov has now added support for the NCover format.
