### ISSUE TITLE
Alternatives to Codecov? - Waiting for status to be reported

### ISSUE THREAD

**Issue by Rush** [codecov/support#481]
I contacted codecov support but unable to get resolution. Codecov is nowadays more often broken then not. The uploads say they are successfully uploading, using codecov 3.0.0 from npm. 

![](https://rush.sh/15MmIlH10PhE+90dytw8PcYIa+k/screenshot.png)

The in-codecov logs is showing a lot of errors probably internal to how codecov is working. 

Do y'all know any other services with strong Github integration? Unfortunately can't rely on Codecov if 90% of pull requests need to be force merged by the admin!

**Comment by stevepeak** [comment]
Hi @Rush, I'm sorry to hear you are having issues. I will look for your ticket in our support channels. Since this is a single project issue I will close the thread.
