### ISSUE TITLE
Default branch is wrong

### ISSUE THREAD

**Issue by blackbing** [codecov/support#482]
Sorry I can not link to your slack(https://slack.codecov.io/) so I create an issue here.

https://codecov.io/bb/cnyesrd/fe-forex default branch is not point to `codecov.yml` in this repository. 
https://codecov.io/bb/cnyesrd/fe-crypto has the same situation. It bother our team a long time. Can you help us to figure out the problem?

![2018-02-26 2 59 50](https://user-images.githubusercontent.com/47012/36657003-c10b551a-1b05-11e8-9270-257a8af3ca9a.png)

here is our codecov.yml

``` yml
codecov:
  branch: develop
```

**Comment by stevepeak** [comment]
I've updated them both. Thanks! 
> There is a bug in the change branchs that we are looking into.
