### ISSUE TITLE
repo not recognized ?

### ISSUE THREAD

**Issue by DotzuX** [codecov/support#484]
My repo used Swift & Objc, This is my [travis.yml](https://github.com/DotzuX/DotzuX/blob/master/.travis.yml)

[travis-ci](https://travis-ci.org/DotzuX/DotzuX) just works fine. But [codecov](https://codecov.io/gh/DotzuX/DotzuX/) not work.

Anything wrong with my `travis.yml` ? 
Thanks!

**Comment by stevepeak** [comment]
Please remove the `-J Example_Swif` from the upload command 👍

**Comment by DotzuX** [comment]
Thanks!

**Comment by DotzuX** [comment]
I just removed ` -J Example_Swift`, but does not work yet...
please help me, thanks @stevepeak
