### ISSUE TITLE
 No coverage report found.

### ISSUE THREAD

**Issue by DotzuX** [codecov/support#485]
[https://www.travis-ci.org/DotzuX/DotzuX](https://www.travis-ci.org/DotzuX/DotzuX)

Anything wrong? Thanks

**Comment by udos** [comment]
looks like you are not runnig code coverage before collecting the report on line [L2415](https://www.travis-ci.org/DotzuX/DotzuX/jobs/353196343#L2415)

so codecov does not find the coverage report on line [L2434](https://www.travis-ci.org/DotzuX/DotzuX/jobs/353196343#L2434)

**Comment by DotzuX** [comment]
works now, thanks
