### ISSUE TITLE
Incremental (or decremental) code coverage for status API

### ISSUE THREAD

**Issue by RyanCopley** [codecov/support#5]
It would be nice to set a threshold for the required coverage change limit. If it would be set to -1%, if a pull request lowered coverage by 1%, the status would fail. If it was set to 1%, and the PR kept the same amount of coverage, the status would fail.

**Comment by stevepeak** [comment]
Hey @BenLiyanage @justinabrahms here is a thread about the feature you requested. Will be getting on this very soon. You can add comments and ideas here. Thanks!

**Comment by justinabrahms** [comment]
I would settle for a simple comment if that's particularly easier for you. This feature makes me very excited though.

**Comment by RyanCopley** [comment]
I'd prefer using the status API as it's more enforceable in our organization (Red X means bad)

**Comment by RyanCopley** [comment]
@justinabrahms it already does what you want, actually: https://i.imgur.com/iLQPsZP.png

**Comment by justinabrahms** [comment]
@RyanCopley Maybe you and I want different things.

What I want is to know what percentage of this patch is covered. I don't care about how this affects overall coverage. I'd like to enter a code base that has no test coverage and be able to say "All future patches must have 80% test coverage". We will then trend towards 80% coverage without having a bad CI status in the meantime.

Does that make sense? Is this also what you want? The screenshot you posted doesn't reflect this patch-centric view (on a percentage basis, that is)

**Comment by stevepeak** [comment]
The plan, as of now, is to add two distinct methods to this feature.

#### Commit Status
> User sets `X` in Codecov UI

1. **when not in a PR:** pass when `previous coverage + X  > commit coverage`
2. **when in a PR commit:** pass when `pr coverage + X > merge into coverage`
3. **non-pr

#### Comments
> Add a new section that illustrates the patch coverage

**Comment by justinabrahms** [comment]
I'm not sure I understand your comment, @stevepeak, but I think "all commits" is the one that I want.

**Comment by BenLiyanage** [comment]
What Justin said sounds very similar to what I'd be interested in.  I'd
like to know where/what can be covered better to improve my code coverage.

-Ben

**Comment by justinabrahms** [comment]
The logic for incremental code coverage looks something akin to (python pseudocode):

```python
changed_lines, removed = parse_diff()
changes_in_patch = set((line.filename, line.number) for line in changed_lines)
covered_lines = parse_coverage()
covered = set((line.filename, line.number) for line in covered_lines)

incremental_coverage = len(changes_in_patch.intersection(covered)) / len(changes_in_patch)
```

I'm assuming you have logic for `parse_coverage`. If you need help with `parse_diff`, I've written that logic before in https://github.com/justinabrahms/imhotep and I'm happy to help.

**Comment by stevepeak** [comment]
I'll do my best to enhance these tools to accommodate to each request presented in this thread. 

@justinabrahms thanks for the notes on incremental logic. The "all commits" would be the one your interested in. Perhaps doing a status for (1) overall min coverage, and (2) incremental coverage would do the trick.

@BenLiyanage perhaps the best way to accomplish your ideas would be changing the Uncovered Suggestions feature on be exclusive to the patched files.

**Comment by BenLiyanage** [comment]
Honestly, while it would be nice to have that change, I think the browser
extension covers most of what I need. It would be great if there was a
plugin for intilij/pycharms that did the same thing though. When I'm
checking in code is a bit too late to be finding out I have poor coverage.

-Ben

**Comment by stevepeak** [comment]
Incremental coverage was deployed just now. I utilized the logic from https://github.com/codecov/support/issues/5#issuecomment-103304437 with modifications necessary to achieve this process.

```diff
diff --git a/ex b/ex
@@ -1,3 +1,3 @@
+ new stmt
+ # ignored
- stmt old
+ stmt changed
```
>Coverage data: `1: hit, 2: none, 3: miss`

**Incremental coverage** would be 50%
