### ISSUE TITLE
Allow unified coverage reports to be distinguished in the UI

### ISSUE THREAD

**Issue by kentcdodds** [codecov/support#50]
I have e2e tests and unit tests and report coverage on both. It'd be nice to know that these particular lines are covered by unit tests, but not e2e tests, or these are covered by both, or these by one, or the other, or none.

**Comment by kentcdodds** [comment]
As part of this, it'd be great to be able to toggle one of the reports off so I can see coverage for only one of the reports.

**Comment by stevepeak** [comment]
@kentcdodds great suggestions! Thank you for the feedback and I'll keep notes about this feature here. Cheers!

**Comment by RyanCopley** [comment]
:+1: i was just thinking the same thing is needed

**Comment by stevepeak** [comment]
> Note: store report type that generated each line.

Which screenshot do you prefer for the UI?

# Toggle in the header

<img width="1559" alt="screen shot 2015-08-11 at 7 09 11 pm" src="https://cloud.githubusercontent.com/assets/2041757/9213051/813be192-405c-11e5-87ba-8292ff473020.png">

# Tooltip

<img width="468" alt="screen shot 2015-08-11 at 7 04 55 pm" src="https://cloud.githubusercontent.com/assets/2041757/9213007/162b2610-405c-11e5-9744-46f4577ae2d2.png">

**Comment by kentcdodds** [comment]
I prefer the Toggle in the header, though I don't see a problem with having both...

**Comment by stevepeak** [comment]
Deploying in next major release. We will post on Twitter / Newsletter when deployed. Thank you!
