### ISSUE TITLE
Coverage Suggestions Bug

### ISSUE THREAD

**Issue by reaperhulk** [codecov/support#51]
Taking a look at coverage suggestions on the pyca/cryptography repo shows a bunch of code that is covered, but it claims there are 62 missed lines and that coverage will reach 100.42% if they are covered:

https://codecov.io/github/pyca/cryptography/features/suggestions?ref=master

**Comment by stevepeak** [comment]
Thanks for pointing this out. Looks like we need to filter out fully covered chunks :)

**Comment by stevepeak** [comment]
Fixed this in a recent deploy. However its not retroactive. So the next commit will reflect the fix. Thanks!
