### ISSUE TITLE
Add flat badge

### ISSUE THREAD

**Issue by alex** [codecov/support#52]
The current badge doesn't match our repos other ones:

![screen shot 2015-07-03 at 8 30 46 pm](https://cloud.githubusercontent.com/assets/772/8505829/6abbcae4-21c2-11e5-872d-defebb7d66fb.png)

**Comment by stevepeak** [comment]
Thanks for the feedback @alex I'll be fixing to the default look on http://shields.io/. Deploying early this week.

[![codecov.io](https://img.shields.io/badge/Codecov-90%25-green.svg)](https://img.shields.io/badge/Codecov-90%25-green.svg)
