### ISSUE TITLE
branch shows most recent build rather than last build on branch

### ISSUE THREAD

**Issue by reaperhulk** [codecov/support#53]
When viewing a link like https://codecov.io/github/pyca/cryptography?branch=master (or the codecov badge) the most recently built job's data is shown rather than the last build against the actual master branch. This typically means a PR's coverage is showing when it should be master.

**Comment by reaperhulk** [comment]
It looks like this also affects the coverage change comment. The diff is not from master (or whatever branch the PR was submitted against) to the PR, it's from last build to current build.

**Comment by stevepeak** [comment]
I believe this is duplicate to #37. Which I plan to deploy early this week. Thank you :)
