### ISSUE TITLE
PHP coverage issue

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#56]
> The PHP cover.xml output has coverage data presented incorrectly. As [seen here][1]

### Line 49 Missed 
> https://travis-ci.org/stevepeak/Elastica/jobs/70055799#L3385

```xml
<line num="48" type="method" name="__construct" crap="2" count="0"/>
<line num="49" type="stmt" count="0"/>
<line num="50" type="stmt" count="0"/>
<line num="51" type="stmt" count="0"/>
<line num="52" type="stmt" count="0"/>
```

### Line 49 is omitted
> https://travis-ci.org/stevepeak/Elastica/jobs/70055800#L6530

```xml
<line num="48" type="method" name="__construct" crap="2" count="4"/>

<line num="50" type="stmt" count="4"/>
<line num="51" type="stmt" count="4"/>
<line num="52" type="stmt" count="4"/>
```

### Resulting coverage

```diff
+ <line num="48" type="method" name="__construct" crap="2" count="4"/>
- <line num="49" type="stmt" count="0"/>
+ <line num="50" type="stmt" count="4"/>
+ <line num="51" type="stmt" count="4"/>
+ <line num="52" type="stmt" count="4"/>
```

The cover.xml needs to include the `<line num="49" type="stmt" count="4"/>` when the method is hit.

-------

### To Do
Need to create an issue at https://github.com/sebastianbergmann/phpunit-documentation

[1]: https://codecov.io/github/ruflin/Elastica/lib/Elastica/Scroll.php?ref=eb3a787259a6c50f87bce507ff24b124d91c4fe7#l-42

**Comment by ruflin** [comment]
What I just realised is that the two builds have different PHP version (5.5 and 5.6), so the issue could even be related to the PHP version. The coverage "count" is done by XDebug, so it has to be checked in detail how the conversion to the clover output is done.

**Comment by ruflin** [comment]
@sebastianbergmann Perhaps you can give us some insights here?

@stevepeak I just stumbled over this presentation from @sebastianbergmann: https://thephp.cc/dates/2015/05/php-tek/code-coverage-covered-in-depth Seems like some new stuff is coming soon.

**Comment by stevepeak** [comment]
@ruflin do you think this is a common issue for PHP coverage? I though of a work around, but its some extra work... just need to know if its worth it.

**Comment by ruflin** [comment]
I would assume that this is a general issue with all PHP projects. I tried to find a list of other open source projects based on PHP which use codecov to check if they have the same issue, but couldn't find any. Do you know some projects I could check out?

The above described method should work. I assume to generate your reports, you have to go through all files anyways. So the above would not be a lot of additional processing work?

**Comment by stevepeak** [comment]
I'm still thinking of the best way to solve this with the least processing possible. I'll let you know what I come up with.

Meanwhile, I'm not sure whom else may be experiencing this issue. I'll keep an eye out for it. Thank you!

**Comment by stevepeak** [comment]
In the pipe for deployment. Will automatically take effect without configuration.
