### ISSUE TITLE
Dashboard: branch stats

### ISSUE THREAD

**Issue by rozhok** [codecov/support#57]
On a repository dashboard currently master branch is selected for view.

Since our team is makes rare merges to master branch and performs all active development in develop branch I want to be able to select default branch for dashboard view or I want to be able to select per-repository default branch for dashboard view.

Thanks,

**Comment by stevepeak** [comment]
Thank you for the feedback! We are in the process of a new dashboard and we will implement this concept as you have stated well.

Cheers!

**Comment by rozhok** [comment]
I see branches list on a project page. Many thanks!

**Comment by stevepeak** [comment]
Coming in next major release :+1:
