### ISSUE TITLE
GitHub team refresh button/link should also appear on account page

### ISSUE THREAD

**Issue by JoshRosen** [codecov/support#61]
On the "My Projects" page, there's a small refresh button for updating the list of teams associated with my GitHub account:

![image](https://cloud.githubusercontent.com/assets/50748/8794598/ea1f5628-2f39-11e5-8f87-e823d06cb148.png)

However, there doesn't seem to be any obvious way to perform this refresh from the "Account" page.  As a minor usability improvement, I think it would make sense to add a similar refresh button on this page, perhaps next to the "Github Accounts" header (or maybe at the bottom of this same list, next to the "View API Token" link):

![image](https://cloud.githubusercontent.com/assets/50748/8794628/282d4db2-2f3a-11e5-8d40-a351aedbbfac.png)

**Comment by stevepeak** [comment]
Thank you for the suggestion! I do agree that is a good place to put the refresh button as well. I'll add that now. Thank you!

**Comment by stevepeak** [comment]
Just deployed, thank you for the request :+1:
