### ISSUE TITLE
Can't switch between branches

### ISSUE THREAD

**Issue by slafs** [codecov/support#63]
There seems to be a problem with branches switching when branch name has `#` char in it which is very common when we have pull requests. Url gets updated with `?branch=#XX` which obviously confuses the browser. With `?branch=%23XX` (urlquoted `#`) everything works fine.

![codecov_branches](https://cloud.githubusercontent.com/assets/210173/8955637/d48c7c94-35ee-11e5-9a72-d828eb018b84.png)

**Comment by stevepeak** [comment]
Thank you for catching this. :+1:

**Comment by stevepeak** [comment]
Deploying, thank you!
