### ISSUE TITLE
Improve support for tox

### ISSUE THREAD

**Issue by treyhunner** [codecov/support#64]
I'm looking into adding codecov to django-rest-framework.  I ran a [build][travis] on Travis, but it didn't result in any reports on codecov.

I then ran the codecov bash command locally and it resulted in coverage showing up as inside a tox folder: [see report][codecov].

It would be nice if codecov could squash tox runs into a single directory in the correct structure.

[codecov]: https://codecov.io/github/treyhunner/django-rest-framework?branch=travis-test
[travis]: https://travis-ci.org/treyhunner/django-rest-framework/builds/73603968

**Comment by stevepeak** [comment]
The backend now remove the extra path `tox/[^/]+/lib/[^/]+/site-packages/` found in the reports. Thank you!
