### ISSUE TITLE
coverage info became null after early moving to new github organization permissions features

### ISSUE THREAD

**Issue by vasily-v-ryabov** [codecov/support#66]
Codecov.io shows 0% coverage (https://codecov.io/github/pywinauto/pywinauto) but [AppVeyor build log](https://ci.appveyor.com/project/vasily-v-ryabov/pywinauto/build/0.5.0.114/job/6yfn4tc6m4nc6q0n) indicates that codecov tool submitted the data OK.

    codecov
    Uploaded: True
    Report URL: http://codecov.io/github/pywinauto/pywinauto?ref=e12b75fd15bdeb0d62c3989f36ee4016ac703b93
    Upload Version: codecov-v1.2.3
    Message: Coverage reports upload successfully

I'm not sure that new github permission features is the root cause. This feature enhances access rights, there's no new restrictions. New codecov version may break it down as well.

**Comment by stevepeak** [comment]
Sorry for this issue. Can you restart this build. I'm going to capture the raw upload and debug from there. Thanks!

**Comment by vasily-v-ryabov** [comment]
OK, started new build with new commit.

**Comment by stevepeak** [comment]
[Raw upload][1] contains files that the uploader "thought" were coverage files and therefore did not call `coverage xml`. This is a process I'm looking to improve upon, but for now please add:

```
coverage xml && codecov
```

Thank you!

[1]: https://codecov.s3.amazonaws.com/repos/FE4F1699F8978F7A5D60D3D71E0669FD/raw/upload:1438616790.643630.txt

**Comment by vasily-v-ryabov** [comment]
The workaround helped. Thanks!
