### ISSUE TITLE
PR failing if test coverage went down

### ISSUE THREAD

**Issue by tabuchid** [codecov/support#68]
Is it possible to have a commit/PR fail if overall test coverage went down in the PR?
I see options for coverage for a single commit or patch but I'm looking into having a simple test if the coverage went down by X% then fail.

**Comment by stevepeak** [comment]
I'm working on this now. Should be deploying this week. It will be a flagged feature. What repos would you like flagged in? Thanks!

**Comment by tabuchid** [comment]
Awesome. Thanks @stevepeak 
percolate/ios-api and percolate/ios

**Comment by stevepeak** [comment]
Ok, flagging those repos. Please do not update the Status feature in Codecov UI, it will override the flag. Thank you! I'll be monitoring these repos.

**Comment by stevepeak** [comment]
Based on customer feedback I'll be improving the reference point of these comparisons. Flagged repos will see this change when deployed. Thanks!

**Comment by stevepeak** [comment]
<img width="908" alt="screen shot 2015-08-11 at 1 16 21 pm" src="https://cloud.githubusercontent.com/assets/2041757/9204450/57b9a0e2-402b-11e5-86dd-6c1f37c91be3.png">

> [See animated git here](http://cl.ly/image/2i2b42400Q1D)

This is deploying soon. Looking for feedback :) Thanks!

### Changes
1. Removing **Commit Status**, from my research it is not used as often and is not as impactful as the Patch Coverage (now called Incremental Coverage)
1. Added new **Smart Mode** as seen in the screen shot above. There is still the "minimum" input field which is called our static mode.

**Comment by adiroiban** [comment]
Was this deployed ?

I have this PR in which the coverage was decreased, but codeve/project status is green - https://github.com/twisted/twisted/pull/259

**Comment by stevepeak** [comment]
Yes it was. I can help explain this:

```
codecov/patch — Coverage not affected when comparing bb0d1d6...e0a5736
codecov/project — Absolute coverage decreased by -0.69% but relative coverage increased by +10.23% compared to bb0d1d6
```

- **patch** was not affected because no lines in the compare were tracked by coverage
- **project** coverage decreased due to removing code, see this example below:


```diff
  line 1 covered
  line 2 missed
- line 3 covered
- line 4 covered
```
> Coverage before: 75%. Coverage after: 50%

**Comment by adiroiban** [comment]
Thanks. I suggest to also show that information in the page available in the "Details" link.

With Chrome I had to check the source code to see the full message.

**Comment by stevepeak** [comment]
Good call... I'll come up with something and reply back here
