### ISSUE TITLE
Slow load time

### ISSUE THREAD

**Issue by RyanCopley** [codecov/support#7]
```
I have been seeing the long page loads and looking into a better way to check repo permissions. Unfortunatly there is no “Best fit” api that match my needs. But I’ll be reviewing this today.
```

Loading our orgs page is very slow (20+ seconds), we believe this is because of the lack of cache on determining if a member has access or not.

**Comment by stevepeak** [comment]
Now caching what private repos the acting user can access to speed up performance. The first page load will still be long to build the cache. Cheers!
