### ISSUE TITLE
Increased permissions

### ISSUE THREAD

**Issue by jimhester** [codecov/support#70]
Previously coveralls only required the following permissions

- Read org and team membership
- Access commit status
- Access user email addresses (read-only) 

Now it seems to also require

- Access private repositories

In particular the private repository access grants both read and _write_ access to the repositories, which is somewhat concerning to me.

I don't think anything nefarious is going on and I know there are some issues with GitHub's permission granularity, but I was interested in the rational for the change and if it is possible to opt-in to the legacy permissions.

**Comment by stevepeak** [comment]
Hey @jimhester We still only need the permission you have mentioned. This may be due to a cookie on your browser. Can you check to see if a cookie called `ghpr` was created by Codecov?

Thank you

**Comment by jimhester** [comment]
I think I know what happened.  I had a private fork on my personal account which I have since deleted, but I did not clear my cookies before re-trying the permissions.

Removing the `ghpr` cookie, revoking permissions, logging out of codecov, then logging in again fixed the issue.

Thanks for the quick response Steve!

**Comment by dotnetCarpenter** [comment]
FYI I see the same and got the `ghpr` (true) cookie but haven't forked anything. Anyway removing the cookie helped.
