### ISSUE TITLE
Improvements are suggested for 100% covered code

### ISSUE THREAD

**Issue by kmike** [codecov/support#72]
See https://codecov.io/github/scrapy/parsel/features/suggestions?ref=bd61b43a69794227e4a2f23596797dafceb3d2a1:

![screen shot 2015-08-21 at 1 05 43 pm](https://cloud.githubusercontent.com/assets/107893/9404043/61bca6de-4805-11e5-87f3-45d2c919f4f0.png)

**Comment by stevepeak** [comment]
Thank you @kmike for the issue. Deployed and fixed :) (ps. sorry for delay on reply)

**Comment by kmike** [comment]
Thanks @stevepeak!
