### ISSUE TITLE
Option for more precision on Codecov badges

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#77]
Add an option to increase precision on badges via http argument.

Default: `https://codecov.io/github/owner/repo/coverage.svg?precision=0` == `10%`
More: `https://codecov.io/github/owner/repo/coverage.svg?precision=1` == `10.1%`
Most: `https://codecov.io/github/owner/repo/coverage.svg?precision=2` == `10.11%`

**Comment by jklemm** [comment]
Thanks Steve!
