### ISSUE TITLE
Automatic token retrieval for Travis Matrix builds

### ISSUE THREAD

**Issue by jimhester** [codecov/support#78]
Normal Travis builds do not require specifying a CODECOV_TOKEN (as I presume it is looked up by the travis job id).  However this does not work for matrix builds.

Is this a known limitation and is there a way for me to get this working without having to supply an upload token?

I saw https://github.com/codecov/enterprise/wiki/Configuration#delay-policy, but that seems to only apply to codecov enterprise.

**Comment by stevepeak** [comment]
Hey @jimhester do you have a repo that is not working? There are many customers using matrix builds with out a problem without the token... Perhaps there is some other issue at hand

**Comment by jimhester** [comment]
https://travis-ci.org/ropensci/binomen/jobs/77516586#L3110 was the one reported at https://github.com/jimhester/covr/issues/107.  I had run into the issue as well at https://travis-ci.org/gaborcsardi/argufy/jobs/75725712#L2137.

It may be a r-builder or covr issue somehow, if so let me know and I can fix it.

**Comment by stevepeak** [comment]
Likely missing environment variables. You can find a complete list of supported CI's and their vars here: https://github.com/codecov/codecov-python/blob/master/codecov/__init__.py#L212-L379 Let me know if that does the trick :+1:

**Comment by stevepeak** [comment]
@jimhester How are we looking on this? Thank you!
