### ISSUE TITLE
Space in a folder or file causes coverage location in the Web UI to break

### ISSUE THREAD

**Issue by RyanCopley** [codecov/support#8]
I have a folder called `Framework UI` deep in my projects folder structure, but it shows up as `UI` in the root of my project in codecov's web UI

**Comment by stevepeak** [comment]
Hey @RyanCopley can you try this change to the uploader and see it it resolves the issue. Thanks!

https://github.com/codecov/codecov-bash/compare/master...fix/newlines

```cul
bash <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/fix/newlines/codecov)`
```

**Comment by stevepeak** [comment]
Merged at https://github.com/codecov/codecov-bash/commit/cdbe907cd341defc8a8f1c488b0237cc0be2235b
