### ISSUE TITLE
Ignore/Skip lines in file

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#83]
> Supporting **all** languages via [Python](https://github.com/codecov/codecov-python/commit/39f7ab5b3dba6a5e39f47e15f18323662e770201) (Node, Bash coming soon) uploader.
> Enable via `codecov --flag-feature skip`
> Current spec open for discussion

Add the following to skip over lines/blocks of code you do not wish to track coverage on.

```js
if (debug) { /* codecov skip start */
  var ok = "Content you don't need tracked by Codecov";
} /* codecov skip start */

var trackthis = true;
if ( trackthis ){
  alert("It will :)");
  alert("But not this..."); # codecov skip
}

/* codecov skip start */
if (debug) {
  var ok = "Content you don't need tracked by Codecov";
} 
/* codecov skip start */
```
> The reason we are using `codecov` and prevent confusion of "where" is processing the skipped lines. When **running coverage locally** lines will remain covered, not respecting this feature. Only when the coverage reports are uploaded to Codecov properly will the skipped lines be respected.

# Syntax Options

### Single line
```
/* codecov skip */
# codecov ignore
```

### Start block
```
/* codecov skip start */
/* codecov start skip */
/* codecov ignore start */
/* codecov start ignore */
# codecov skip start
# codecov start skip
# codecov ignore start
# codecov start ignore
```

### End block
```
/* codecov skip end */
/* codecov end skip */
/* codecov ignore end */
/* codecov end ignore */
# codecov skip end
# codecov end skip
# codecov ignore end
# codecov end ignore
```

**Comment by kentcdodds** [comment]
Honestly, I probably wouldn't use this feature. I would prefer to avoid encoding a dependency on a third party service in my code. Free tools are one thing (Istanbul comments for example), but paid services are another in my opinion...

Also, I'd prefer the reports in codecov to reflect exactly what the reports are locally. The less magic the better.

**Comment by stevepeak** [comment]
@kentcdodds thanks for the honesty :) That was my worry of depending on a 3rd party product and not something native. I'll keep this on the back-burner to accept more customer feedback to see if anyone needs this.

**Comment by jayvdb** [comment]
I'd also not like to include `# codecov skip` or similar in my source.
Partially because it is a third party SaaS, but also because it is only one tool.  For the same reason I dont like using `pylint` comments in the source code.
Adding something like the `.coveragerc` `exclude_lines` regex's in a `.codecov.yml` (#105) would be much more desirable.

If you added support for `exclude_lines` regex, you could achieve a similar result by having default `exclude_lines` regex for `'# codecov skip'` and (multiline) `'\/* codecov skip start.* codecov skip end *\/'`

**Comment by stevepeak** [comment]
This issue is presented for other languages. If I recall: C and ES6 have issues with ignoring coverage. Presenting this concept is a short term solution until something more native (non vendor) is fixed.

I'm still hesitant to add this as well... As of not its unlikely.

**Comment by kentcdodds** [comment]
The ES6 issues were resolved recently :-)

**Comment by bukzor** [comment]
I've already configured my python tool (coveragepy) to ignore certain lines.
It would be ideal if codecov would ask coveragepy which lines are covered/ignored.

**Comment by stevepeak** [comment]
> It would be ideal if codecov would ask coveragepy which lines are covered/ignored.

The xml reports produced by coveragepy will reflect the skipped lines set forth in `.coveragerc`. So this should not be an issue for Python (and please let me know if you have any). 

This issue was created to help problems specific to ES6, which seem to have been completed already. So Codecov likely will not have any custom solution.

**Comment by OktoberComstock** [comment]
Hi there! This may be a noobie question, but where would I be placing the above code in? In the codecov.yml file? Or would I have to wrap this around every line of code every time I needed it to be ignored? I'm using swagger-docs with Ruby and would love to be able to ignore the swagger syntax lines within my controllers. Thank you!

**Comment by OktoberComstock** [comment]
Can this work without the codecov Python uploader setup?

**Comment by OktoberComstock** [comment]
Was this ever implemented and merged? @stevepeak

**Comment by stevepeak** [comment]
Not really...Codecov does not scan for it's own comments. There are a couple reasons why:

1. It is not efficient to scan through every file for this syntax.
2. Codecov does not clone or store source code server side - so all this processing would be done during CI builds.
3. It should be the responsibility of the language's coverage collecting agent to ignore lines.

With that being said: @OktoberComstock what is your programming language and examples of lines you would like to ignore?

**Comment by mkchoi212** [comment]
@stevepeak If I could add something to this, I personally would love a feature that would allow me to ignore lines that go something like this.

```c
if( ( bb->buf = ( unsigned char * )realloc( bb->buf, newlen ) ) == NULL ) {  /* TEST */
       fprintf( stderr, "grow: Could not allocate more buffer space" );      /* IGNORE */
       exit( EXIT_FAILURE );                                                 /* IGNORE */
}
```
 I wrote the code within the if statement to simply print a message and crash the program when `realloc` fails to allocate more space. Personally, I think code like this doesn't need to be tested because the block's behavior is quite obvious.

**Comment by stevepeak** [comment]
We would love to do this, however, the overhead of scanning every file for `/* ignore */` may be to elaborate.

@mkchoi212 For `C` you can use `// LCOV_EXCL_SKIP`

**Comment by mkchoi212** [comment]
@stevepeak Thanks. I will give that a go
