### ISSUE TITLE
Show the build status on codecov/commits page.

### ISSUE THREAD

**Issue by ckadam** [codecov/support#85]
The codecov commits page (https://codecov.io/github/<repo>/commits?page=1) shows the list of latest commits on various branches in the repo, and corresponding code coverage number. It would be nice to display the build status next to coverage number. This would be a visual hint to indicate that drop in coverage could be b'cos of incomplete build. 

PS: such visual clue is provided in the individual coverage details page.

**Comment by stevepeak** [comment]
Great idea! Thank you @ckadam

**Comment by stevepeak** [comment]
Deploying shortly. Thank you!
