### ISSUE TITLE
Add an option to not fail on missing token

### ISSUE THREAD

**Issue by slafs** [codecov/support#86]
In python client (`codecov<1.3`) the `codecov` command ended just fine when a token was missing.
This changed and broke our builds after upgrading to `1.3.x` because now `codecov` is complaining about missing token. 

We would like to reuse our tests suites but not every build environment will have `CODECOV_TOKEN` configured. So option like `--dont-fail-on-missing-token` would be nice.

**Comment by stevepeak** [comment]
Hey @slafs sorry about your builds! How about `-q --quiet` mode?

**Comment by slafs** [comment]
but that would imply no output, right? I was aiming for something rather to prevent failing from this particular reason. E.g. I want to know what's going on when I have a token but for example have not configured a repo on `codecov.io`

**Comment by stevepeak** [comment]
That makes sense. `quiet` does suggest no output. I'm attempting to be more general here by setting a flag to not fail the build. `--no-fail`, `--no-exit`...

Thoughts?

**Comment by slafs** [comment]
right, `--no-fail` sounds good :+1:

**Comment by stevepeak** [comment]
Deployed in `v0.4.1`

**Comment by slafs** [comment]
I'm sure you meant `v1.4.1` ;)

**Comment by stevepeak** [comment]
Yes, sorry :) Thanks @slafs
