### ISSUE TITLE
Commit Status - Incremental coverage check should exclude files for which coverage does not exist.

### ISSUE THREAD

**Issue by ckadam** [codecov/support#87]
For example, if we make changes to one of the configuration file (.ini) as part of the PR and that happens to only change in the PR, then "Incremental Coverage" check fails with following error message.

`CI failed: coverage not measured fully.`

Expected Behavior:
- If PR changes includes files for which Coverage Data does not exist, then such files should not be considered for Incremental coverage check, and commit status should not be marked as Failed.

**Comment by stevepeak** [comment]
@ckadam Thank you for the issue! 

The message `CI failed: coverage not measured fully.` is only relevant to the fact that the CI builds failed. If the builds passed for this specific pull request, and the .ini file had no impact on the coverage, then Codecov would have reporting a successful status (given coverage remains the same or increased).

I would present a concept of creating a `codecov.yml` file which can present configuration relevant to this situation.

```yml
# codecov.yml (not implemented yet)
status:
  ignore:
    - "*.ini"
    - "*.md"
  project: on
  patch: 85
```

According to the configuration above: if a single commit (or pull request) only changes `.ini` or `.md` files then Codecov will not post a status at all (or maybe a success that says "coverage ignored" to acknowledge Codecov did its job)

I would like to open this issue for all customers to leave feedback and contribute to the idea of a `codecov.yml` file to specify configuration of status and all other features.

----


#### Configuration can impact coverage

I understand the request here and believe it can be programmed in to Codecov. However, my issue with this is that configuration files for the project may impact coverage. Lets take this example below:

```python
# file.py
def method(x):
  if debug:
    print 'degugging'
  return x * 10
```

```yml
# travis.yml
env:
  DEBUG: true | false
```

Simply toggling a configuration will impact coverage. In this example the `.travis.yml` file does not have coverage data, but does impact project coverage.

**Comment by stevepeak** [comment]
@ckadam have you seen this issue lately? Thank you!
