### ISSUE TITLE
Project status threshold

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#88]
By default commits will fail if they drop `0.01%` in coverage compared to their parent (learn more about how we determine this [here][1])

Add a setting for a threshold on how much the coverage may be allow to dropped.

[1]: https://github.com/codecov/support/wiki/When-comparing-commits

**Comment by blueyed** [comment]
I think the coverage of a patch and the project's total are different things, e.g. the project's coverage should never drop, but the coverage of the patch/diff should be still e.g. 80 or 100%.

**Comment by stevepeak** [comment]
This is how it's set up now. A couple customers are asking for a threshold on how far the **project** status is allowed to fall to consider a pass.
