### ISSUE TITLE
Display what has changed

### ISSUE THREAD

**Issue by RyanCopley** [codecov/support#9]
It would be nice to be able to see what "changed", as like this:

![7iezqdmbycgxbfup39md32pelq2nrr0oe4fxle1ztki](https://cloud.githubusercontent.com/assets/819591/7736812/7800a9b6-ff14-11e4-9242-ba25b3cc5fb4.jpg)

**Comment by stevepeak** [comment]
Moved/Duplicate of #20. Thanks!
