### ISSUE TITLE
Only first line of multi-line statements colored by coverage

### ISSUE THREAD

**Issue by plaes** [codecov/support#93]
It currently seems that the coverage.xml parser doesn't properly handle multiline expressions like below, only marking the first line of the expression as not passing:

```
import foo,\
    bar                          # this line is marked tested
```
and

```
call_function(foo,
    bar,                          # this line is marked tested
    arg3,                        # this line is marked tested
    arg4)                        # this line is marked tested
```

The problem seems to lie on how coverage.xml seems to be set up. For example, a file with multiline expression is reported with following "missing block":
569-592, the relevant section in `coverage.xml` file contains following:
```
<line hits="1" number="562"/>
<line hits="0" number="569"/>
<line hits="0" number="576"/>
<line hits="0" number="577"/>
<line hits="0" number="578"/>
<line hits="0" number="579"/>
<line hits="0" number="581"/>
<line hits="0" number="583"/>
<line hits="0" number="584"/>
<line hits="0" number="585"/>
<line hits="0" number="586"/>
<line hits="0" number="587"/>
<line hits="0" number="588"/>
<line hits="0" number="589"/>
<line hits="0" number="590"/>
<line hits="0" number="592"/>
```

And the function which should be 100% untested, except the signature (starting from line 562) looks following:

```
562     def sign2(self, request, overwrite=False, delete=True, lifetime=None):
563         """
564         Sign directly using private key, this is usually done by root.
565         Basic constraints and certificate lifetime are copied from openssl.cnf,
566         lifetime may be overridden on the command line,
567         other extensions are copied as is.
568         """
569         cert = raw_sign(
570             crypto.load_privatekey(crypto.FILETYPE_PEM, open(self.private_key).read()),
571             self.certificate._obj,
572             request._obj,
573             self.basic_constraints,
574             lifetime=lifetime or self.certificate_lifetime)
575
576         path = os.path.join(self.signed_dir, request.common_name + ".pem")
577         if os.path.exists(path):
578             if overwrite:
579                 self.revoke(request.common_name)
580             else:
581                 raise FileExistsError("File %s already exists!" % path)
582
583         buf = crypto.dump_certificate(crypto.FILETYPE_PEM, cert)
584         with open(path + ".part", "wb") as fh:
585             fh.write(buf)
586         os.rename(path + ".part", path)
587         click.echo("Wrote certificate to: %s" % path)
588         if delete:
589             os.unlink(request.path)
590             click.echo("Deleted request: %s" % request.path)
591
592         return Certificate(open(path))
```

And the example from coverage terminal output (with extras removed):
```
certidude/wrappers.py               399    294    26%   [removed], 569-592, [removed]
```

**Comment by plaes** [comment]
And I get 100% same `coverage.xml` with both coverage and pytest-cov.

**Comment by stevepeak** [comment]
This is an issue with [coverage.py](https://bitbucket.org/ned/coveragepy). I'm not sure if an issue exists already, but I suggest submitting an issue there. Thank you!

**Comment by nedbat** [comment]
If coverage.xml says that lines 569-592 are uncovered, then either that code is not run, or you haven't configured coverage.py properly.  Perhaps the function is being executed in a subprocess?

**Comment by plaes** [comment]
@nedbat Actually the not covered lines do not show up in `coverage.xml`.

For example if I have multiline construction like lines 569-574, only line 569 ends up in coverage.xml.

**Comment by stevepeak** [comment]
@plaes If I may. `+` represent lines "covered" in `coverage.xml`.

## Currently
```diff
+def method(argument_a,
                    argument_b):
   pass 
```

## You would like
```diff
+def method(argument_a,
                    argument_b):
   pass 
```

```diff
+def method(argument_a,
+                   argument_b):
   pass 
```

**Comment by nedbat** [comment]
Your first comment shows statements split over multiple lines.  Your larger example shows a multi-statement function definition.  These are separate issues.

Coverage.py will only mark the first line of a multi-line statement.   But a multi-statement function definition is properly handled, with each statement having its own data, as you can see in the coverage.xml.  If the body of the function is marked as not covered, then either the body of the function isn't being executed, or coverage isn't running when the function executes.  This latter can happen if the function is executed in a subprocess, for example.

Can you share a pointer to your code, with details of how you are running coverage.py?  I assure you it can handle multi-line function definitions just fine.  It would be useless if it couldn't.

**Comment by stevepeak** [comment]
@nedbat upon reviewing this again I have have been mistaken on the source of the issue.

```diff
+def method():
+    call_this(arg1,
               arg2,
               arg3)
+    call_that()

<line hits="1" number="1"/>
<line hits="1" number="2"/>
<line hits="1" number="5"/>
```
> Note that the xml shows line 2 & 3 are not measured.

@plaes can you confirm this is the issue? Thank you!

**Comment by plaes** [comment]
Yup, this is the issue. It only adds first line to the xml file. Same issue happens also with non-covered lines.

**Comment by nedbat** [comment]
Just to be clear, this line from your original description is a completely different issue:
```
certidude/wrappers.py               399    294    26%   [removed], 569-592, [removed]
```

**Comment by peterjc** [comment]
For any multi-line Python constructions including triple quote strings, the continuation ``\``, and brackets, when viewing Python files on codecov.io - only the first line gets the red/green background indicating if the tests executed it. i.e. The problem as described by @stevepeak (with clear illustrations).

I would expect the display code which maps ``coverage.xml`` onto a Python script to automatically apply the coloration to multi-line statements as a block.

Can we re-title this bug to something like "Only first line of multi-line statements colored by coverage"?

**Comment by stevepeak** [comment]
@peterjc thank you for the suggestion :+1: I've changed the title.

**Comment by peterjc** [comment]
Does this still count as "invalid" or can it be relabeled too? Thanks.

**Comment by stevepeak** [comment]
The reason for it being labeled `invalid` is because this "issue" is on the behalf of `coveragepy`. The reports generated by `coverage xml` express this issue and therefore Codecov expresses it.

*IMO* I agree with the way `coveragepy` handles this. The method should only be marked as tested once (therefore counted as 1 hit for totals). However, Codecov is being improved soon and this concept *may* be able to be implemented in the future, but the value of these methods will remain 1 hit and the proceeding lines will be highlighted as hit, but not actually be "counted" towards the total coverage. Thoughts?

**Comment by peterjc** [comment]
I hope this answers the question: If I have a Python file with just a four line statement (lots of brackets or '\\' continuations, doesn't matter), which is executed during the tests, then I want to see its coverage reported as 100% (ideally as 4 out of 4 lines, but counted as 1 or 1 lines would be fine), but *not* as 25% (1 out of 4 lines). I've not dug into the Codecov system to see exactly how it counts multi-line statements.

I was more interested in fixing the visual representation when browsing the source code on the Codecov website, looking for things which need tests.

**Comment by plaes** [comment]
>>> I hope this answers the question: If I have a Python file with just a four line statement (lots of brackets or \ continuations, doesn't matter), which is executed during the tests, then I want to see its coverage reported as 100% (ideally as 4 out of 4 lines, but counted as 1 of 1 lines would be fine), but not as 25% (1 out of 4 lines).

This was the main reason I opened the bug.

**Comment by stevepeak** [comment]
@peterjc sounds good, we are on the same page here.

To be clear the the coverage (in Codecov and coveragepy) is 100% (3/3) as expressed below, not 60% (3/5).

> **Codeov / Coveragepy** Coverage 100% 3/3.
```diff
+def method():
+    call_this(arg1,
               arg2,
               arg3)
+    call_that()
```

> **NOT** the case. Coverage 60% 3/5.
```diff
+def method():
+    call_this(arg1,
-              arg2,
-              arg3)
+    call_that()
```

> **Future Codecov** Coverage 100% 3/3
```diff
+def method():
+    call_this(arg1,
+              arg2,
+              arg3)
+    call_that()
```
