### ISSUE TITLE
Rebase needs to delete old commits on branch.

### ISSUE THREAD

**Issue by stevepeak** [codecov/support#97]
When rebasing old commits on Codecov are still visible in the branch view, but are not longer necessary to store when a branch has been rebased. Currently the latest commit overlap, with matching timestamps. 

1. Keep track of base commit for branches
2. If the base changes: tag commits as deleted if no longer in same git-tree

**Comment by albfan** [comment]
Let me known an I check as soon as it's deployed

**Comment by stevepeak** [comment]
Deploying in next major release. We will post on Twitter / Newsletter when deployed. Thank you!
