### ISSUE TITLE
broken styles for coverage diff

### ISSUE THREAD

**Issue by kmike** [codecov/support#99]
I'm on OS X 10.11, Firefox 41.0.2. This is how coverage diff displayed - a column with line numbers is too narrow:

![screen shot 2015-10-17 at 4 05 34 am](https://cloud.githubusercontent.com/assets/107893/10555172/75433596-7484-11e5-8d80-c6814117aa07.png)

**Comment by stevepeak** [comment]
Thank you @kmike for sending this in. We just deployed changes to this to improve processing speed.
